using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace LittleFocus {
 static class UI {
  public static Color Bg=Color.FromArgb(245,244,237), Ink=Color.FromArgb(40,53,46), Green=Color.FromArgb(53,89,65), Soft=Color.FromArgb(232,239,222), Muted=Color.FromArgb(105,115,106), Purple=Color.FromArgb(115,86,143);
  public static Font Font(float size,bool bold=false){return new Font("Microsoft YaHei UI",size,bold?FontStyle.Bold:FontStyle.Regular);}
  public static Label Label(string text,float size=10,bool bold=false){return new Label{Text=text,Font=Font(size,bold),ForeColor=Ink,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,AutoEllipsis=true,Margin=new Padding(4)};}
  public static Button Button(string text,Action action,bool primary=false){var b=new Button{Text=text,AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,MinimumSize=new Size(88,36),Padding=new Padding(10,4,10,4),FlatStyle=FlatStyle.Flat,BackColor=primary?Green:Color.White,ForeColor=primary?Color.White:Ink,Font=Font(9.5f),Margin=new Padding(4),UseVisualStyleBackColor=false};b.FlatAppearance.BorderColor=primary?Green:Color.FromArgb(216,223,209);b.Click+=(s,e)=>action();return b;}
  public static FlowLayoutPanel Flow(params Control[] controls){var p=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,WrapContents=true,Margin=new Padding(0)};p.Controls.AddRange(controls);return p;}
  public static TableLayoutPanel Table(int cols,params float[] rows){var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=cols,RowCount=rows.Length,Margin=new Padding(0)};foreach(var r in rows)t.RowStyles.Add(new RowStyle(r<0?SizeType.Percent:SizeType.Absolute,Math.Abs(r)));t.ControlAdded+=(s,e)=>{int row=t.GetRow(e.Control);if(e.Control is FlowLayoutPanel&&row>=0&&row<t.RowStyles.Count&&t.RowStyles[row].SizeType==SizeType.Absolute)t.RowStyles[row].SizeType=SizeType.AutoSize;};return t;}
  public static TextBox TextBox(bool multi=false){return new TextBox{Dock=DockStyle.Fill,Width=260,Font=Font(10),Multiline=multi,ScrollBars=multi?ScrollBars.Vertical:ScrollBars.None,Margin=new Padding(4),BorderStyle=BorderStyle.FixedSingle};}
  public static DataGridView Grid(){return new DataGridView{Dock=DockStyle.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,RowHeadersVisible=false,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,Font=Font(9),EnableHeadersVisualStyles=false,ColumnHeadersHeight=36,ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.DisableResizing,RowTemplate={Height=34},ColumnHeadersDefaultCellStyle=new DataGridViewCellStyle{BackColor=Soft,ForeColor=Ink,Font=Font(9,true)},DefaultCellStyle=new DataGridViewCellStyle{SelectionBackColor=Color.FromArgb(218,231,204),SelectionForeColor=Ink,Padding=new Padding(4)},AllowUserToResizeRows=false};}
  public static void FormStyle(Form f,string title,int width,int height){f.Text=title;f.AutoScaleMode=AutoScaleMode.None;f.ClientSize=new Size(width,height);f.MinimumSize=new Size(width,height);f.StartPosition=FormStartPosition.CenterScreen;f.BackColor=Bg;f.Font=Font(10);f.ForeColor=Ink;f.Icon=SystemIcons.Application;f.Load+=(s,e)=>PrepareScale(f);}
  public static void PrepareScale(Form f){if(f.AutoScaleMode==AutoScaleMode.Dpi)return;f.SuspendLayout();f.AutoScaleMode=AutoScaleMode.Dpi;f.AutoScaleDimensions=new SizeF(96,96);f.ResumeLayout(true);f.PerformAutoScale();var area=Screen.FromControl(f).WorkingArea;f.MinimumSize=new Size(Math.Min(f.MinimumSize.Width,area.Width-20),Math.Min(f.MinimumSize.Height,area.Height-20));f.Size=new Size(Math.Min(f.Width,area.Width-20),Math.Min(f.Height,area.Height-20));f.PerformLayout();}
 }
 public class StagePath:Control {
  List<Stage> stages=new List<Stage>();
  public StagePath(){DoubleBuffered=true;BackColor=UI.Soft;Height=54;MinimumSize=new Size(120,54);}
  public void UpdateStages(IEnumerable<Stage> value){stages=value==null?new List<Stage>():value.ToList();Visible=stages.Count>0;Invalidate();}
  protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(stages.Count==0)return;var g=e.Graphics;int left=28,right=Math.Max(left+1,Width-28),ground=Height-14;using(var trunk=new Pen(Color.FromArgb(105,115,80),4)){g.DrawLine(trunk,Width/2,ground,Width/2,12);}using(var branch=new Pen(Color.FromArgb(133,145,102),2)){g.DrawLine(branch,Width/2,Height/2,right,Height/2);g.DrawLine(branch,Width/2,Height/2,left,Height/2);}for(int i=0;i<stages.Count;i++){int x=stages.Count==1?Width/2:left+(right-left)*i/Math.Max(1,stages.Count-1);int y=12+(i%2)*12;Color fruit=stages[i].Done?UI.Green:(i==stages.FindIndex(s=>!s.Done)?Color.FromArgb(232,169,67):Color.White);using(var b=new SolidBrush(fruit))using(var p=new Pen(UI.Green,2)){g.FillEllipse(b,x-8,y-8,16,16);g.DrawEllipse(p,x-8,y-8,16,16);}using(var leaf=new SolidBrush(Color.FromArgb(87,126,79))){g.FillEllipse(leaf,x+5,y-9,8,4);}}}
  } public class Notice:Form {
  static IEnumerable<Button> FindButtons(Control c){if(c is Button)yield return (Button)c;foreach(Control child in c.Controls)foreach(var b in FindButtons(child))yield return b;} public TextBox Detail;
  System.Windows.Forms.Timer live;
  Func<string> liveProvider;string baseText="",encouragement="";
  void UpdateDetail(){if(IsDisposed)return;string value=((liveProvider==null?baseText:liveProvider())+(encouragement.Length>0?"\n\n给此刻的你：\n"+encouragement:"")).Replace("\r\n","\n").Replace("\n","\r\n");if(Detail.Text!=value){int start=Detail.SelectionStart,len=Detail.SelectionLength;Detail.Text=value;Detail.Select(Math.Min(start,value.Length),Math.Min(len,Math.Max(0,value.Length-start)));}}
  public void AddEncouragement(string text){encouragement=text;UpdateDetail();}
  public void SetLiveText(Func<string> provider){liveProvider=provider;if(live!=null)live.Dispose();live=new System.Windows.Forms.Timer{Interval=500};live.Tick+=(s,e)=>UpdateDetail();live.Start();}
  protected override void Dispose(bool disposing){if(disposing&&live!=null)live.Dispose();base.Dispose(disposing);}
  public Notice(string title,string text,params KeyValuePair<string,Action>[] actions){
   baseText=text;
   UI.FormStyle(this,title,600,430);TopMost=true;ShowInTaskbar=true;MaximizeBox=false;MinimizeBox=false;FormBorderStyle=FormBorderStyle.Sizable;Padding=new Padding(24);
   var root=UI.Table(1,60,-100,76);var heading=UI.Label(title,17,true);heading.AutoSize=true;heading.AutoEllipsis=false;root.RowStyles[0].SizeType=SizeType.AutoSize;root.Controls.Add(heading,0,0);Detail=new TextBox{Text=text.Replace("\r\n","\n").Replace("\n","\r\n"),Multiline=true,ReadOnly=true,TabStop=true,BorderStyle=BorderStyle.None,ScrollBars=ScrollBars.Vertical,Dock=DockStyle.Fill,Font=UI.Font(11),BackColor=UI.Bg,ForeColor=UI.Ink,Margin=new Padding(4,14,4,12)};Detail.MouseEnter+=(s,e)=>{if(!Detail.Focused){int start=Detail.SelectionStart,len=Detail.SelectionLength;Detail.Focus();Detail.Select(start,len);}};Shown+=(s,e)=>{Detail.Select(0,0);var firstButton=Controls.Cast<Control>().SelectMany(c=>FindButtons(c)).FirstOrDefault();if(firstButton!=null)firstButton.Focus();};root.Controls.Add(Detail,0,1);
   var buttons=UI.Flow();bool first=true;foreach(var item in actions){var captured=item;buttons.Controls.Add(UI.Button(item.Key,()=>{Close();if(captured.Value!=null)captured.Value();},first));first=false;}root.Controls.Add(buttons,0,2);Controls.Add(root);
  }
 }
 public class TaskListBox:ListBox {
  public int ActiveIndex=-1;public bool Animate;
  public TaskListBox(){DrawMode=DrawMode.OwnerDrawFixed;ItemHeight=46;DoubleBuffered=true;SetStyle(ControlStyles.OptimizedDoubleBuffer|ControlStyles.AllPaintingInWmPaint,true);}
  protected override void OnFontChanged(EventArgs e){base.OnFontChanged(e);ItemHeight=Math.Max(46,Font.Height+22);}
  protected override void OnDrawItem(DrawItemEventArgs e){if(e.Index<0)return;bool selected=(e.State&DrawItemState.Selected)!=0;bool active=e.Index==ActiveIndex;Color bg=selected?UI.Green:active?UI.Soft:Color.White;using(var brush=new SolidBrush(bg))e.Graphics.FillRectangle(brush,e.Bounds);string name=Convert.ToString(Items[e.Index]);var box=e.Bounds;box.X+=18;box.Width-=24;TextRenderer.DrawText(e.Graphics,name,Font,box,selected?Color.White:UI.Ink,TextFormatFlags.VerticalCenter|TextFormatFlags.Left|TextFormatFlags.EndEllipsis);if(active){int alpha=Animate?(int)(150+100*Math.Sin(DateTime.UtcNow.TimeOfDay.TotalSeconds*1.5)):220;using(var b=new SolidBrush(Color.FromArgb(alpha,selected?Color.White:UI.Green)))e.Graphics.FillEllipse(b,e.Bounds.X+4,e.Bounds.Y+e.Bounds.Height/2-3,6,6);}}
 }
 public class EncouragementDialog:Form {
  public EncouragementDialog(AppData data){UI.FormStyle(this,"AI 鼓励 · 人格与触发状态",720,650);Padding=new Padding(20);var root=UI.Table(1,38,46,30,120,28,-100,60,50);var auto=new CheckBox{Text="启用自动 AI 鼓励（会调用 API）",Checked=data.AutoEncouragement,AutoSize=true};root.Controls.Add(auto,0,0);var onBreak=new CheckBox{Text="进入休息",Checked=data.EncourageOnBreak,AutoSize=true,Margin=new Padding(8)};var onEnd=new CheckBox{Text="结束计时",Checked=data.EncourageOnTimerEnd,AutoSize=true,Margin=new Padding(8)};var onComplete=new CheckBox{Text="完成任务",Checked=data.EncourageOnTaskComplete,AutoSize=true,Margin=new Padding(8)};root.Controls.Add(UI.Flow(onBreak,onEnd,onComplete),0,1);root.Controls.Add(UI.Label("人格 / 称呼 / 语气 · i-have-adhd 主，adhd-friendly-skill 辅",9),0,2);var persona=UI.TextBox(true);persona.MaxLength=1500;persona.Text=data.EncouragementPersona;root.Controls.Add(persona,0,3);root.Controls.Add(UI.Label("补充提示词（可以修改原来的偏好）",9),0,4);var prompt=UI.TextBox(true);prompt.MaxLength=2000;prompt.Text=data.EncouragementPrompt.Replace("\r\n","\n").Replace("\n","\r\n");root.Controls.Add(prompt,0,5);var note=UI.Label("在触发时生成，显示到当前提醒里；不再等待点击“知道了”。\n发送触发状态、时间、今日汇总、本次专注时长、人格与提示词。不发送完整日志。",9);note.AutoEllipsis=false;root.Controls.Add(note,0,6);root.Controls.Add(UI.Flow(UI.Button("保存",()=>{data.AutoEncouragement=auto.Checked;data.EncourageOnBreak=onBreak.Checked;data.EncourageOnTimerEnd=onEnd.Checked;data.EncourageOnTaskComplete=onComplete.Checked;data.EncouragementPersona=persona.Text.Trim();data.EncouragementPrompt=prompt.Text.Trim().Replace("\r\n","\n");DialogResult=DialogResult.OK;Close();},true),UI.Button("载入新版默认",()=>{persona.Text=AiDefaults.Persona;prompt.Text=AiDefaults.Prompt.Replace("\n","\r\n");})),0,7);Controls.Add(root);}
 }
 public class SupportSettingsDialog:Form {
  public SupportSettingsDialog(AppData data){UI.FormStyle(this,"接续卡 AI · 我的习惯",760,680);Padding=new Padding(20);var root=UI.Table(1,40,128,34,132,32,-100,52);var auto=new CheckBox{Text="打开空白接续卡时自动生成（默认关闭，会调用 API）",Checked=data.AutoResumeSuggestions,AutoSize=true};root.Controls.Add(auto,0,0);var logic=UI.Label("AI 默认会这样拆解\r\n\r\n从你写下的整件事开始，一直拆到真正完成。每一步只保留一个容易启动的动作，并写清可以看到的完成标准。简单任务通常 1–3 步，复杂任务最多 5 步。",9);logic.AutoEllipsis=false;logic.BackColor=UI.Soft;logic.Padding=new Padding(14,10,14,10);root.Controls.Add(logic,0,1);root.Controls.Add(UI.Label("还可以告诉 AI 你更需要什么",10,true),0,2);var habits=UI.TextBox(true);habits.MaxLength=2000;habits.Text=data.SupportHabits;string[] choices={"先给一个 2 分钟内能开始的动作","每一步都明确完成标准","中断后容易重新接上","优先减少切换和准备动作"};var options=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=2,Margin=new Padding(0)};options.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));options.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));for(int i=0;i<choices.Length;i++){string selected=choices[i];var box=new CheckBox{Text=selected,AutoSize=false,Dock=DockStyle.Fill,Margin=new Padding(8,5,8,5),Font=UI.Font(9.5f)};box.CheckedChanged+=(s,e)=>{if(!box.Checked)return;var lines=habits.Text.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).ToList();if(!lines.Contains(selected)){lines.Add(selected);habits.Text=String.Join("\r\n",lines);}};options.Controls.Add(box,i%2,i/2);}root.Controls.Add(options,0,3);root.Controls.Add(UI.Label("我的补充备注（勾选会追加到这里，你仍可修改）",9),0,4);root.Controls.Add(habits,0,5);var save=UI.Button("保存习惯",()=>{data.SupportHabits=habits.Text.Trim();data.AutoResumeSuggestions=auto.Checked;data.AiPreferencesRevision=1;DialogResult=DialogResult.OK;Close();},true);root.Controls.Add(UI.Flow(save,UI.Button("取消",()=>Close())),0,6);Controls.Add(root);Shown+=(s,e)=>{habits.Select(0,0);save.Focus();};}
 }
 public class ProjectDefaultsDialog:Form {
  public ProjectDefaultsDialog(AppData data){UI.FormStyle(this,"项目与程序设置",580,350);Padding=new Padding(20);var root=UI.Table(1,48,58,58,34,58,-100);root.Controls.Add(UI.Label("新建项目与窗口行为",15,true),0,0);var mode=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=190,Font=UI.Font(10),Margin=new Padding(8)};mode.Items.AddRange(new object[]{"番茄钟","极限挑战"});mode.SelectedIndex=data.DefaultProjectChallenge?1:0;root.Controls.Add(UI.Flow(UI.Label("新建项目默认模式",9),mode),0,1);var distraction=new CheckBox{Text="新建项目默认允许分心",Checked=data.DefaultAllowDistraction,AutoSize=true,Margin=new Padding(8)};root.Controls.Add(distraction,0,2);root.Controls.Add(UI.Label("点击主窗口右上角关闭按钮时",9,true),0,3);var closeMode=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=230,Font=UI.Font(10),Margin=new Padding(8)};closeMode.Items.AddRange(new object[]{"收进托盘，继续运行","退出软件"});closeMode.SelectedIndex=data.CloseToTray?0:1;root.Controls.Add(UI.Flow(closeMode),0,4);root.Controls.Add(UI.Flow(UI.Button("保存设置",()=>{data.DefaultProjectChallenge=mode.SelectedIndex==1;data.DefaultAllowDistraction=distraction.Checked;data.CloseToTray=closeMode.SelectedIndex==0;DialogResult=DialogResult.OK;Close();},true),UI.Button("取消",()=>Close())),0,5);Controls.Add(root);}
 }
 public class BuiltInActivitiesDialog:Form {
  public BuiltInActivitiesDialog(IEnumerable<BreakIdea> values){UI.FormStyle(this,"默认内置休息活动",650,500);Padding=new Padding(18);var root=UI.Table(1,48,-100,50);root.Controls.Add(UI.Label("这些活动会在开启“随机使用内置活动”时参与抽取",13,true),0,0);var list=UI.Grid();list.ReadOnly=true;list.Columns.Add("name","活动");list.Columns.Add("detail","怎么做");list.Columns[0].FillWeight=35;list.Columns[1].FillWeight=65;foreach(var x in values)list.Rows.Add(x.Name,x.Detail);root.Controls.Add(list,0,1);root.Controls.Add(UI.Flow(UI.Button("关闭",()=>Close(),true)),0,2);Controls.Add(root);}
 }
 public class ResumeDialog:Form {
  TextBox note,step,done;Label status;Button generate;CancellationTokenSource cancel;int revision;bool applying,busy;readonly Project project;readonly ApiConfig api;readonly AppData data;
  public ResumeDialog(Project p,ApiConfig config=null,AppData appData=null){project=p;api=config;data=appData??new AppData();UI.FormStyle(this,"接续卡 · AI 建议可以修改",650,570);Padding=new Padding(20);var root=UI.Table(1,40,28,72,28,72,28,64,72,50);root.Controls.Add(UI.Label("下一步不必重新想，可以先用建议。",15,true),0,0);note=UI.TextBox(true);note.Name="ResumeNote";note.MaxLength=500;note.Text=p.ResumeNote;step=UI.TextBox(true);step.Name="ResumeStep";step.MaxLength=500;step.Text=String.IsNullOrWhiteSpace(p.SmallStep)?TaskSupport.Next(p):p.SmallStep;done=UI.TextBox(true);done.Name="ResumeDone";done.MaxLength=500;done.Text=p.DoneWhen;root.Controls.Add(UI.Label("接续线索 / 建议（请确认符合实际）",9),0,1);root.Controls.Add(note,0,2);root.Controls.Add(UI.Label("下一步 · 2–5 分钟内能开始的动作",9),0,3);root.Controls.Add(step,0,4);root.Controls.Add(UI.Label("做到什么就可以结束？",9),0,5);root.Controls.Add(done,0,6);status=UI.Label("建议只填入这里，点击保存才写入任务；也可以直接手动修改。\nAI 会收到本任务信息、自述习惯和计时汇总；可能产生 API 费用。",9);status.AutoEllipsis=false;root.Controls.Add(status,0,7);generate=UI.Button("AI 生成建议",async()=>await Generate());root.Controls.Add(UI.Flow(UI.Button("保存接续卡",()=>{p.ResumeNote=note.Text.Trim();p.SmallStep=String.IsNullOrWhiteSpace(p.SmallStep)&&step.Text.Trim()==TaskSupport.Next(p)?"":step.Text.Trim();p.DoneWhen=done.Text.Trim();p.UpdatedUtc=DateTime.UtcNow;DialogResult=DialogResult.OK;Close();},true),generate,UI.Button("暂时不用",()=>Close())),0,8);Controls.Add(root);foreach(var box in new[]{note,step,done})box.TextChanged+=(s,e)=>{if(!applying)revision++;};Shown+=async(s,e)=>{if(config!=null&&!String.IsNullOrWhiteSpace(config.Model)&&data.AutoResumeSuggestions&&String.IsNullOrWhiteSpace(p.ResumeNote)&&String.IsNullOrWhiteSpace(p.SmallStep)&&String.IsNullOrWhiteSpace(p.DoneWhen))await Generate();};FormClosing+=(s,e)=>{if(cancel!=null)cancel.Cancel();};}
  public async Task Generate(){if(busy)return;if(api==null||String.IsNullOrWhiteSpace(api.Model)){status.Text="请先在设置中配置 API。当前建议仍可手动填写和保存。";return;}busy=true;generate.Enabled=false;int startedRevision=revision;cancel=new CancellationTokenSource();status.Text="正在生成建议（最多 60 秒）。你可以继续编辑；不会覆盖等待期间的修改。";try{var draft=new Project{Name=project.Name,NextStep=project.NextStep,SmallStep=step.Text,ResumeNote=note.Text,DoneWhen=done.Text,LastCheckpoint=project.LastCheckpoint,Stages=project.Stages};var values=await Planner.ResumeSuggestions(draft,data,api,cancel.Token);if(IsDisposed)return;if(!TryApplySuggestions(values,startedRevision)){status.Text="检测到你已经修改内容，本次 AI 结果未覆盖它们。需要时可重新生成。";return;}status.Text="AI 建议已填入，尚未保存。可以修改后再点击保存接续卡。";}catch(OperationCanceledException){if(!IsDisposed)status.Text="生成已取消或超时，原内容保留。";}catch(Exception){if(!IsDisposed)status.Text="暂时无法生成，请检查 API 或重试。原内容保留，仍可手动保存。";}finally{busy=false;if(!IsDisposed)generate.Enabled=true;cancel.Dispose();cancel=null;}}
  public bool TryApplySuggestions(string[] values,int expectedRevision){if(revision!=expectedRevision)return false;applying=true;try{note.Text=values[0];step.Text=values[1];done.Text=values[2];}finally{applying=false;}return true;}
 }
 public class StuckDialog:Form {
  public string Result;
  public StuckDialog(Project p){UI.FormStyle(this,"卡住了 · 先缩小一步",610,350);Padding=new Padding(20);var root=UI.Table(1,44,58,50,50,50,-100);root.Controls.Add(UI.Label("不用做完整件事，先重新接上。",15,true),0,0);var label=UI.Label("选择一个起步动作，也可以关闭窗口。\n这不会改变任务状态、休息规则或挑战时长。",9);label.AutoEllipsis=false;root.Controls.Add(label,0,1);string[] options={"只打开与任务有关的文件","写下一句：我现在卡在哪里","留下一个可用的草稿，不做润色"};for(int i=0;i<options.Length;i++){string choice=options[i];root.Controls.Add(UI.Flow(UI.Button(choice,()=>{Result=choice;DialogResult=DialogResult.OK;Close();},i==0)),0,i+2);}root.Controls.Add(UI.Flow(UI.Button("先不选",()=>Close())),0,5);Controls.Add(root);}
 }
 public class ApiDialog:Form {
  public ApiDialog(ApiConfig api,string directory){
   UI.FormStyle(this,"AI 拆解 · 本机 API 配置",680,500);Padding=new Padding(22);MaximizeBox=false;MinimizeBox=false;
   var root=UI.Table(1,35,40,30,40,30,40,38,72,48);var enabled=new CheckBox{Text="使用 API（取消后保留地址、模型和密钥）",Checked=api.Enabled,AutoSize=true};root.Controls.Add(enabled,0,0);
   root.Controls.Add(UI.Label("Chat Completions 兼容接口（完整地址）",10,true),0,1);var endpoint=UI.TextBox();endpoint.Text=api.Endpoint;root.Controls.Add(endpoint,0,2);root.Controls.Add(UI.Label("模型名称 · 按服务商提供的名称填写"),0,3);var model=UI.TextBox();model.Text=api.Model;root.Controls.Add(model,0,4);
   root.Controls.Add(UI.Label("API Key · Windows 当前用户加密保存"),0,5);var key=UI.TextBox();key.UseSystemPasswordChar=true;try{key.Text=api.GetKey();}catch(Exception){key.Text="";}root.Controls.Add(key,0,6);
   var economy=new CheckBox{Text="省时模式：官方 DeepSeek 关闭深度思考（其他服务不添加此参数）",Checked=api.EconomyMode,AutoSize=true};var note=UI.Label("AI 仅手动生成或已开启的鼓励事件调用；取消使用 API 后仍可保存原配置。",9);note.AutoEllipsis=false;var apiNote=UI.Table(1,30,-100);apiNote.Controls.Add(economy,0,0);apiNote.Controls.Add(note,0,1);root.Controls.Add(apiNote,0,7);
   root.Controls.Add(UI.Flow(UI.Button("保存本机配置",()=>{try{if(enabled.Checked)Planner.Endpoint(endpoint.Text);api.Enabled=enabled.Checked;api.Endpoint=endpoint.Text.Trim();api.Model=model.Text.Trim();api.SetKey(key.Text);api.EconomyMode=economy.Checked;api.Save(directory);DialogResult=DialogResult.OK;Close();}catch(Exception){MessageBox.Show(this,"保存失败，请检查接口地址、密钥格式或目录写入权限。","配置未保存");}},true),UI.Button("一键停用 API（保留配置）",()=>{try{api.Enabled=false;api.Save(directory);DialogResult=DialogResult.OK;Close();}catch(Exception){MessageBox.Show(this,"停用状态保存失败，原配置未改动。","配置未保存");}}),UI.Button("取消",()=>Close())),0,8);Controls.Add(root);
  }
 } public class SyncDialog:Form {
  public SyncDialog(SyncConfig config,string dir){
   UI.FormStyle(this,"联网同步 · WebDAV",720,460);Padding=new Padding(22);MaximizeBox=false;MinimizeBox=false;
   var root=UI.Table(1,32,40,30,40,30,40,40,82,48);var url=UI.TextBox();url.Text=config.Url;var user=UI.TextBox();user.Text=config.User;var password=UI.TextBox();password.UseSystemPasswordChar=true;try{password.Text=config.Password();}catch(Exception){}var auto=new CheckBox{Text="自动同步：程序打开且没有计时任务时，每 5 分钟一次",Checked=config.AutoSync,Dock=DockStyle.Fill};
   root.Controls.Add(UI.Label("同步文件完整 URL（HTTPS，所在 WebDAV 目录须已存在）",10,true),0,0);root.Controls.Add(url,0,1);root.Controls.Add(UI.Label("WebDAV 用户名"),0,2);root.Controls.Add(user,0,3);root.Controls.Add(UI.Label("密码 / 应用专用密码 · 本机加密保存"),0,4);root.Controls.Add(password,0,5);root.Controls.Add(auto,0,6);
   var note=UI.Label("例如 https://你的服务/dav/focus-data.xml。所有设备使用同一文件地址。\n同步文件包含任务与计时记录，不含 API 密钥和同步密码；密码仅用于认证。\n传输使用 HTTPS；远端文件未额外加密，请使用自己的可信账号。",9);note.AutoEllipsis=false;root.Controls.Add(note,0,7);
   root.Controls.Add(UI.Flow(UI.Button("保存同步设置",()=>{try{Planner.Endpoint(url.Text);if(user.Text.Contains(":"))throw new InvalidOperationException("用户名不能包含冒号。");config.Url=url.Text.Trim();config.User=user.Text.Trim();config.SetPassword(password.Text);config.AutoSync=auto.Checked;config.Save(dir);DialogResult=DialogResult.OK;Close();}catch(Exception ex){MessageBox.Show(this,ex is InvalidOperationException?ex.Message:"保存失败，请检查数据目录和密码格式。","配置未保存");}},true),UI.Button("取消",()=>Close())),0,8);Controls.Add(root);
  }
 }
 public class MiniSettingsDialog:Form {
  public MiniSettingsDialog(AppData data){UI.FormStyle(this,"mini · 锁定与休息短句",700,620);Padding=new Padding(20);var root=UI.Table(1,34,42,58,42,32,50,-100,54);root.Controls.Add(UI.Label("锁定时次要内容可见度（越低越淡）",11,true),0,0);var dim=new TrackBar{Name="MiniDim",Minimum=0,Maximum=100,TickFrequency=25,Value=Math.Max(0,Math.Min(100,data.MiniDimPercent)),Dock=DockStyle.Fill};root.Controls.Add(dim,0,1);var desc=UI.Label("倒计时、当前子任务 / 休息短句和锁按钮保持清晰。\n这里调整文字与图标的淡化程度；整窗透明度仍可在 mini 右键菜单调整。",9);desc.AutoEllipsis=false;root.Controls.Add(desc,0,2);var ai=new CheckBox{Name="MiniAiRest",Text="与休息鼓励一起生成本轮短句（默认关，不额外逐条请求）",Checked=data.MiniAiRest,AutoSize=true};root.Controls.Add(ai,0,3);root.Controls.Add(UI.Label("短句库每行一条。AI 生成会先填满一轮休息，再按间隔轮换；离线时使用下方默认/自定义库。",9),0,4);var seconds=new NumericUpDown{Name="RestLineSeconds",Minimum=5,Maximum=120,Value=Math.Max(5,Math.Min(120,data.RestLineSeconds)),Width=80};var clearDays=new NumericUpDown{Name="AiRestClearDays",Minimum=0,Maximum=365,Value=Math.Max(0,Math.Min(365,data.AiRestClearDays)),Width=80};root.Controls.Add(UI.Flow(UI.Label("轮换间隔（秒）",9),seconds,UI.Label("AI 生成库自动清理（天，0=不清理）",9),clearDays),0,5);var lines=UI.TextBox(true);lines.Name="MiniRestLines";lines.MaxLength=12000;lines.Text=(data.MiniRestLines??"").Replace("\r\n","\n").Replace("\n","\r\n");root.Controls.Add(lines,0,6);root.Controls.Add(UI.Flow(UI.Button("保存",()=>{var list=lines.Text.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).Distinct().ToList();if(list.Count>200||list.Any(x=>x.Length>60)){MessageBox.Show(this,"最多200条，每条最多60个字符。请缩短后保存。");return;}data.MiniDimPercent=dim.Value;data.MiniAiRest=ai.Checked;data.RestLineSeconds=(int)seconds.Value;data.AiRestClearDays=(int)clearDays.Value;data.MiniRestLines=String.Join("\n",list);DialogResult=DialogResult.OK;Close();},true),UI.Button("取消",()=>Close())),0,7);Controls.Add(root);}
 } public class DistractionSettingsDialog:Form {
  public DistractionSettingsDialog(AppData data){UI.FormStyle(this,"个性化探索设置",700,500);Padding=new Padding(20);var root=UI.Table(1,42,42,42,42,42,42,-100,50);root.Controls.Add(UI.Label("我想看的方向（最多 3 个；每次随机选 1 个）",12,true),0,0);var saved=(data.DistractionTopic??"").Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).Take(3).ToArray();TextBox topic1=UI.TextBox(),topic2=UI.TextBox(),topic3=UI.TextBox();topic1.MaxLength=topic2.MaxLength=topic3.MaxLength=400;if(saved.Length>0)topic1.Text=saved[0];if(saved.Length>1)topic2.Text=saved[1];if(saved.Length>2)topic3.Text=saved[2];root.Controls.Add(UI.Flow(UI.Label("方向 1",9),topic1),0,1);root.Controls.Add(UI.Flow(UI.Label("方向 2",9),topic2),0,2);root.Controls.Add(UI.Flow(UI.Label("方向 3",9),topic3),0,3);var row=UI.Flow(UI.Label("最多字数",9),new NumericUpDown{Minimum=100,Maximum=2000,Value=Math.Max(100,Math.Min(2000,data.DistractionMaxChars)),Width=90,Name="MaxChars"},UI.Label("同一条冷却分钟",9),new NumericUpDown{Minimum=1,Maximum=120,Value=Math.Max(1,Math.Min(120,data.DistractionCooldownMinutes)),Width=90,Name="Cooldown"});root.Controls.Add(row,0,4);root.Controls.Add(UI.Label("默认 300 字。没有填写方向时，会根据项目名生成，并在结果中说明。",9),0,5);var useProject=new CheckBox{Text="个性化与项目名关联",Checked=data.DistractionUseProjectName,AutoSize=true,Margin=new Padding(4,8,4,4)};root.Controls.Add(useProject,0,6);var save=UI.Button("保存探索方向",()=>{var directions=new[]{topic1.Text,topic2.Text,topic3.Text}.Select(x=>(x??"").Trim()).Where(x=>x.Length>0).Distinct().ToList();var max=(NumericUpDown)row.Controls.OfType<NumericUpDown>().First(x=>x.Name=="MaxChars");var cool=(NumericUpDown)row.Controls.OfType<NumericUpDown>().First(x=>x.Name=="Cooldown");data.DistractionTopic=String.Join("\n",directions);data.DistractionUseProjectName=useProject.Checked;data.DistractionMaxChars=(int)max.Value;data.DistractionCooldownMinutes=(int)cool.Value;data.LastFresh=null;data.LastFreshProjectId="";DialogResult=DialogResult.OK;Close();},true);root.Controls.Add(UI.Flow(save,UI.Button("取消",()=>Close())),0,7);Controls.Add(root);Shown+=(s,e)=>{topic1.Select(0,0);save.Focus();};}
 }
 public class SelfReviewDialog:Form {
  readonly AppData data;readonly List<ChallengeAdjustment> items;readonly TextBox analysis;readonly Panel cloud;readonly Action persist;
  public SelfReviewDialog(AppData value,ApiConfig api,Action save=null){data=value;persist=save;items=data.ChallengeAdjustments.Where(x=>x!=null).OrderByDescending(x=>x.AtUtc).ToList();UI.FormStyle(this,"审视自我",900,760);Padding=new Padding(18);var root=UI.Table(1,46,120,30,92,34,-100,52);root.Controls.Add(UI.Label("从记录里找节奏和任务设计规律，不评价人格。",12,true),0,0);cloud=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,BorderStyle=BorderStyle.FixedSingle};cloud.Paint+=PaintCloud;root.Controls.Add(cloud,0,1);root.Controls.Add(UI.Label("AI 寻找逻辑 · 可以按你的需要修改",9,true),0,2);var prompt=UI.TextBox(true);prompt.Name="SelfReviewPrompt";prompt.MaxLength=2000;prompt.Text=data.SelfReviewPrompt;root.Controls.Add(prompt,0,3);root.Controls.Add(UI.Label("AI 给出的可复用规律 · 新分析会覆盖旧结果并保存在本机",9,true),0,4);analysis=UI.TextBox(true);analysis.ReadOnly=true;analysis.TabStop=false;analysis.Font=UI.Font(10);analysis.Text=String.IsNullOrWhiteSpace(data.SelfReviewAnalysis)?"还没有保存的分析。点击下方按钮后，结果会显示在这里。":Planner.FormatAnalysis(data.SelfReviewAnalysis);root.Controls.Add(analysis,0,5);var analyze=UI.Button("AI 看看规律",async()=>{try{data.SelfReviewPrompt=prompt.Text.Trim();analysis.Text="正在整理规律…";string result=await Task.Run(()=>Planner.AnalyzeAdjustments(api,BuildContext(),CancellationToken.None,data.SelfReviewPrompt));result=Planner.FormatAnalysis(result);data.SelfReviewAnalysis=result;data.SelfReviewAnalysisUtc=DateTime.UtcNow;analysis.Text=result;if(persist!=null)persist();}catch(Exception ex){analysis.Text="分析暂时不可用："+ex.Message;}},true);root.Controls.Add(UI.Flow(analyze,UI.Button("保存寻找逻辑",()=>{data.SelfReviewPrompt=prompt.Text.Trim();if(persist!=null)persist();}),UI.Button("查看原始记录",()=>{using(var d=new AdjustmentRecordsDialog(items))d.ShowDialog(this);}),UI.Button("清空记录",()=>{if(MessageBox.Show(this,"清空全部加时、提前完成理由和已保存分析？此操作无法撤销。","清空审视记录",MessageBoxButtons.OKCancel,MessageBoxIcon.Warning)!=DialogResult.OK)return;data.ChallengeAdjustments.Clear();items.Clear();data.SelfReviewAnalysis="";data.SelfReviewAnalysisUtc=DateTime.MinValue;analysis.Text="记录与分析已清空。";cloud.Invalidate();if(persist!=null)persist();}),UI.Button("关闭",()=>Close())),0,6);Controls.Add(root);Shown+=(s,e)=>{prompt.Select(0,0);analysis.Select(0,0);analyze.Focus();};}
  static string KindText(string kind){return kind=="early"?"提前完成":kind=="overtime-early"?"加时内完成":"申请加时";}
  string BuildContext(){return String.Join("\n",items.Take(40).Select(x=>x.AtUtc.ToString("yyyy-MM-dd")+" | "+KindText(x.Kind)+" | 项目:"+x.ProjectName+" | 子任务:"+x.StageName+" | 时间变化秒:"+x.DeltaSeconds+" | 理由:"+x.Reason));}
  void PaintCloud(object sender,PaintEventArgs e){var words=items.Where(x=>!String.IsNullOrWhiteSpace(x.Reason)).SelectMany(x=>x.Reason.Split(new[]{' ','，','。','、','；','\r','\n','/','·'},StringSplitOptions.RemoveEmptyEntries)).Where(x=>x.Length>=2).GroupBy(x=>x).OrderByDescending(g=>g.Count()).Take(24).ToList();if(words.Count==0){e.Graphics.DrawString("还没有可汇总的理由",UI.Font(12),Brushes.Gray,20,20);return;}int max=words.Max(x=>x.Count()),i=0;foreach(var w in words){float size=10+18*(float)w.Count()/Math.Max(1,max);int x=15+(i*97)%(Math.Max(120,cloud.Width-130)),y=15+((i*53)%(Math.Max(60,cloud.Height-45)));using(var f=UI.Font(size,i%3==0))using(var brush=new SolidBrush(i%2==0?UI.Green:UI.Purple))e.Graphics.DrawString(w.Key,f,brush,x,y);i++;}}
 }
 public class AdjustmentRecordsDialog:Form {
  public AdjustmentRecordsDialog(IEnumerable<ChallengeAdjustment> values){UI.FormStyle(this,"审视自我 · 原始记录",760,520);Padding=new Padding(18);var root=UI.Table(1,42,-100,48);root.Controls.Add(UI.Label("加时与提前完成记录",14,true),0,0);var list=UI.TextBox(true);list.ReadOnly=true;list.TabStop=false;list.Font=UI.Font(9.5f);list.Text=String.Join("\r\n",values.Select(x=>x.AtUtc.ToLocalTime().ToString("MM-dd HH:mm")+" · "+(x.Kind=="early"?"提前完成":x.Kind=="overtime-early"?"加时内完成":"申请加时")+" · "+x.ProjectName+(String.IsNullOrWhiteSpace(x.StageName)?"":" / "+x.StageName)+(String.IsNullOrWhiteSpace(x.Reason)?"":" · "+x.Reason)));root.Controls.Add(list,0,1);root.Controls.Add(UI.Flow(UI.Button("关闭",()=>Close())),0,2);Controls.Add(root);}
 }
 public static class AppHost { public static ApiConfig Api; }
 public class DataManagementDialog:Form {
  public DataManagementDialog(Action export,Action import,Action folder,Action favorites,Action distraction,Action clearAll){UI.FormStyle(this,"数据与记录",620,340);Padding=new Padding(20);var root=UI.Table(1,54,58,42,54,-100);root.Controls.Add(UI.Label("备份、恢复和本地数据",14,true),0,0);root.Controls.Add(UI.Flow(UI.Button("导出全部数据",export),UI.Button("导入并合并",import),UI.Button("打开数据文件夹",folder)),0,1);root.Controls.Add(UI.Label("导入前会自动备份；导出的记录不含 API 密钥。",9),0,2);var danger=UI.Button("清空全部数据",clearAll);danger.ForeColor=Color.FromArgb(150,45,45);danger.FlatAppearance.BorderColor=Color.FromArgb(190,95,95);root.Controls.Add(UI.Flow(danger),0,3);var warning=UI.Label("清空会移除项目、计时记录、自定义活动、收藏和 AI 本地分析。API 与同步连接配置保留。执行前会在数据文件夹留一份自动备份。",9);warning.AutoEllipsis=false;warning.ForeColor=UI.Muted;root.Controls.Add(warning,0,4);Controls.Add(root);}
 }
 public class AiSettingsHubDialog:Form {
  public AiSettingsHubDialog(AppData data,ApiConfig api,string dir,Action encourage,Action persist=null){UI.FormStyle(this,"AI 与 API 设置",560,300);Padding=new Padding(20);var root=UI.Table(1,52,52,38,52,-100);root.Controls.Add(UI.Label("把常用 AI 配置收在一个次级面板。",11,true),0,0);root.Controls.Add(UI.Flow(UI.Button("配置 API",()=>{using(var d=new ApiDialog(api,dir))d.ShowDialog(this);}),UI.Button("测试 API",encourage)),0,1);root.Controls.Add(UI.Label("AI 个性化",10,true),0,2);root.Controls.Add(UI.Flow(UI.Button("接续卡 AI",()=>{using(var d=new SupportSettingsDialog(data)){if(d.ShowDialog(this)==DialogResult.OK&&persist!=null)persist();}}),UI.Button("AI 鼓励",()=>{using(var d=new EncouragementDialog(data)){if(d.ShowDialog(this)==DialogResult.OK&&persist!=null)persist();}})),0,3);Controls.Add(root);}
 } public class ChallengeNoteDialog:Form {
  public string Reason="";public int Minutes;public bool Accepted;
  public ChallengeNoteDialog(string title,string message,bool overtime,int suggestedMinutes,int maxMinutes=120){UI.FormStyle(this,title,700,overtime?470:390);Padding=new Padding(20);var root=UI.Table(1,55,80,34,46,overtime?62:0,50,-100,56);root.Controls.Add(UI.Label(title,16,true),0,0);var info=UI.Label(message,10);info.AutoEllipsis=false;root.Controls.Add(info,0,1);root.Controls.Add(UI.Label(overtime?"申请理由（默认理由不会保存原文）":"提早完成原因（可留空）",9),0,2);var reason=UI.TextBox();reason.Name="ChallengeReason";reason.Text=overtime?"我做不完了":"";root.Controls.Add(reason,0,3);NumericUpDown mins=null;TrackBar slider=null;if(overtime){int upper=Math.Max(1,Math.Min(maxMinutes,120));int initial=Math.Max(1,Math.Min(upper,suggestedMinutes));slider=new TrackBar{Minimum=1,Maximum=upper,Value=initial,TickFrequency=Math.Max(1,upper/4),Dock=DockStyle.Fill};mins=new NumericUpDown{Minimum=1,Maximum=upper,Value=initial,Width=90,Margin=new Padding(4,8,4,4)};slider.ValueChanged+=(s,e)=>{if(mins.Value!=slider.Value)mins.Value=slider.Value;};mins.ValueChanged+=(s,e)=>{if(slider.Value!=(int)mins.Value)slider.Value=(int)mins.Value;};root.Controls.Add(UI.Flow(UI.Label("增加分钟",9),mins),0,4);root.Controls.Add(slider,0,5);}root.Controls.Add(UI.Flow(UI.Button(overtime?"申请并继续":"记录并继续",()=>{Reason=reason.Text.Trim();Minutes=mins==null?0:(int)mins.Value;Accepted=true;DialogResult=DialogResult.OK;Close();},true),UI.Button("保持暂停",()=>Close())),0,overtime?6:5);Controls.Add(root);Shown+=(s,e)=>{reason.Focus();reason.Select(reason.TextLength,0);};}
 }
 public class FreshContentDialog:Form {
  readonly FreshContent content; readonly Label source; readonly string projectId; readonly Action<FreshContent> saveFavorite;
  public FreshContentDialog(FreshContent value,string project,Action<FreshContent> favorite){content=value;projectId=project;saveFavorite=favorite;UI.FormStyle(this,"个性化探索 · 计时保持暂停",720,560);Padding=new Padding(20);var root=UI.Table(1,48,34,-100,42,52);root.Controls.Add(UI.Label(value.Title,15,true),0,0);var meta=UI.Label("中文内容 · 本次输出 "+value.Body.Length+" 字",9);meta.ForeColor=UI.Muted;root.Controls.Add(meta,0,1);var body=UI.TextBox(true);body.ReadOnly=true;body.TabStop=false;body.Text=Paragraphs(value.Body);body.Font=UI.Font(11);root.Controls.Add(body,0,2);source=UI.Label(String.IsNullOrWhiteSpace(value.SourceUrl)?"来源：未提供（模型未核验网址）":"来源："+value.SourceUrl,8.5f);source.AutoEllipsis=false;root.Controls.Add(source,0,3);var close=UI.Button("知道了",()=>Close());var buttons=UI.Flow(UI.Button(value.Favorite?"已收藏":"收藏宝藏",()=>{value.Favorite=true;saveFavorite(value);},true),close);root.Controls.Add(buttons,0,4);Controls.Add(root);Shown+=(s,e)=>{body.SelectionLength=0;close.Focus();};}
  static string Paragraphs(string text){text=(text??"").Replace("\r\n","\n").Trim();if(text.Contains("\n\n"))return text.Replace("\n","\r\n");var sentences=text.Split(new[]{'。','！','？'},StringSplitOptions.RemoveEmptyEntries);if(sentences.Length<3)return text;var rows=new List<string>();for(int i=0;i<sentences.Length;i+=2){string row=String.Join("。",sentences.Skip(i).Take(2)).Trim();if(row.Length>0)rows.Add(row+"。");}return String.Join("\r\n\r\n",rows);}
 }
 public class FavoritesDialog:Form {
  public FavoritesDialog(IEnumerable<FreshContent> values,Action clear=null){UI.FormStyle(this,"收藏的宝藏",700,500);Padding=new Padding(18);var list=new ListBox{Dock=DockStyle.Fill,Font=UI.Font(11)};var items=values.Where(x=>x!=null&&x.Favorite).OrderByDescending(x=>x.SavedUtc).ToList();foreach(var x in items)list.Items.Add(String.IsNullOrWhiteSpace(x.Title)?"未命名":x.Title);var detail=UI.TextBox(true);detail.ReadOnly=true;detail.TabStop=false;detail.Font=UI.Font(10);list.SelectedIndexChanged+=(s,e)=>{if(list.SelectedIndex<0){detail.Text="";return;}var x=items[list.SelectedIndex];detail.Text=x.Body+"\r\n\r\n"+(String.IsNullOrWhiteSpace(x.SourceUrl)?"来源未提供":x.SourceUrl);detail.SelectionLength=0;};var root=UI.Table(2,-100,110,44);root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,42));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,58));root.Controls.Add(list,0,0);root.SetColumnSpan(list,2);root.Controls.Add(detail,0,1);root.SetColumnSpan(detail,2);var close=UI.Button("关闭",()=>Close());root.Controls.Add(UI.Flow(UI.Button("清空宝藏",()=>{if(MessageBox.Show(this,"清空全部收藏？此操作无法撤销。","清空宝藏",MessageBoxButtons.OKCancel,MessageBoxIcon.Warning)!=DialogResult.OK)return;if(clear!=null)clear();items.Clear();list.Items.Clear();detail.Clear();}),close),0,2);root.SetColumnSpan(root.GetControlFromPosition(0,2),2);Controls.Add(root);Shown+=(s,e)=>close.Focus();}
 }
 public class ProjectDetailsDialog:Form {
   readonly AppData data; readonly ComboBox project; readonly TextBox search; readonly Label total; readonly DataGridView grid; readonly List<Project> allProjects; bool updatingChoices; string initialSelectedId;
  public ProjectDetailsDialog(AppData value,string selectedId){
    data=value;initialSelectedId=selectedId;allProjects=data.Projects.Where(x=>!x.Deleted).OrderBy(x=>x.Name).ToList();UI.FormStyle(this,"项目明细",860,620);Padding=new Padding(18);
    var root=UI.Table(1,46,46,34,-100,48);root.Controls.Add(UI.Label("查询项目明细",16,true),0,0);
    search=UI.TextBox();search.Width=220;search.Margin=new Padding(4,6,8,6);search.AccessibleName="按名称搜索项目";project=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=320,Font=UI.Font(10),Margin=new Padding(4,6,8,6)};
    total=UI.Label("",10,true);total.ForeColor=UI.Green;root.Controls.Add(UI.Flow(UI.Label("输入关键词",10),search,UI.Label("匹配项目",10),project),0,1);root.Controls.Add(total,0,2);
    grid=UI.Grid();grid.ReadOnly=true;grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;grid.ScrollBars=ScrollBars.Both;grid.Columns.Add("day","日期");grid.Columns.Add("mode","模式");grid.Columns.Add("start","开始");grid.Columns.Add("end","结束");grid.Columns.Add("duration","时长");grid.Columns.Add("outcome","状态");grid.Columns.Add("stage","子任务");grid.Columns.Add("stageNote","子任务备注");for(int i=0;i<6;i++){grid.Columns[i].AutoSizeMode=DataGridViewAutoSizeColumnMode.AllCells;grid.Columns[i].MinimumWidth=70;}grid.Columns[5].MinimumWidth=130;grid.Columns[6].MinimumWidth=150;grid.Columns[6].FillWeight=32;grid.Columns[7].MinimumWidth=220;grid.Columns[7].FillWeight=68;root.Controls.Add(grid,0,3);
    root.Controls.Add(UI.Flow(UI.Button("关闭",()=>Close())),0,4);search.TextChanged+=(s,e)=>RefreshProjectChoices();project.SelectedIndexChanged+=(s,e)=>{if(!updatingChoices)RefreshRows();};Controls.Add(root);Shown+=(s,e)=>{RefreshProjectChoices();RefreshRows();search.Focus();};
   }
   void RefreshProjectChoices(){string keep=project.SelectedItem is Project?((Project)project.SelectedItem).Id:initialSelectedId;string key=(search.Text??"").Trim();var matches=allProjects.Where(p=>key.Length==0||(p.Name??"").IndexOf(key,StringComparison.OrdinalIgnoreCase)>=0||(p.NextStep??"").IndexOf(key,StringComparison.OrdinalIgnoreCase)>=0).ToList();updatingChoices=true;project.Items.Clear();foreach(var p in matches)project.Items.Add(p);int selected=matches.FindIndex(p=>p.Id==keep);if(selected<0&&matches.Count>0)selected=0;project.SelectedIndex=selected;updatingChoices=false;RefreshRows();}
   void RefreshRows(){grid.Rows.Clear();if(project.SelectedIndex<0){total.Text="没有匹配的项目。";return;}var p=(Project)project.SelectedItem;var rows=data.Records.Where(r=>r.ProjectId==p.Id||String.IsNullOrEmpty(r.ProjectId)&&r.ProjectName==p.Name).OrderByDescending(r=>r.StartUtc).ToList();total.Text="累计专注 "+FocusEngine.Duration(rows.Sum(r=>r.Seconds))+"   ·   "+rows.Count+" 条记录   ·   "+(p.Challenge?"极限挑战":"番茄钟");foreach(var r in rows)grid.Rows.Add(r.Day,r.Challenge?"极限挑战":"番茄钟",r.StartUtc.ToLocalTime().ToString("HH:mm:ss"),r.EndUtc.ToLocalTime().ToString("HH:mm:ss"),FocusEngine.Duration(r.Seconds),r.Outcome,String.IsNullOrEmpty(r.StageName)?"—":r.StageName,String.IsNullOrEmpty(r.StageNote)?"—":r.StageNote);}
 }

 public class ProjectDialog:Form {
  public Project Result;
  readonly ApiConfig api;readonly string directory;readonly AppData appData;CheckBox readHistory;
  TextBox name,description;ComboBox mode;NumericUpDown minutes;
  DataGridView grid;Label status;Button generate,save,removeStage;int dragRow=-1;Point dragPoint;DateTime dragStarted;FlowLayoutPanel bottom,planTools;
  CancellationTokenSource cancel;bool busy,updatingDurations;string source;
  readonly Project original;
    public ProjectDialog(Project project,ApiConfig config,string dataDirectory,AppData data=null){
     original=project;api=config;directory=dataDirectory;appData=data;if(String.IsNullOrWhiteSpace(project.Name)&&data!=null){project.AllowDistraction=data.DefaultAllowDistraction;project.Challenge=data.DefaultProjectChallenge;project.ChallengeMinutes=Math.Max(1,data.FocusMinutes);project.ChallengeMinutesCustomized=false;project.PomodoroMinutes=0;}source=project.PlanSource;
   UI.FormStyle(this,project.Name==""?"新建任务":"编辑任务",900,710);Padding=new Padding(20);
   var root=UI.Table(1,42,38,28,76,46,-100,48,54);
   root.Controls.Add(UI.Label("只需要写下，你想做什么。",16,true),0,0);name=UI.TextBox();name.MaxLength=100;name.Text=project.Name;root.Controls.Add(name,0,1);
   root.Controls.Add(UI.Label("任务描述 / 目标成果（AI 将根据这里拆解）",9),0,2);description=UI.TextBox(true);description.MaxLength=4000;description.Text=project.NextStep;root.Controls.Add(description,0,3);
   mode=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=145,Font=UI.Font(10),Margin=new Padding(4,8,8,4)};mode.Items.AddRange(new object[]{"番茄钟","极限挑战"});mode.SelectedIndex=project.Challenge?1:0;
   minutes=new NumericUpDown{Minimum=1,Maximum=720,Value=project.ChallengeMinutes,Width=70,Margin=new Padding(4,8,4,4)};
   var modeLabel=UI.Label("计时方式",9);modeLabel.Dock=DockStyle.None;modeLabel.Size=new Size(70,34);var minLabel=UI.Label("时长分钟",9);minLabel.Dock=DockStyle.None;minLabel.Size=new Size(95,34);
   generate=UI.Button("AI拆解",async()=>await Generate());readHistory=new CheckBox{Text="读取加时 / 提前历史",AutoSize=true,Checked=false,Margin=new Padding(8,11,8,4)};removeStage=UI.Button("-子任务",()=>RemoveStage());removeStage.Enabled=false;planTools=UI.Flow(generate,readHistory,UI.Button("写稿模板",()=>{LoadStages(Planner.Writing());source="写稿模板";status.Text="模板已载入，无 API 请求。";}),UI.Button("+子任务",()=>AddStage()),removeStage);root.Controls.Add(planTools,0,4);
   grid=UI.Grid();grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.AllCells;grid.ScrollBars=ScrollBars.Both;grid.EditMode=DataGridViewEditMode.EditOnKeystrokeOrF2;grid.AllowUserToDeleteRows=false;grid.Columns.Add(new DataGridViewCheckBoxColumn{Name="done",HeaderText="完成",FillWeight=12});grid.Columns.Add("remaining","剩余 %");grid.Columns[1].FillWeight=18;grid.Columns.Add(new DataGridViewTextBoxColumn{Name="duration",HeaderText="时长（可编辑）",ReadOnly=false,MinimumWidth=120});grid.Columns.Add("title","子任务（按执行顺序）");grid.Columns[3].FillWeight=45;grid.Columns.Add("action","下一步动作");grid.Columns[4].MinimumWidth=380;grid.DataError+=(s,e)=>{e.ThrowException=false;};LoadStages(project.Stages);root.Controls.Add(grid,0,5);
   foreach(DataGridViewColumn column in grid.Columns)column.SortMode=DataGridViewColumnSortMode.NotSortable;
   grid.SelectionChanged+=(s,e)=>removeStage.Enabled=grid.SelectedRows.Count>0;grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)grid.BeginEdit(true);};
   grid.AllowDrop=true;grid.MouseDown+=(s,e)=>{var hit=grid.HitTest(e.X,e.Y);dragRow=e.Button==MouseButtons.Left?hit.RowIndex:-1;dragPoint=e.Location;dragStarted=DateTime.UtcNow;if(hit.RowIndex<0){grid.CurrentCell=null;grid.ClearSelection();}};
   grid.MouseMove+=(s,e)=>{if(dragRow>=0&&e.Button==MouseButtons.Left&&(DateTime.UtcNow-dragStarted).TotalMilliseconds>=350&&(Math.Abs(e.X-dragPoint.X)+Math.Abs(e.Y-dragPoint.Y)>5)){grid.EndEdit();int row=dragRow;dragRow=-1;grid.DoDragDrop(new StageDrag{Owner=this,Index=row},DragDropEffects.Move);}};
   grid.MouseUp+=(s,e)=>dragRow=-1;grid.DragOver+=(s,e)=>{var move=e.Data.GetData(typeof(StageDrag)) as StageDrag;e.Effect=move!=null&&move.Owner==this?DragDropEffects.Move:DragDropEffects.None;var pt=grid.PointToClient(new Point(e.X,e.Y));if(grid.Rows.Count>0&&pt.Y<30&&grid.FirstDisplayedScrollingRowIndex>0)grid.FirstDisplayedScrollingRowIndex--;else if(pt.Y>grid.Height-25&&grid.FirstDisplayedScrollingRowIndex<grid.Rows.Count-1)grid.FirstDisplayedScrollingRowIndex++;};
   grid.DragDrop+=(s,e)=>{var move=e.Data.GetData(typeof(StageDrag)) as StageDrag;if(move==null||move.Owner!=this)return;var pt=grid.PointToClient(new Point(e.X,e.Y));int target=grid.HitTest(pt.X,pt.Y).RowIndex;if(target<0)target=grid.Rows.Count-1;MoveStageTo(move.Index,target);};
   Shown+=(s,e)=>{grid.CurrentCell=null;grid.ClearSelection();removeStage.Enabled=false;name.Focus();name.Select(0,0);};
   var context=new ContextMenuStrip();context.Items.Add("上移子任务",null,(s,e)=>MoveStage(-1));context.Items.Add("下移子任务",null,(s,e)=>MoveStage(1));grid.ContextMenuStrip=context;
   status=UI.Label("保存仅写入本地，不调用 API。只有点击“AI 拆解”才请求模型；已有步骤会保留。",9);status.AutoEllipsis=false;status.ForeColor=UI.Muted;root.Controls.Add(status,0,6);
   save=UI.Button("保存任务",()=>SaveTask(),true);bottom=UI.Flow(save,UI.Button("取消",()=>Close()));root.Controls.Add(bottom,0,7);Controls.Add(root);
   mode.SelectedIndexChanged+=(s,e)=>{if(mode.SelectedIndex==1&&!original.ChallengeMinutesCustomized)minutes.Value=Math.Max(minutes.Minimum,Math.Min(minutes.Maximum,original.PomodoroMinutes>0?original.PomodoroMinutes:(appData==null?25:appData.FocusMinutes)));minutes.Enabled=mode.SelectedIndex==1;minLabel.Text=mode.SelectedIndex==1?"挑战总分钟":"番茄钟分钟";UpdateDurations();};minutes.ValueChanged+=(s,e)=>UpdateDurations();grid.CellValueChanged+=(s,e)=>{if(updatingDurations)return;if(e.ColumnIndex==1)UpdateDurations();else if(e.ColumnIndex==2)ApplyDuration(e.RowIndex);};minutes.Enabled=mode.SelectedIndex==1;minLabel.Text=mode.SelectedIndex==1?"挑战总分钟":"番茄钟分钟";
   FormClosing+=(s,e)=>{if(cancel!=null)cancel.Cancel();};
  }
  void LoadStages(List<Stage> stages){grid.Rows.Clear();foreach(var s in stages){int row=grid.Rows.Add(s.Done,s.Remaining,"",s.Title,s.Action);grid.Rows[row].Tag=s.Id;if(s.AllocatedSeconds>0)grid.Rows[row].Cells[2].Tag=s.AllocatedSeconds;}UpdateDurations();grid.CurrentCell=null;grid.ClearSelection();if(removeStage!=null)removeStage.Enabled=false;}
  int PlanMinutes(){if(mode.SelectedIndex==1)return (int)minutes.Value;if(original.PomodoroMinutes>0)return original.PomodoroMinutes;return appData==null?25:Math.Max(1,appData.FocusMinutes);}
  void UpdateDurations(){if(grid==null||grid.Columns["duration"]==null)return;updatingDurations=true;try{int total=PlanMinutes();for(int i=0;i<grid.Rows.Count;i++){int current,next=0;if(!Int32.TryParse(Convert.ToString(grid.Rows[i].Cells[1].Value),out current))continue;if(i+1<grid.Rows.Count)Int32.TryParse(Convert.ToString(grid.Rows[i+1].Cells[1].Value),out next);int seconds=grid.Rows[i].Cells[2].Tag is int?(int)grid.Rows[i].Cells[2].Tag:Math.Max(0,(int)Math.Round(total*60*Math.Max(0,current-next)/100.0));grid.Rows[i].Cells[2].Value=FocusEngine.Duration(seconds);}}finally{updatingDurations=false;}}
  void ApplyDuration(int row){if(row<0||row>=grid.Rows.Count)return;TimeSpan span;if(!TimeSpan.TryParse(Convert.ToString(grid.Rows[row].Cells[2].Value),out span)||span.TotalSeconds<0){UpdateDurations();return;}int total=Math.Max(60,PlanMinutes()*60),seconds=Math.Max(1,(int)Math.Round(span.TotalSeconds)),share=Math.Max(1,(int)Math.Round(seconds*100.0/total));int current=100;if(!Int32.TryParse(Convert.ToString(grid.Rows[row].Cells[1].Value),out current))current=100;updatingDurations=true;try{grid.Rows[row].Cells[2].Tag=seconds;if(row+1<grid.Rows.Count){int after=0;if(row+2<grid.Rows.Count)Int32.TryParse(Convert.ToString(grid.Rows[row+2].Cells[1].Value),out after);grid.Rows[row+1].Cells[1].Value=Math.Max(after,Math.Min(current,current-share));grid.Rows[row+1].Cells[2].Tag=null;}else{int upper=row==0?100:Convert.ToInt32(grid.Rows[row-1].Cells[1].Value);grid.Rows[row].Cells[1].Value=Math.Max(0,Math.Min(upper,share));}}finally{updatingDurations=false;}UpdateDurations();}
  class StageDrag{public ProjectDialog Owner;public int Index;}
  void RenumberStages(){for(int i=0;i<grid.Rows.Count;i++)grid.Rows[i].Cells[1].Value=100-(int)Math.Floor(90.0*i/Math.Max(1,grid.Rows.Count-1));UpdateDurations();}
  void AddStage(){if(grid.Rows.Count>=20){status.Text="最多20个子任务。";return;}grid.EndEdit();int index=grid.SelectedRows.Count==0?grid.Rows.Count:grid.SelectedRows[0].Index+1;grid.Rows.Insert(index,false,100,"","新子任务","");grid.Rows[index].Tag=Guid.NewGuid().ToString("N");RenumberStages();grid.CurrentCell=null;grid.ClearSelection();}
  void RemoveStage(){if(grid.SelectedRows.Count==0)return;grid.EndEdit();grid.Rows.RemoveAt(grid.SelectedRows[0].Index);RenumberStages();grid.CurrentCell=null;grid.ClearSelection();}
  void MoveStage(int direction){if(grid.SelectedRows.Count==0)return;int index=grid.SelectedRows[0].Index;MoveStageTo(index,index+direction);}
  void MoveStageTo(int index,int target){if(index<0||target<0||index>=grid.Rows.Count||target>=grid.Rows.Count||target==index)return;grid.EndEdit();var row=grid.Rows[index];grid.Rows.RemoveAt(index);grid.Rows.Insert(target,row);RenumberStages();grid.CurrentCell=grid.Rows[target].Cells[3];grid.Rows[target].Selected=true;}
  Project Draft(){return new Project{Id=original.Id,Name=name.Text.Trim(),NextStep=description.Text.Trim(),SmallStep=original.SmallStep,ResumeNote=original.ResumeNote,DoneWhen=original.DoneWhen,LastCheckpoint=original.LastCheckpoint,LastWorkedUtc=original.LastWorkedUtc,Enabled=original.Enabled,Completed=original.Completed,Deleted=original.Deleted,Challenge=mode.SelectedIndex==1,ChallengeMinutes=(int)minutes.Value,ChallengeMinutesCustomized=original.ChallengeMinutesCustomized||(mode.SelectedIndex==1&&(int)minutes.Value!=(original.PomodoroMinutes>0?original.PomodoroMinutes:(appData==null?25:appData.FocusMinutes))),PomodoroMinutes=original.PomodoroMinutes,AllowDistraction=original.AllowDistraction,AiEnabled=false,PlanSource=source};}
  List<Stage> ReadStages(){grid.EndEdit();var list=new List<Stage>();foreach(DataGridViewRow row in grid.Rows){if(row.IsNewRow)continue;int n;if(!Int32.TryParse(Convert.ToString(row.Cells[1].Value),out n))throw new InvalidOperationException("剩余百分比请填写整数。");if(row.Tag==null)row.Tag=Guid.NewGuid().ToString("N");list.Add(new Stage{Id=(string)row.Tag,Done=Convert.ToBoolean(row.Cells[0].Value??false),Remaining=n,AllocatedSeconds=row.Cells[2].Tag is int?(int)row.Cells[2].Tag:0,Title=Convert.ToString(row.Cells[3].Value).Trim(),Action=Convert.ToString(row.Cells[4].Value).Trim()});}return list;}
  async Task<bool> Generate(){
   if(busy)return false;if(String.IsNullOrWhiteSpace(name.Text)){status.Text="先填写任务名称。";return false;}
   if(String.IsNullOrWhiteSpace(api.Model)){status.Text="请先配置 API 的地址、模型和密钥；也可以先保存，稍后拆解。";return false;}
   busy=true;planTools.Enabled=false;generate.Enabled=false;bottom.Enabled=false;name.Enabled=false;description.Enabled=false;mode.Enabled=false;minutes.Enabled=false;grid.Enabled=false;cancel=new CancellationTokenSource();
   status.Text="正在请求 AI（最多等待 60 秒）。你可以关闭窗口取消。";
   try{var stages=await Planner.Generate(Draft(),api,cancel.Token,appData,readHistory.Checked);if(IsDisposed)return false;LoadStages(stages);source="AI 拆解";status.Text="方案已就绪（相同输入复用本次运行缓存）。检查后保存。";return true;}
   catch(OperationCanceledException){if(!IsDisposed)status.Text="请求已取消或超时；已填写内容保留，可以重试或先保存。";return false;}
   catch(Exception ex){if(!IsDisposed)status.Text=ex is System.Security.Cryptography.CryptographicException?"当前 Windows 用户无法解密密钥，请重新配置。":ex is System.Net.Http.HttpRequestException?"无法连接 API，请检查网络和接口地址。任务内容已保留。":ex.Message;return false;}
   finally{busy=false;if(!IsDisposed){planTools.Enabled=true;generate.Enabled=true;bottom.Enabled=true;name.Enabled=true;description.Enabled=true;mode.Enabled=true;minutes.Enabled=mode.SelectedIndex==1;grid.Enabled=true;}cancel.Dispose();cancel=null;}
  }
  void SaveTask(){
   if(busy)return;if(String.IsNullOrWhiteSpace(name.Text)){status.Text="请填写任务名称。";return;}

   try{var result=Draft();result.Stages=ReadStages();if(result.Stages.Count>0){string error=Planner.Validate(result.Stages);if(error!=null)throw new InvalidOperationException(error);}else if(result.Challenge){result.Stages=new List<Stage>{new Stage{Remaining=100,Title="开始任务",Action=result.NextStep},new Stage{Remaining=90,Title="检查方向",Action="当前的一小步是什么？"},new Stage{Remaining=70,Title="继续推进",Action="暂时放下无关事项，回到当前任务。"},new Stage{Remaining=50,Title="时间过半",Action="检查进度，先完成必要部分。"},new Stage{Remaining=30,Title="进入后半程",Action="缩小范围，优先做出可用结果。"},new Stage{Remaining=10,Title="收尾与保存",Action="整理已有成果，留时间保存。"}};result.PlanSource="默认提醒（可再 AI 拆解）";}
    if(result.PlanSource=="待拆解"||result.PlanSource=="待 AI 拆解")result.PlanSource="手动子任务";Result=result;DialogResult=DialogResult.OK;Close();
   }catch(Exception ex){status.Text=ex.Message;}
  }
 }
}











