using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Media;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Win32;

namespace LittleFocus {
 public class MainForm:Form {
  readonly Store store;AppData data;FocusEngine engine;ApiConfig api;
  readonly Random random=new Random();readonly System.Windows.Forms.Timer timer=new System.Windows.Forms.Timer{Interval=500};
  SyncConfig sync;bool syncing;DateTime nextSync=DateTime.UtcNow.AddMinutes(5);CancellationTokenSource syncCancel,distractionCancel;Label syncStatus;
  NotifyIcon tray;Notice notice;string noticeKind="";DateTime savedAt=DateTime.UtcNow;bool updating,closing,saveError,exitRequested;
  TabControl tabs;TaskListBox projects;Label projectToday;RadioButton briefHistory;CheckedListBox subtasks,ideas;RadioButton activeView,completedView;Label currentTitle,phase,time,caption,progressText,reward,status,activityLabel;
  ProgressBar progress;StagePath pathBar;Button start,pause,stop,rest,complete,restoreTask;DateTimePicker from,to;DataGridView summary,records;Label total;
  MiniTimer mini;TextBox nextStep;Label stepHeading,resumeHint;Button stepDone,resumeCard,stuck,expandSteps,distractionMain;CheckBox allowDistractionMain;bool stepsExpanded;Project undoProject;Stage undoStage;string undoSmall;string feedback="";DateTime feedbackUntil;
  List<Project> visibleProjects=new List<Project>();List<BreakIdea> visibleIdeas=new List<BreakIdea>();Project shownProject;BreakIdea activity;
  readonly List<BreakIdea> builtins=new List<BreakIdea>{
   new BreakIdea{Name="离开椅子，走一小圈",Detail="在房间或走廊轻松走动 5 分钟，暂时放下屏幕。"},
   new BreakIdea{Name="去接一杯水",Detail="起身接水，按需要喝几口，再慢慢走动一会儿。"},
   new BreakIdea{Name="去窗边看看远处",Detail="走到安全的窗边，看看树、天空或远处建筑，再走几步。"},
   new BreakIdea{Name="走着听一首歌",Detail="放一首喜欢的歌，在安全的空间轻松走动，注意脚下。"},
   new BreakIdea{Name="给桌面留一点空白",Detail="站起来，把几件小东西放回原位。不必变成大扫除。"},
   new BreakIdea{Name="松一松肩膀",Detail="起身走动，轻轻耸肩再放下，手臂自然摆动。不舒服就停下。"},
   new BreakIdea{Name="给植物一点关注",Detail="走到植物旁看看新叶，再在附近走动一会儿。"},
   new BreakIdea{Name="走走，想想喜欢的饭",Detail="离开工位，想想一道喜欢的食物或味道，不用做记录。"}
  };
  public MainForm(Store s){
   store=s;data=store.Load();if(data.DistractionTopic=="根据我的兴趣，给一条轻松、有用的中文内容"||data.DistractionTopic=="随机十万个为什么或英文新闻")data.DistractionTopic="";engine=new FocusEngine(data);try{api=ApiConfig.Load(store.DirectoryPath);}catch(Exception){api=new ApiConfig();}try{sync=SyncConfig.Load(store.DirectoryPath);}catch(Exception){sync=new SyncConfig();}
   UI.FormStyle(this,Brand.AppName+" · 一次只做一件事",1120,785);Icon=SeedIcon();MinimumSize=new Size(1030,740);StartPosition=FormStartPosition.CenterScreen;Padding=new Padding(20,12,20,10);
   var root=UI.Table(1,66,-100,34);var header=UI.Table(2,-100);header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,650));header.Controls.Add(UI.Label("专注小站 · 一次一件事",18,true),0,0);header.Controls.Add(UI.Flow(UI.Button("迷你计时条",()=>ShowMini()),UI.Button("收藏宝藏",()=>ShowFavorites()),UI.Button("收进托盘",()=>Hide())),1,0);root.Controls.Add(header,0,0);
   tabs=new TabControl{Dock=DockStyle.Fill,Font=UI.Font(10),Padding=new Point(20,9)};root.Controls.Add(tabs,0,1);status=UI.Label("本地保存 · 无按键统计 · "+(data.CloseToTray?"关闭窗口后在托盘继续":"关闭窗口即退出"),8.5f);status.ForeColor=UI.Muted;root.Controls.Add(status,0,2);Controls.Add(root);
   BuildFocus();BuildHistory();BuildSettings();BuildTray();RefreshProjects(data.LastProjectId);PickActivity();RefreshDisplay();RefreshHistory();
   timer.Tick+=async(sender,e)=>{HandleEvent(engine.Tick(DateTime.UtcNow));RefreshDisplay();if((DateTime.UtcNow-savedAt).TotalSeconds>=10){Save();if(tabs.SelectedIndex==1)RefreshHistory();}if(sync.AutoSync&&!syncing&&engine.State==Phase.Idle&&DateTime.UtcNow>=nextSync)await SyncNow(true);};timer.Start();
   tabs.SelectedIndexChanged+=(sender,e)=>{if(tabs.SelectedIndex==1)RefreshHistory();};Resize+=(sender,e)=>{if(WindowState==FormWindowState.Minimized){Hide();WindowState=FormWindowState.Normal;}};
   FormClosing+=OnClosing;SystemEvents.PowerModeChanged+=PowerChanged;SystemEvents.SessionSwitch+=SessionChanged;
   Shown+=(sender,e)=>{if(!String.IsNullOrEmpty(store.Warning))ShowNotice("数据恢复",store.Warning,"info",Pair("知道了",null));};
  }
  TabPage Page(string name){var p=new TabPage(name){BackColor=UI.Bg,Padding=new Padding(14)};tabs.TabPages.Add(p);return p;}
  void BuildFocus(){
   var page=Page("现在专注");var layout=UI.Table(2,-100);layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,300));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));page.Controls.Add(layout);
   var left=UI.Table(1,40,46,46,30,42,-100,46);left.BackColor=Color.White;left.Padding=new Padding(12);left.Margin=new Padding(0,0,14,0);layout.Controls.Add(left,0,0);
   left.Controls.Add(UI.Label("我的任务",15,true),0,0);left.Controls.Add(UI.Flow(UI.Button("＋ 新建",()=>EditProject(null),true),UI.Button("整理任务",()=>EditProject(Selected()))),0,1);
   activeView=new RadioButton{Text="进行中",Appearance=Appearance.Button,AutoSize=true,Checked=true,Padding=new Padding(12,5,12,5),Margin=new Padding(4),FlatStyle=FlatStyle.Flat};completedView=new RadioButton{Text="已完成",Appearance=Appearance.Button,AutoSize=true,Padding=new Padding(12,5,12,5),Margin=new Padding(4),FlatStyle=FlatStyle.Flat};left.Controls.Add(UI.Flow(activeView,completedView),0,2);
   
   var taskHint=UI.Label("选一个任务，右侧只看当前一步。",8.5f);taskHint.ForeColor=UI.Muted;left.Controls.Add(taskHint,0,3);
   projects=new TaskListBox{Name="ProjectList",Dock=DockStyle.Fill,Font=UI.Font(14),BorderStyle=BorderStyle.None,IntegralHeight=false,BackColor=Color.White,HorizontalScrollbar=false,Margin=new Padding(0,4,0,4)};left.Controls.Add(projects,0,4);left.SetRowSpan(projects,2);
   projects.SelectedIndexChanged+=(s,e)=>{if(!updating){stepsExpanded=projects.SelectedIndex>=0;RefreshSubtasks();RefreshDisplay();}};
   projects.DoubleClick+=(s,e)=>EditProject(Selected());
   var taskMenu=new ContextMenuStrip();taskMenu.Items.Add("复制任务（名称、描述与子任务）",null,(s,e)=>CopySelected());taskMenu.Items.Add("删除任务及历史记录",null,(s,e)=>DeleteSelected());projects.ContextMenuStrip=taskMenu;projects.MouseDown+=(s,e)=>{if(e.Button==MouseButtons.Right){int i=projects.IndexFromPoint(e.Location);if(i>=0)projects.SelectedIndex=i;}};
   restoreTask=UI.Button("恢复到进行中",()=>RestoreTask());left.Controls.Add(UI.Flow(restoreTask),0,6);completedView.CheckedChanged+=(s,e)=>RefreshProjects(null);
   var right=UI.Table(1,40,24,118,164,46,0,46,24,-100,34);right.MinimumSize=new Size(0,630);var rightScroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true};layout.Controls.Add(rightScroll,1,0);rightScroll.Controls.Add(right);right.Dock=DockStyle.Top;right.Height=630;rightScroll.SizeChanged+=(s,e)=>{right.Height=Math.Max(right.MinimumSize.Height,rightScroll.ClientSize.Height);};right.Padding=new Padding(16,6,16,4);right.BackColor=Color.White;
   currentTitle=UI.Label("先选一个任务",17,true);right.Controls.Add(currentTitle,0,0);projectToday=UI.Label("",9);projectToday.ForeColor=UI.Muted;right.Controls.Add(projectToday,0,1);
   var nextCard=UI.Table(1,28,50,24);nextCard.BackColor=Color.FromArgb(242,246,237);nextCard.Padding=new Padding(12,8,12,8);nextCard.Margin=new Padding(0,4,0,10);stepHeading=UI.Label("现在只做这一小步",10.5f,true);stepHeading.AutoEllipsis=false;nextCard.Controls.Add(stepHeading,0,0);nextStep=UI.TextBox(true);nextStep.Name="NextAction";nextStep.ReadOnly=true;nextStep.BorderStyle=BorderStyle.None;nextStep.BackColor=nextCard.BackColor;nextStep.ForeColor=UI.Ink;nextStep.Font=UI.Font(10.5f);nextStep.TabStop=false;nextCard.Controls.Add(nextStep,0,1);resumeHint=UI.Label("",9);resumeHint.ForeColor=UI.Muted;resumeHint.AutoEllipsis=false;nextCard.Controls.Add(resumeHint,0,2);right.Controls.Add(nextCard,0,2);
   var timerBox=UI.Table(2,24,68,28,10,24,24);timerBox.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));timerBox.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,180));timerBox.BackColor=UI.Soft;timerBox.Padding=new Padding(14,2,14,2);phase=UI.Label("准备好了就开始",10,true);phase.AutoEllipsis=false;phase.TextAlign=ContentAlignment.MiddleCenter;phase.Cursor=Cursors.Hand;phase.Click+=(s,e)=>ToggleSelectedMode();timerBox.Controls.Add(phase,0,0);time=UI.Label("25:00",32);time.Name="MainCountdown";time.TextAlign=ContentAlignment.MiddleCenter;time.Cursor=Cursors.Hand;time.DoubleClick+=(s,e)=>EditCurrentDuration();timerBox.Controls.Add(time,0,1);caption=UI.Label("到点后，确认才进入休息。",9);caption.AutoEllipsis=false;caption.TextAlign=ContentAlignment.MiddleCenter;timerBox.Controls.Add(caption,0,2);progress=new ProgressBar{Dock=DockStyle.Fill,Maximum=1000,Style=ProgressBarStyle.Continuous,Margin=new Padding(20,2,20,2)};timerBox.Controls.Add(progress,0,3);progressText=UI.Label("",8);progressText.TextAlign=ContentAlignment.MiddleCenter;pathBar=new StagePath{Dock=DockStyle.Fill,Margin=new Padding(20,0,20,0)};timerBox.Controls.Add(pathBar,0,4);allowDistractionMain=new CheckBox{Name="AllowDistractionMain",Text="允许分心",AutoSize=true,Visible=false,Margin=new Padding(4,0,4,0),BackColor=UI.Soft,Anchor=AnchorStyles.Left};allowDistractionMain.CheckedChanged+=(s,e)=>{if(updating||shownProject==null)return;shownProject.AllowDistraction=allowDistractionMain.Checked;shownProject.UpdatedUtc=DateTime.UtcNow;Save();RefreshDisplay();};timerBox.Controls.Add(allowDistractionMain,1,4);timerBox.SetRowSpan(allowDistractionMain,2);right.Controls.Add(timerBox,0,3);
   start=UI.Button("开始计时",()=>StartSelected(),true);pause=UI.Button("暂停",()=>PauseResume());rest=UI.Button("开始休息",()=>{if(engine.State==Phase.Break)EarlyFocus();else BeginBreak();});stop=UI.Button("结束本次",()=>EndFocus("手动结束"));complete=UI.Button("完成任务",()=>CompleteTask());right.Controls.Add(UI.Flow(start,pause,rest,stop,complete),0,4);Tint(rest,Color.FromArgb(62,116,111));pause.ForeColor=UI.Purple;pause.FlatAppearance.BorderColor=UI.Purple;stop.ForeColor=Color.FromArgb(144,90,55);stop.FlatAppearance.BorderColor=stop.ForeColor;complete.ForeColor=UI.Green;complete.FlatAppearance.BorderColor=UI.Green;
   activityLabel=UI.Label("",9);activityLabel.ForeColor=UI.Muted;right.Controls.Add(activityLabel,0,5);
   stepDone=UI.Button("完成当前一步",()=>FinishStep());resumeCard=UI.Button("留接续卡",()=>EditResume());stuck=UI.Button("卡住了",()=>Unstuck());stuck.ForeColor=UI.Purple;stuck.FlatAppearance.BorderColor=UI.Purple;expandSteps=UI.Button("展开全部步骤",()=>{stepsExpanded=!stepsExpanded;subtasks.Visible=stepsExpanded&&engine.State!=Phase.Break;RefreshDisplay();});distractionMain=UI.Button("分心一下",()=>ShowDistraction());distractionMain.Visible=false;right.Controls.Add(UI.Flow(stepDone,resumeCard,stuck,expandSteps),0,6);
   var stepsHint=UI.Label("完整路径 · 现在只需要处理第一条未完成步骤",9,true);stepsHint.ForeColor=UI.Muted;right.Controls.Add(stepsHint,0,7);
   subtasks=new CheckedListBox{Dock=DockStyle.Fill,Font=UI.Font(13),MinimumSize=new Size(0,190),CheckOnClick=true,BorderStyle=BorderStyle.None,IntegralHeight=false,BackColor=Color.White,Visible=false,HorizontalScrollbar=true};right.Controls.Add(subtasks,0,8);
   subtasks.DoubleClick+=(s,e)=>EditSelectedStageDuration();
   subtasks.ItemCheck+=(s,e)=>{if(updating||shownProject==null||e.Index>=shownProject.Stages.Count)return;var stage=shownProject.Stages[e.Index];undoProject=null;bool completing=e.NewValue==CheckState.Checked;if(completing&&engine.IsChallenge&&engine.Current==shownProject){double saved=engine.PlannedStageRemaining(stage);engine.Pause(DateTime.UtcNow);stage.Done=true;shownProject.SmallStep="";shownProject.UpdatedUtc=DateTime.UtcNow;BeginInvoke(new Action(()=>ChallengeEarly(stage,saved)));return;}if(engine.Current==shownProject)HandleEvent(engine.Tick(DateTime.UtcNow));stage.Done=completing;shownProject.SmallStep="";shownProject.UpdatedUtc=DateTime.UtcNow;Feedback(stage.Done?"已完成："+stage.Title:"已恢复："+stage.Title);BeginInvoke(new Action(()=>{Save();RefreshDisplay();}));};
   reward=UI.Label("",9);reward.ForeColor=UI.Green;right.Controls.Add(reward,0,9);
  }
  void Feedback(string text){feedback=text;feedbackUntil=DateTime.UtcNow.AddSeconds(8);}
  void EditSelectedStageDuration(){var p=Selected();int index=subtasks.SelectedIndex;if(engine.State!=Phase.Idle||p==null||index<0||index>=p.Stages.Count)return;var stage=p.Stages[index];using(var f=new Form()){UI.FormStyle(f,"修改子任务时长",470,260);f.Padding=new Padding(20);decimal initial=(decimal)Math.Max(0.1,TaskSupport.StageSeconds(p,stage,data)/60.0);var value=new NumericUpDown{Minimum=.1M,Maximum=Math.Max(1,p.Challenge?p.ChallengeMinutes:(p.PomodoroMinutes>0?p.PomodoroMinutes:data.FocusMinutes)),DecimalPlaces=1,Increment=.5M,Value=Math.Min(initial,Math.Max(1,p.Challenge?p.ChallengeMinutes:(p.PomodoroMinutes>0?p.PomodoroMinutes:data.FocusMinutes))),Width=100,Margin=new Padding(8)};var root=UI.Table(1,48,62,58);root.Controls.Add(UI.Label(stage.Title,12,true),0,0);root.Controls.Add(UI.Flow(UI.Label("分配时长（分钟）",10),value),0,1);root.Controls.Add(UI.Flow(UI.Button("保存",()=>{int total=Math.Max(60,(p.Challenge?p.ChallengeMinutes:(p.PomodoroMinutes>0?p.PomodoroMinutes:data.FocusMinutes))*60),seconds=Math.Max(1,(int)Math.Round((double)value.Value*60)),share=Math.Max(1,(int)Math.Round(seconds*100.0/total));stage.AllocatedSeconds=seconds;if(index+1<p.Stages.Count){int after=index+2<p.Stages.Count?p.Stages[index+2].Remaining:0;p.Stages[index+1].Remaining=Math.Max(after,Math.Min(stage.Remaining,stage.Remaining-share));p.Stages[index+1].AllocatedSeconds=0;}else{int upper=index==0?100:p.Stages[index-1].Remaining;stage.Remaining=Math.Max(0,Math.Min(upper,share));}p.UpdatedUtc=DateTime.UtcNow;Save();RefreshSubtasks();RefreshDisplay();f.Close();},true),UI.Button("取消",()=>f.Close())),0,2);f.Controls.Add(root);f.ShowDialog(this);}}
  void EditResume(){EditResumeFor(DisplayProject());}
  void EditResumeFor(Project p){if(p==null||p.Completed)return;using(var d=new ResumeDialog(p,api,data)){if(d.ShowDialog(this)==DialogResult.OK){undoProject=null;Save();Feedback("接续卡已保存，下次可以从这里继续。");RefreshDisplay();}}}
  void Unstuck(){var p=DisplayProject();if(p==null||p.Completed)return;using(var d=new StuckDialog(p)){if(d.ShowDialog(this)==DialogResult.OK){undoProject=null;p.SmallStep=d.Result;p.UpdatedUtc=DateTime.UtcNow;Save();Feedback("起步动作已缩小，计时规则没有改变。");RefreshDisplay();}}}
  void FinishStep(){var p=DisplayProject();if(engine.Current==p)HandleEvent(engine.Tick(DateTime.UtcNow));if(p==null||p.Completed)return;var stage=p.Stages.FirstOrDefault(x=>!x.Done);if(String.IsNullOrWhiteSpace(p.SmallStep)&&stage==null)return;undoProject=p;undoSmall=p.SmallStep;undoStage=String.IsNullOrWhiteSpace(p.SmallStep)?stage:null;string done=TaskSupport.Next(p);if(undoStage!=null)undoStage.Done=true;else p.SmallStep="";if(engine.Current==p)engine.RefreshStageDeadline();p.LastCheckpoint="刚刚做完："+done;p.UpdatedUtc=DateTime.UtcNow;Feedback("这一步已记录，可以继续，也可以先停下。");Save();RefreshSubtasks();RefreshDisplay();}
  void UndoStep(){if(undoProject==null||undoProject!=DisplayProject()||undoProject.Completed)return;if(undoStage!=null){if(!undoProject.Stages.Contains(undoStage))return;undoStage.Done=false;}else undoProject.SmallStep=undoSmall;if(engine.Current==undoProject)engine.RefreshStageDeadline();undoProject.LastCheckpoint="已恢复上一步";undoProject.UpdatedUtc=DateTime.UtcNow;undoProject=null;Save();RefreshSubtasks();Feedback("上一步已恢复。");RefreshDisplay();}
  void WithdrawLastStage(){var p=DisplayProject();if(p==null||p.Completed)return;var stage=p.Stages.LastOrDefault(x=>x.Done);if(stage==null)return;stage.Done=false;if(engine.Current==p)engine.RefreshStageDeadline();p.UpdatedUtc=DateTime.UtcNow;Feedback("已撤回完成标记，可以重新推进这一步。");Save();RefreshSubtasks();RefreshDisplay();}
  Project Selected(){return projects.SelectedIndex>=0&&projects.SelectedIndex<visibleProjects.Count?visibleProjects[projects.SelectedIndex]:null;}
  Project DisplayProject(){return engine.State!=Phase.Idle?engine.Current:Selected();}
  void RefreshProjects(string selectedId){updating=true;projects.Items.Clear();visibleProjects=data.Projects.Where(p=>!p.Deleted&&p.Completed==completedView.Checked).ToList();int projectExtent=0;foreach(var p in visibleProjects){string label=(p.Stages!=null&&p.Stages.Count>0?"▸ ":"")+p.Name;projects.Items.Add(label);projectExtent=Math.Max(projectExtent,TextRenderer.MeasureText(label,projects.Font).Width+36);}projects.HorizontalScrollbar=true;projects.HorizontalExtent=Math.Max(0,projectExtent);int index=visibleProjects.FindIndex(p=>p.Id==selectedId);if(index>=0)projects.SelectedIndex=index;else if(projects.Items.Count>0)projects.SelectedIndex=0;updating=false;stepsExpanded=projects.SelectedIndex>=0;RefreshSubtasks();RefreshDisplay();}
  void RefreshSubtasks(){updating=true;shownProject=DisplayProject();subtasks.Items.Clear();int extent=0;if(shownProject!=null)foreach(var s in shownProject.Stages){string label=s.Title+"  ·  "+FocusEngine.Duration(TaskSupport.StageSeconds(shownProject,s,data));subtasks.Items.Add(label,s.Done);extent=Math.Max(extent,TextRenderer.MeasureText(label,subtasks.Font).Width+34);}subtasks.HorizontalExtent=Math.Max(0,extent);updating=false;}
  void EditProject(Project project){if(project!=null&&engine.State!=Phase.Idle&&engine.Current!=null&&project.Id==engine.Current.Id){MessageBox.Show(this,"请先结束当前任务，再修改模式或子任务计划。子任务仍可以直接勾选。","先结束计时");return;}using(var d=new ProjectDialog(project??new Project(),api,store.DirectoryPath,data)){if(d.ShowDialog(this)!=DialogResult.OK)return;int i=data.Projects.FindIndex(p=>p.Id==d.Result.Id);if(i<0)data.Projects.Add(d.Result);else data.Projects[i]=d.Result;Save();RefreshProjects(d.Result.Id);RefreshHistory();}}
  void DeleteSelected(){var p=Selected();if(p==null)return;if(engine.State!=Phase.Idle&&engine.Current==p){MessageBox.Show(this,"请先结束本次计时，再删除任务。删除将一并清除该项目的历史记录。");return;}p.Deleted=true;p.UpdatedUtc=DateTime.UtcNow;data.Records.RemoveAll(r=>r.ProjectId==p.Id);data.ChallengeAdjustments.RemoveAll(a=>a.ProjectId==p.Id);data.FreshContents.RemoveAll(a=>a.ProjectId==p.Id);data.DistractionLog.RemoveAll(a=>a.ProjectId==p.Id);undoProject=null;Save();RefreshProjects(null);RefreshHistory();}
  void CopySelected(){var p=Selected();if(p==null)return;if(engine.State!=Phase.Idle&&engine.Current==p){MessageBox.Show(this,"请先结束本次计时，再复制该任务。","先结束计时");return;}var copy=new Project{Name=UniqueProjectName(p.Name),NextStep=p.NextStep,SmallStep="",ResumeNote="",DoneWhen=p.DoneWhen,Challenge=p.Challenge,ChallengeMinutes=p.ChallengeMinutes,ChallengeMinutesCustomized=p.ChallengeMinutesCustomized,PomodoroMinutes=p.PomodoroMinutes,AllowDistraction=p.AllowDistraction,PlanSource=p.PlanSource};foreach(var s in p.Stages)copy.Stages.Add(new Stage{Title=s.Title,Action=s.Action,Remaining=s.Remaining,AllocatedSeconds=s.AllocatedSeconds,Done=false});copy.UpdatedUtc=DateTime.UtcNow;data.Projects.Add(copy);Save();RefreshProjects(copy.Id);RefreshHistory();Feedback("已复制为“"+copy.Name+"”，子任务的完成状态已清零。");}
  string UniqueProjectName(string baseName){string name=String.IsNullOrWhiteSpace(baseName)?"未命名任务":baseName.Trim();int n=1;int open=name.LastIndexOf('（');if(open>0&&name.EndsWith("）")){int value;if(Int32.TryParse(name.Substring(open+1,name.Length-open-2),out value)&&value>0){name=name.Substring(0,open).TrimEnd();n=value+1;}}var taken=new HashSet<string>(data.Projects.Where(x=>!x.Deleted).Select(x=>x.Name));string candidate=name+"（"+n+"）";while(taken.Contains(candidate)){n++;candidate=name+"（"+n+"）";}return candidate;}
  void ToggleSelectedMode(){if(engine.State!=Phase.Idle)return;var p=Selected();if(p==null||p.Completed)return;if(!p.Challenge&&!p.ChallengeMinutesCustomized)p.ChallengeMinutes=p.PomodoroMinutes>0?p.PomodoroMinutes:data.FocusMinutes;p.Challenge=!p.Challenge;p.UpdatedUtc=DateTime.UtcNow;Save();RefreshSubtasks();RefreshDisplay();}
      void EditCurrentDuration(){if(engine.State!=Phase.Idle)return;var p=Selected();if(p==null||p.Completed)return;bool challenge=p.Challenge;using(var f=new Form()){UI.FormStyle(f,"本项目的总时长",460,250);f.Padding=new Padding(20);int initial=challenge?Math.Max(1,p.ChallengeMinutes):Math.Max(1,p.PomodoroMinutes>0?p.PomodoroMinutes:data.FocusMinutes);var n=new NumericUpDown{Minimum=1,Maximum=720,Value=initial,Width=100,Margin=new Padding(8)};var root=UI.Table(1,48,60,58);root.Controls.Add(UI.Label("只影响“"+p.Name+"” · 保存后会刷新全部子任务时长",11,true),0,0);root.Controls.Add(UI.Flow(UI.Label("项目总分钟",10),n),0,1);root.Controls.Add(UI.Flow(UI.Button("保存",()=>{if(challenge){p.ChallengeMinutes=(int)n.Value;p.ChallengeMinutesCustomized=true;}else p.PomodoroMinutes=(int)n.Value;foreach(var s in p.Stages)s.AllocatedSeconds=0;p.UpdatedUtc=DateTime.UtcNow;Save();RefreshSubtasks();RefreshDisplay();f.Close();},true),UI.Button("恢复全局默认",()=>{if(challenge){p.ChallengeMinutes=(int)data.FocusMinutes;p.ChallengeMinutesCustomized=false;}else p.PomodoroMinutes=0;foreach(var s in p.Stages)s.AllocatedSeconds=0;p.UpdatedUtc=DateTime.UtcNow;Save();RefreshSubtasks();RefreshDisplay();f.Close();})),0,2);f.Controls.Add(root);f.ShowDialog(this);}}  void RestoreTask(){var p=Selected();if(p==null||!p.Completed)return;p.Completed=false;p.Enabled=true;p.UpdatedUtc=DateTime.UtcNow;Save();activeView.Checked=true;RefreshProjects(p.Id);}
  void CompleteTask(){var p=DisplayProject();if(p==null||p.Completed)return;bool timed=engine.State!=Phase.Idle&&engine.Current!=null&&engine.Current.Id==p.Id;engine.Complete(p,DateTime.UtcNow);CloseNotice();if(!Save())return;RefreshProjects(null);RefreshHistory();ShowNotice("任务完成，记录已保存",p.Name+(timed?"\n本轮专注："+FocusEngine.Duration(engine.RunSeconds):"")+"\n\n任务已移到“已完成”视图，可以随时查看或恢复。","completed",Pair("知道了",null));QueueEncouragement("task-complete",notice,timed?engine.SessionSeconds:0);}
  void StartSelected(){
   if(syncing){MessageBox.Show(this,"正在同步，完成后即可开始计时。");return;}if(engine.State!=Phase.Idle&&engine.State!=Phase.Ready)return;var p=engine.State==Phase.Ready?engine.Current:Selected();if(p==null||p.Completed){MessageBox.Show(this,"请选择一个进行中的任务。","选一个任务");return;}
   if(p.Challenge&&Planner.Validate(p.Stages)!=null){MessageBox.Show(this,"挑战需要有效的阶段计划，请编辑任务并拆解或手动设置。","先设置阶段");return;}
   CloseNotice();data.LastProjectId=p.Id;engine.Start(p,DateTime.UtcNow);RefreshSubtasks();Save();RefreshDisplay();BeginInvoke(new Action(()=>{if(!IsDisposed)ShowMini();}));
  }
  void PauseResume(){if(engine.State==Phase.Focus){TaskSupport.Remember(engine.Current);HandleEvent(engine.Pause(DateTime.UtcNow));if(noticeKind=="due")CloseNotice();}else if(engine.State==Phase.Paused){if(engine.ReminderSent)engine.Snooze();engine.Resume(DateTime.UtcNow);CloseNotice();}Save();RefreshDisplay();}
  static void Tint(Button b,Color c){b.BackColor=c;b.ForeColor=Color.White;b.FlatAppearance.BorderColor=c;}
  static void Primary(Button b,bool primary){b.BackColor=primary?UI.Green:Color.White;b.ForeColor=primary?Color.White:UI.Ink;b.FlatAppearance.BorderColor=primary?UI.Green:Color.FromArgb(216,223,209);}
  void EarlyFocus(){if(!engine.EndBreakEarly(DateTime.UtcNow))return;CloseNotice();Save();RefreshSubtasks();RefreshDisplay();}
  void BeginBreak(){TaskSupport.Remember(engine.Current);if(engine.BeginBreak(DateTime.UtcNow)){CloseNotice();PickActivity();Save();RefreshDisplay();ShowRest();}}
  async void ShowDistraction(){if(engine.State!=Phase.Focus&&engine.State!=Phase.Paused)return;bool resumeAfterClose=engine.State==Phase.Focus,dialogShown=false;engine.Pause(DateTime.UtcNow);Save();RefreshDisplay();var p=engine.Current;string projectId=p==null?"":p.Id;var directions=(data.DistractionTopic??"").Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).Take(3).ToList();bool noDirection=directions.Count==0;string chosen=noDirection?"":directions[random.Next(directions.Count)];string relatedProject=noDirection||data.DistractionUseProjectName?(p==null?"":p.Name):"";try{FreshContent item=null;if(data.LastFresh!=null&&data.LastFresh.Kind=="personalized"&&data.LastFreshProjectId==projectId&&(DateTime.UtcNow-data.LastFreshAtUtc).TotalMinutes<data.DistractionCooldownMinutes)item=data.LastFresh;if(item==null){if(!api.Enabled||String.IsNullOrWhiteSpace(api.Model)){ShowNotice("个性化探索未配置","请先启用 API 并配置模型。计时保持暂停。","distraction",Pair("知道了",null));return;}status.Text="正在生成一条简短内容…";if(distractionCancel!=null)distractionCancel.Cancel();using(var request=new CancellationTokenSource(TimeSpan.FromSeconds(20))){distractionCancel=request;item=await Planner.Fresh(api,chosen,data.DistractionMaxChars,relatedProject,request.Token);if(distractionCancel==request)distractionCancel=null;}item.ProjectId=projectId;item.ProjectName=p==null?"":p.Name;item.SavedUtc=DateTime.UtcNow;data.LastFresh=item;data.LastFreshAtUtc=DateTime.UtcNow;data.LastFreshProjectId=projectId;data.DistractionLog.Add(new DistractionRecord{ProjectId=projectId,ProjectName=item.ProjectName,Kind=item.Kind,Topic=noDirection?"未设置方向 · 根据项目名":chosen,Title=item.Title,Body=item.Body,SourceUrl=item.SourceUrl,CharCount=(item.Body??"").Length});Save();}if(noDirection&&!item.Body.StartsWith("你还没有选择个性化方向"))item.Body="你还没有选择个性化方向，本次内容根据项目名称生成。\r\n\r\n"+item.Body;using(var d=new FreshContentDialog(item,projectId,x=>SaveFavorite(x))){dialogShown=true;d.ShowDialog(this);}status.Text=resumeAfterClose?"内容已看完，已继续本轮计时。":"内容已看完；仍保持原来的暂停状态。";}catch(OperationCanceledException){if(!IsDisposed)ShowNotice("个性化内容生成已停止","生成超过 20 秒或窗口正在关闭。计时保持暂停，可以稍后重试。","distraction-error",Pair("知道了",null));}catch(Exception ex){if(!IsDisposed)ShowNotice("个性化内容暂时不可用",ex.Message+"\n\n计时保持暂停，不自动重试。","distraction-error",Pair("知道了",null));}finally{distractionCancel=null;if(dialogShown&&resumeAfterClose&&!IsDisposed&&engine.State==Phase.Paused){engine.Resume(DateTime.UtcNow);Save();RefreshDisplay();}}}
  void SaveFavorite(FreshContent item){var old=data.FreshContents.FirstOrDefault(x=>x.Id==item.Id);if(old==null)data.FreshContents.Add(item);else{old.Favorite=true;old.Body=item.Body;old.SourceUrl=item.SourceUrl;}Save();}
  void ShowFavorites(){using(var d=new FavoritesDialog(data.FreshContents,()=>{foreach(var item in data.FreshContents)item.Favorite=false;data.FreshContents.Clear();if(data.LastFresh!=null)data.LastFresh.Favorite=false;Save();}))d.ShowDialog(this);}
  void ShowDistractionSettings(){using(var d=new DistractionSettingsDialog(data)){if(d.ShowDialog(this)==DialogResult.OK){Save();}}}
  void ShowProjectDetails(){string selected=Selected()==null?null:Selected().Id;using(var d=new ProjectDetailsDialog(data,selected))d.ShowDialog(this);}
  void ShowDistractionLog(){using(var d=new SelfReviewDialog(data,api,()=>Save()))d.ShowDialog(this);}
  void ShowDataManagement(){using(var d=new DataManagementDialog(()=>Backup(),()=>Restore(),()=>OpenFolder(),()=>ShowFavorites(),()=>ShowDistractionLog(),()=>ClearAllData()))d.ShowDialog(this);}
  void ClearAllData(){if(engine.State!=Phase.Idle){MessageBox.Show(this,"请先结束当前计时，再清空全部数据。已经记录的本轮时间不会丢失。","当前仍在计时");return;}if(MessageBox.Show(this,"将清空所有项目、计时记录、自定义活动、收藏和 AI 本地分析。\n\nAPI 与同步配置会保留。继续吗？","清空全部数据",MessageBoxButtons.OKCancel,MessageBoxIcon.Warning)!=DialogResult.OK)return;if(MessageBox.Show(this,"这是最后一次确认。清空后主界面会恢复为空白状态。\n\n程序会先在数据文件夹保存一份“清空前”备份。","确认清空",MessageBoxButtons.OKCancel,MessageBoxIcon.Warning)!=DialogResult.OK)return;try{Directory.CreateDirectory(store.DirectoryPath);if(File.Exists(store.FilePath))File.Copy(store.FilePath,Path.Combine(store.DirectoryPath,"清空前-"+DateTime.Now.ToString("yyyyMMdd-HHmmss-fff")+".xml"),false);var fresh=new AppData();store.Save(fresh);data=fresh;engine=new FocusEngine(data);activity=null;undoProject=null;undoStage=null;restLines.Clear();restLineKey="";CloseNotice();RefreshProjects(null);RefreshIdeas();RefreshHistory();PickActivity();RefreshDisplay();status.Text="全部本地业务数据已清空；API 与同步配置已保留。";MessageBox.Show(this,"已清空全部数据。\n清空前备份保存在数据文件夹中。","清空完成");}catch(Exception){MessageBox.Show(this,"清空失败，原数据仍保留。请检查数据目录是否可写。","未清空");}}
  string RestText(){return "项目："+engine.Current.Name+"\n本轮已专注 "+FocusEngine.Duration(engine.RunSeconds)+"\n\n"+activity.Name+"\n"+activity.Detail;}
  void ShowRest(){ShowNotice("休息时间",RestText(),"rest",Pair("知道了，去活动",null),Pair("换一个",()=>{PickActivity();ShowRest();}),Pair("提前专注",()=>EarlyFocus()));QueueBreakEncouragement(notice);}
  void EndFocus(string outcome){if(engine.State==Phase.Idle)return;TaskSupport.Remember(engine.Current);var endedProject=engine.Current;string name=engine.Current==null?"任务":engine.Current.Name;double seconds=engine.RunSeconds;bool challenge=engine.IsChallenge;engine.Stop(DateTime.UtcNow,outcome);seconds=engine.RunSeconds;CloseNotice();Save();RefreshSubtasks();RefreshHistory();RefreshDisplay();ShowNotice("专注结束，时间已保存",name+"\n本轮专注："+FocusEngine.Duration(seconds)+"\n\n"+(engine.LastAward>0&&data.Rewards?(challenge?"完成一次挑战，收下一颗星。":"完成一个番茄，收下一份进展。") :"已经投入的时间都算数。准备好时，再开始下一步。"),"ended",Pair("知道了",null),Pair("留一张接续卡",()=>EditResumeFor(endedProject)));QueueEncouragement("timer-end",notice);}
  static string Short(double secs){long s=(long)Math.Ceiling(Math.Max(0,secs));return String.Format("{0:00}:{1:00}",s/60,s%60);}
  void RefreshDisplay(){
   var p=DisplayProject();bool active=engine.State!=Phase.Idle;currentTitle.Text=p==null?"先选一个任务":p.Name;bool challenge=active?engine.IsChallenge:p!=null&&p.Challenge;
   double goal=active?engine.GoalMinutes*60:(challenge?p.ChallengeMinutes*60:(p!=null&&p.PomodoroMinutes>0?p.PomodoroMinutes:data.FocusMinutes)*60);var idleStage=p==null?null:p.Stages.FirstOrDefault(x=>!x.Done);double stageGoal=active?engine.StageRemaining():TaskSupport.StageSeconds(p,idleStage,data);if(stageGoal<=0)stageGoal=goal;double remaining=Math.Max(0,goal-engine.RunSeconds);
   if(engine.State==Phase.Idle){phase.Text=challenge?"极限挑战 · 准备开始":"番茄钟 · 准备开始";time.Text=Short(stageGoal);caption.Text=challenge?"当前子任务倒计时 · 项目总时长 "+Short(goal)+"；双击数字可修改项目总时长":"当前子任务到点自动暂停，确认后才进入休息。";progress.Value=0;}
   else if(engine.State==Phase.Break){phase.Text="休息中 · 离开椅子走一走";time.Text=Short(engine.BreakSeconds(DateTime.UtcNow));caption.Text="休息不计入项目时长；结束后等你确认继续。";progress.Value=(int)Math.Min(1000,1000*(1-engine.BreakSeconds(DateTime.UtcNow)/300));}
   else if(engine.State==Phase.Ready){phase.Text="休息结束 · 等你回来";time.Text="00:00";caption.Text="点击继续此任务，再开始计时。";progress.Value=1000;}
   else{phase.Text=engine.State==Phase.Paused?"已暂停 · 时间不再累计":challenge?"极限挑战 · 专注进行中":stageGoal<=0?"已到休息时间 · 等待确认":"番茄钟 · 专注进行中";time.Text=Short(stageGoal);caption.Text="本轮已专注 "+FocusEngine.Duration(engine.RunSeconds)+(challenge?" · 项目总剩余 "+Short(engine.ChallengeTotalRemaining()):engine.State==Phase.Paused?" · 点击继续恢复":" · 当前子任务单独计时");progress.Value=(int)Math.Min(1000,engine.RunSeconds/goal*1000);}
   progressText.Text="";pathBar.UpdateStages(p==null?null:p.Stages);
   start.Visible=engine.State==Phase.Idle||engine.State==Phase.Ready;pause.Visible=engine.State==Phase.Focus||engine.State==Phase.Paused;stop.Visible=active;rest.Visible=engine.State==Phase.Break||engine.State==Phase.Focus||engine.State==Phase.Paused;rest.Text=engine.State==Phase.Break?"提前专注":"开始休息";start.Enabled=(engine.State==Phase.Idle||engine.State==Phase.Ready)&&p!=null&&!p.Completed;start.Text=engine.State==Phase.Ready?"继续此任务":"开始计时";pause.Enabled=engine.State==Phase.Focus||engine.State==Phase.Paused;pause.Text=engine.State==Phase.Paused?"继续":"暂停";stop.Enabled=active;rest.Enabled=engine.State==Phase.Break||engine.State==Phase.Focus||engine.State==Phase.Paused;complete.Enabled=p!=null&&!p.Completed;restoreTask.Visible=completedView.Checked;restoreTask.Enabled=Selected()!=null&&Selected().Completed;
   bool resting=engine.State==Phase.Break;stepDone.Visible=resumeCard.Visible=stuck.Visible=!resting;distractionMain.Visible=p!=null&&p.AllowDistraction&&active&&!resting;distractionMain.Enabled=distractionMain.Visible;string next=(resting&&activity!=null?activity.Detail:TaskSupport.Next(p)).Replace("\r\n","\n").Replace("\n","\r\n");if(nextStep.Text!=next)nextStep.Text=next;int doneSteps=p==null?0:p.Stages.Count(x=>x.Done);stepHeading.Text=engine.State==Phase.Break?"现在休息 · 离开椅子走一走":engine.State==Phase.Paused?"已暂停 · 下一步替你留着":"现在只做这一小步";if(!resting&&p!=null&&p.Stages.Count>0)stepHeading.Text+="   ·   已完成 "+doneSteps+" / "+p.Stages.Count;resumeHint.Text=TaskSupport.Checkpoint(p);if(p!=null&&!String.IsNullOrWhiteSpace(p.DoneWhen))resumeHint.Text+=(resumeHint.Text.Length>0?"\n":"")+"完成标准："+p.DoneWhen;if(resting)resumeHint.Text="回来后："+TaskSupport.Next(p);resumeCard.Enabled=stuck.Enabled=p!=null&&!p.Completed;stepDone.Enabled=p!=null&&!p.Completed&&(!String.IsNullOrWhiteSpace(p.SmallStep)||p.Stages.Any(x=>!x.Done));expandSteps.Text=stepsExpanded?"收起全部步骤":"展开全部步骤";expandSteps.Enabled=p!=null&&p.Stages.Count>0;expandSteps.Visible=!resting;subtasks.Visible=stepsExpanded&&engine.State!=Phase.Break;allowDistractionMain.Visible=p!=null&&!resting;updating=true;if(p!=null&&allowDistractionMain.Checked!=p.AllowDistraction)allowDistractionMain.Checked=p.AllowDistraction;updating=false;
    Primary(stepDone,active&&!resting&&stepDone.Enabled);activityLabel.Text="";if(!resting&&String.IsNullOrWhiteSpace(resumeHint.Text))resumeHint.Text=engine.State==Phase.Paused?"进度已经替你保留。准备好时再继续。":"先做上面这一小步，不必现在想完整计划。";   string day=DateTime.Now.ToString("yyyy-MM-dd");double today=data.Records.Where(r=>r.Day==day).Sum(r=>r.Seconds);int tomatoes=data.Records.Where(r=>r.Day==day&&!r.Challenge).Sum(r=>r.Tomatoes),stars=data.Records.Where(r=>r.Day==day&&r.Challenge).Sum(r=>r.Tomatoes);
   double taskSeconds=p==null?0:data.Records.Where(r=>r.Day==day&&r.ProjectId==p.Id).Sum(r=>r.Seconds);projectToday.Text=taskSeconds>0||(active&&engine.State==Phase.Focus)?"今日已专注 "+FocusEngine.Duration(taskSeconds):"";int activeIndex=active&&engine.Current!=null?visibleProjects.FindIndex(x=>x.Id==engine.Current.Id):-1;bool animateProjects=false;if(projects.ActiveIndex!=activeIndex||projects.Animate!=animateProjects){projects.ActiveIndex=activeIndex;projects.Animate=animateProjects;projects.Invalidate();}reward.Text=DateTime.UtcNow<feedbackUntil?feedback:"今日已投入 "+FocusEngine.Duration(today)+(data.Rewards&&!data.LowStimulus&&p!=null&&doneSteps>0?"   ·   这项任务已完成 "+doneSteps+" 个小步骤":"");
   if(tray!=null)tray.Text=(active?(challenge?"挑战 ":"专注 ")+time.Text:Brand.AppName+" · 等待开始");
   if(mini!=null&&!mini.IsDisposed){mini.SetPreferences(data.MiniDimPercent,RestLine());mini.SetStages(p==null?null:p.Stages);mini.SetLowStimulus(data.LowStimulus);mini.UpdateState(p==null?"未选择任务":p.Name,time.Text,phase.Text,engine.State,engine.State==Phase.Idle?0:engine.SessionSeconds,true,p==null?null:p.Stages.FirstOrDefault(x=>!x.Done),challenge&&active?"项目总剩余 "+Short(engine.ChallengeTotalRemaining()):null,p!=null&&p.AllowDistraction,p!=null&&p.Stages.Any(x=>x.Done));}
  }
  void HandleEvent(string evt){
   if(evt==null)return;Save();
   if(evt=="due"){ShowNotice("到休息时间了","项目："+engine.Current.Name+"\n已专注 "+FocusEngine.Duration(engine.RunSeconds)+"\n\n计时已暂停。点击开始休息才开始休息倒计时；关闭弹窗仍保持暂停。","due",Pair("开始休息",()=>BeginBreak()),Pair("继续专注 5 分钟",()=>PauseResume()),Pair("结束本次",()=>EndFocus("手动结束")));QueueBreakEncouragement(notice);}
   else if(evt=="challenge-break")ShowNotice("休息提醒","已经连续专注 "+data.FocusMinutes+" 分钟。挑战计时已暂停，可以现在休息，也可以继续挑战。","challenge-break",Pair("开始休息",()=>BeginBreak()),Pair("继续挑战",()=>{engine.SkipChallengeBreak(DateTime.UtcNow);CloseNotice();Save();RefreshDisplay();}),Pair("保持暂停",null));
   else if(evt=="stage")ShowChallengeStage();
   else if(evt=="challenge-end")ShowChallengeDeadline();
   else if(evt=="break-end")ShowNotice("休息结束，准备回来了吗？","休息已结束，当前没有累计专注时间。\n\n点击继续才会开始新一轮，也可以先结束这个任务。","break-end",Pair("继续此任务",()=>StartSelected()),Pair("结束本次",()=>EndFocus("休息后结束")));
   else if(evt=="interrupted")ShowNotice("已暂停，避免误计时间","检测到系统睡眠或较长中断，未把这段空档记为专注。\n\n你回来后点击继续即可。","interrupted",Pair("继续计时",()=>PauseResume()),Pair("先保持暂停",null));
  }
  void RecordAdjustment(string kind,Stage stage,int delta,string reason){var p=engine.Current;if(p==null)return;data.ChallengeAdjustments.Add(new ChallengeAdjustment{ProjectId=p.Id,ProjectName=p.Name,ProjectDescription=p.NextStep,StageId=stage==null?"":stage.Id,StageName=stage==null?"":stage.Title,Kind=kind,DeltaSeconds=delta,Reason=reason=="我做不完了"?"":reason,PlannedRemainingPercent=stage==null?0:stage.Remaining,GoalSeconds=engine.GoalMinutes*60,ElapsedSeconds=(int)engine.RunSeconds});Save();}
  void ChallengeEarly(Stage stage,double saved){bool overtime=engine.InOvertime;RecordAdjustment(overtime?"overtime-early":"early",stage,overtime?0:-(int)Math.Round(saved),"");if(overtime)engine.CompleteOvertimeStage();string text=overtime?"“"+stage.Title+"”在申请的加时内完成。已使用的加时时长会整体顺延后续节点。":"“"+stage.Title+"”比原定节点提前 "+FocusEngine.Duration(saved)+"。总挑战时间与后续原定节点不变。";using(var d=new ChallengeNoteDialog(overtime?"加时内完成一个路径点":"提前完成一个路径点",text,false,0)){if(d.ShowDialog(this)==DialogResult.OK){if(!String.IsNullOrWhiteSpace(d.Reason)){data.ChallengeAdjustments.Last().Reason=d.Reason;Save();}engine.Resume(DateTime.UtcNow);}}RefreshSubtasks();RefreshDisplay();}
  void ShowChallengeStage(){var stage=engine.Reached.LastOrDefault();foreach(var reached in engine.Reached)reached.Done=true;Save();RefreshSubtasks();RefreshDisplay();ShowNotice("已完成当前路径点",stage==null?"已进入下一步。":"已按原定时间完成："+stage.Title+"\n\n下一步会使用自己的原定时长。项目总剩余 "+Short(engine.ChallengeTotalRemaining()),"stage",Pair("进入下一步",()=>{engine.Resume(DateTime.UtcNow);Save();RefreshDisplay();}),Pair("这一步申请加时",()=>{if(stage!=null)stage.Done=false;Save();RefreshSubtasks();RequestOvertime(stage);}),Pair("保持暂停",null));}
  void RequestOvertime(Stage stage){if(stage==null||stage.Done){ShowNotice("当前步骤已经完成","只有尚未完成的子任务可以申请加时。","stage-finished",Pair("知道了",null));return;}int stageTotal=Math.Max(60,TaskSupport.StageSeconds(engine.Current,stage,data));int suggested=Math.Max(1,(int)Math.Ceiling(stageTotal/180.0));int upper=Math.Max(1,engine.ChallengeBaseMinutes);using(var d=new ChallengeNoteDialog("申请一点时间","当前子任务尚未完成时，可以继续申请加时。默认值是这个子任务时长的三分之一，可拖动或手动输入；单次不超过项目初始总时长。",true,suggested,upper)){if(d.ShowDialog(this)!=DialogResult.OK)return;if(!engine.AddChallengeTime(d.Minutes))return;RecordAdjustment("overtime",stage,d.Minutes*60,d.Reason);engine.Resume(DateTime.UtcNow);Save();RefreshDisplay();}}
  void ShowChallengeDeadline(){var stage=engine.CurrentStage();var actions=new List<KeyValuePair<string,Action>>();if(stage!=null&&!stage.Done)actions.Add(Pair("申请加时",()=>RequestOvertime(stage)));actions.Add(Pair("完成挑战",()=>{var p=engine.Current;if(stage!=null)stage.Done=true;engine.FinishChallenge("挑战结束");Save();RefreshSubtasks();RefreshHistory();RefreshDisplay();ShowNotice("挑战结束，时间已保存",p.Name+"\n本次投入 "+FocusEngine.Duration(engine.RunSeconds),"ended",Pair("知道了",null));}));actions.Add(Pair("保持暂停",null));ShowNotice("挑战时间已到","项目："+engine.Current.Name+"\n已到当前总时限，计时暂停。只要当前子任务未完成，就可以继续申请加时。","challenge-due",actions.ToArray());}
  static KeyValuePair<string,Action> Pair(string label,Action action){return new KeyValuePair<string,Action>(label,action);}
  void ShowNotice(string title,string text,string kind,params KeyValuePair<string,Action>[] actions){CloseNotice();noticeKind=kind;notice=new Notice(title,text,actions);notice.StartPosition=FormStartPosition.CenterScreen;notice.Show();PlaySound(false);}
  [DllImport("winmm.dll",CharSet=CharSet.Unicode)]static extern int mciSendString(string command,StringBuilder result,int length,IntPtr callback);
  void PlaySound(bool preview){if(!preview&&(!data.Sound||data.LowStimulus))return;if(!String.IsNullOrWhiteSpace(data.SoundPath)&&File.Exists(data.SoundPath)){try{mciSendString("close focus_notice",null,0,IntPtr.Zero);int opened=mciSendString("open \""+data.SoundPath.Replace("\"","\"\"")+"\" alias focus_notice",null,0,IntPtr.Zero);if(opened==0&&mciSendString("play focus_notice from 0",null,0,IntPtr.Zero)==0)return;}catch{}}Task.Run(()=>PlayPreset(data.SoundPreset??"短双音"));}
  static void PlayPreset(string preset){try{int[] notes=preset=="柔和单音"?new[]{660}:preset=="上扬三音"?new[]{523,659,784}:new[]{660,880};using(var stream=ToneWave(notes))using(var player=new SoundPlayer(stream))player.PlaySync();}catch{}}
  static MemoryStream ToneWave(int[] notes){const int rate=44100;int toneSamples=rate*110/1000,gapSamples=rate*35/1000,total=notes.Length*toneSamples+Math.Max(0,notes.Length-1)*gapSamples;var stream=new MemoryStream();using(var w=new BinaryWriter(stream,Encoding.ASCII,true)){w.Write(Encoding.ASCII.GetBytes("RIFF"));w.Write(36+total*2);w.Write(Encoding.ASCII.GetBytes("WAVEfmt "));w.Write(16);w.Write((short)1);w.Write((short)1);w.Write(rate);w.Write(rate*2);w.Write((short)2);w.Write((short)16);w.Write(Encoding.ASCII.GetBytes("data"));w.Write(total*2);for(int n=0;n<notes.Length;n++){for(int i=0;i<toneSamples;i++){double envelope=Math.Min(1,Math.Min(i/(rate*.012),(toneSamples-i)/(rate*.025)));short sample=(short)(Math.Sin(2*Math.PI*notes[n]*i/rate)*9000*envelope);w.Write(sample);}if(n<notes.Length-1)for(int i=0;i<gapSamples;i++)w.Write((short)0);}}stream.Position=0;return stream;}
  void BeginSoftTone(){PlaySound(false);}
  void CloseNotice(){if(notice!=null&&!notice.IsDisposed)notice.Close();notice=null;noticeKind="";}
  bool showStageSummary; void BuildHistory(){
   var page=Page("按日期回看");var root=UI.Table(1,50,42,150,48,-100);page.Controls.Add(root);
   from=new DateTimePicker{Format=DateTimePickerFormat.Short,Width=145,Margin=new Padding(4,8,4,4)};to=new DateTimePicker{Format=DateTimePickerFormat.Short,Width=145,Margin=new Padding(4,8,4,4)};
   var between=UI.Label("至",9);between.Dock=DockStyle.None;between.Size=new Size(22,36);
   root.Controls.Add(UI.Flow(from,between,to,UI.Button("今天",()=>{from.Value=DateTime.Today;to.Value=DateTime.Today;RefreshHistory();}),UI.Button("最近 7 天",()=>{from.Value=DateTime.Today.AddDays(-6);to.Value=DateTime.Today;RefreshHistory();}),UI.Button("子任务 / 项目统计",()=>{showStageSummary=!showStageSummary;RefreshHistory();}),UI.Button("导出 CSV",()=>ExportCsv())),0,0);
   total=UI.Label("",13,true);root.Controls.Add(total,0,1);summary=UI.Grid();summary.ReadOnly=true;summary.ScrollBars=ScrollBars.Horizontal;summary.Columns.Add("project","项目");summary.Columns.Add("duration","专注总时长");summary.Columns.Add("runs","计时次数");summary.Columns.Add("average","平均每次专注");summary.Columns[0].MinimumWidth=240;root.Controls.Add(summary,0,2);
    briefHistory=new RadioButton{Text="简略",Checked=true,AutoSize=true,Margin=new Padding(8)};var detailHistory=new RadioButton{Text="详细",AutoSize=true,Margin=new Padding(8)};var queryProject=UI.Button("🔍",()=>ShowProjectDetails());queryProject.Name="QueryProjectDetails";queryProject.AccessibleName="查询项目明细";queryProject.AutoSize=false;queryProject.MinimumSize=new Size(44,34);queryProject.Size=new Size(44,34);queryProject.Padding=new Padding(0);queryProject.Margin=new Padding(12,4,4,4);root.Controls.Add(UI.Flow(briefHistory,detailHistory,queryProject),0,3);records=UI.Grid();records.ReadOnly=true;records.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;records.ScrollBars=ScrollBars.Both;records.Columns.Add("day","日期");records.Columns.Add("project","项目");records.Columns.Add("mode","模式");records.Columns.Add("start","开始");records.Columns.Add("end","结束");records.Columns.Add("duration","时长");records.Columns.Add("outcome","状态");records.Columns.Add("stage","子任务（该段时长）");records.Columns.Add("stageNote","子任务备注");foreach(string key in new[]{"day","mode","start","end","duration"})records.Columns[key].AutoSizeMode=DataGridViewAutoSizeColumnMode.AllCells;records.Columns["project"].MinimumWidth=140;records.Columns["stage"].MinimumWidth=150;records.Columns["stageNote"].MinimumWidth=220;records.Columns["outcome"].MinimumWidth=130;root.Controls.Add(records,0,4);records.Columns["start"].Visible=false;records.Columns["end"].Visible=false;records.Columns["outcome"].Visible=false;records.Columns["stageNote"].Visible=false;briefHistory.CheckedChanged+=(s,e)=>{records.Columns["start"].Visible=!briefHistory.Checked;records.Columns["end"].Visible=!briefHistory.Checked;records.Columns["outcome"].Visible=!briefHistory.Checked;records.Columns["stageNote"].Visible=!briefHistory.Checked;};
   detailHistory.CheckedChanged+=(s,e)=>RefreshHistory();from.ValueChanged+=(s,e)=>RefreshHistory();to.ValueChanged+=(s,e)=>RefreshHistory();
  }
  List<TimeRecord> Range(){string a=from.Value.Date.ToString("yyyy-MM-dd"),b=to.Value.Date.ToString("yyyy-MM-dd");return data.Records.Where(r=>String.CompareOrdinal(r.Day,a)>=0&&String.CompareOrdinal(r.Day,b)<=0).ToList();}
  string ProjectName(TimeRecord r){var p=data.Projects.FirstOrDefault(x=>x.Id==r.ProjectId);return p==null?r.ProjectName:p.Name;}
  void RefreshHistory(){if(summary==null)return;summary.Rows.Clear();records.Rows.Clear();if(from.Value.Date>to.Value.Date){total.Text="开始日期不能晚于结束日期。";return;}var rows=Range();total.Text="这段时间投入了 "+FocusEngine.Duration(rows.Sum(r=>r.Seconds))+"    ·    "+rows.Select(r=>r.ProjectId).Distinct().Count()+" 个项目";
   foreach(var group in rows.GroupBy(r=>r.ProjectId).OrderByDescending(g=>g.Sum(r=>r.Seconds)))summary.Rows.Add(ProjectName(group.First()),FocusEngine.Duration(group.Sum(r=>r.Seconds)),group.Select(r=>String.IsNullOrEmpty(r.SessionId)?r.RunId:r.SessionId).Distinct().Count(),FocusEngine.Duration(group.Sum(r=>r.Seconds)/Math.Max(1,group.Select(r=>String.IsNullOrEmpty(r.SessionId)?r.RunId:r.SessionId).Distinct().Count())));
   if(showStageSummary){summary.Rows.Clear();foreach(var group in rows.Where(r=>!String.IsNullOrEmpty(r.StageId)).GroupBy(r=>r.ProjectId+"|"+r.StageId).OrderByDescending(g=>g.Sum(r=>r.Seconds)))summary.Rows.Add(ProjectName(group.First())+" / "+group.First().StageName,FocusEngine.Duration(group.Sum(r=>r.Seconds)),group.Select(r=>String.IsNullOrEmpty(r.SessionId)?r.RunId:r.SessionId).Distinct().Count(),FocusEngine.Duration(group.Sum(r=>r.Seconds)/Math.Max(1,group.Select(r=>String.IsNullOrEmpty(r.SessionId)?r.RunId:r.SessionId).Distinct().Count())));}if(briefHistory.Checked){foreach(var group in rows.GroupBy(r=>r.Day+"|"+r.ProjectId+"|"+r.StageId).OrderByDescending(g=>g.Max(r=>r.StartUtc))){var r=group.First();records.Rows.Add(r.Day,ProjectName(r),group.Any(x=>x.Challenge)?"极限挑战":"番茄钟","","",FocusEngine.Duration(group.Sum(x=>x.Seconds)),"",String.IsNullOrEmpty(r.StageName)?"—":r.StageName,"");}}else foreach(var r in rows.OrderByDescending(r=>r.StartUtc))records.Rows.Add(r.Day,ProjectName(r),r.Challenge?"极限挑战":"番茄钟",r.StartUtc.ToLocalTime().ToString("HH:mm:ss"),r.EndUtc.ToLocalTime().ToString("HH:mm:ss"),FocusEngine.Duration(r.Seconds),r.Outcome,String.IsNullOrEmpty(r.StageName)?"—":r.StageName,String.IsNullOrEmpty(r.StageNote)?"—":r.StageNote);
  }
  static string Csv(string s){if(!String.IsNullOrEmpty(s)&&"=+-@\t\r".Contains(s[0]))s="'"+s;return "\""+(s??"").Replace("\"","\"\"")+"\"";}
  void ExportCsv(){using(var d=new SaveFileDialog{Filter="CSV 表格|*.csv",FileName="专注记录-"+from.Value.ToString("yyyyMMdd")+"-"+to.Value.ToString("yyyyMMdd")+".csv"}){if(d.ShowDialog(this)!=DialogResult.OK)return;try{var b=new StringBuilder("日期,项目,模式,开始,结束,专注秒数,时长,状态,子任务,子任务备注\r\n");foreach(var r in Range())b.AppendLine(String.Join(",",new[]{Csv(r.Day),Csv(ProjectName(r)),Csv(r.Challenge?"极限挑战":"番茄钟"),Csv(r.StartUtc.ToLocalTime().ToString("HH:mm:ss")),Csv(r.EndUtc.ToLocalTime().ToString("HH:mm:ss")),((long)r.Seconds).ToString(),Csv(FocusEngine.Duration(r.Seconds)),Csv(r.Outcome),Csv(r.StageName),Csv(r.StageNote)}));File.WriteAllText(d.FileName,b.ToString(),new UTF8Encoding(true));status.Text="已导出所选日期范围的 CSV。";}catch(Exception){MessageBox.Show(this,"导出失败，请检查目标文件是否被占用或目录是否可写。");}}}
  string breakKey="";Task<BreakContent> breakReply;List<string> restLines=new List<string>();string restLineKey="";int restLineAdvance;CancellationTokenSource breakCancel;
  async void QueueBreakEncouragement(Notice target){if(target==null||target.IsDisposed||!target.Visible||!api.Enabled||(!TaskSupport.EncouragementEnabled(data,"break")&&!data.MiniAiRest))return;string key=engine.RunId;if(key!=breakKey){if(breakCancel!=null)breakCancel.Cancel();breakKey=key;breakReply=null;}if(breakReply==null){breakCancel=new CancellationTokenSource();breakReply=Planner.BreakMessages(api,data.EncouragementPrompt,EncouragementContext("break"),breakCancel.Token,data.EncouragementPersona,data.MiniAiRest);}var pending=breakReply;try{BreakContent result=await pending;if(!closing&&!IsDisposed&&breakKey==key){if(result.Lines.Count>0){restLines=result.Lines;restLineKey=key;data.AiRestLines=(data.AiRestLines??new List<string>()).Concat(result.Lines).Where(x=>!String.IsNullOrWhiteSpace(x)).Select(x=>x.Trim()).Distinct().Take(500).ToList();data.AiRestGeneratedUtc=DateTime.UtcNow;Save();}if(!target.IsDisposed&&target.Visible)target.AddEncouragement(result.Encouragement);}}catch(OperationCanceledException){}catch(Exception){if(!closing)status.Text="AI 鼓励未生成；本轮不自动重试，计时不受影响。";}}
  string RestLine(){if(engine.State!=Phase.Break)return "( ˘ω˘ )";if(data.AiRestClearDays>0&&data.AiRestGeneratedUtc!=DateTime.MinValue&&(DateTime.UtcNow-data.AiRestGeneratedUtc).TotalDays>=data.AiRestClearDays){data.AiRestLines=new List<string>();data.AiRestGeneratedUtc=DateTime.MinValue;Save();}if(restLineKey!=engine.RunId){restLineKey=engine.RunId;restLineAdvance=0;var custom=(data.MiniRestLines??"").Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0);restLines=custom.Concat(data.AiRestLines??new List<string>()).Distinct().OrderBy(x=>random.Next()).ToList();}if(restLines.Count==0)return "( ˘ω˘ )";int interval=Math.Max(5,data.RestLineSeconds);int index=(int)Math.Max(0,(300-engine.BreakSeconds(DateTime.UtcNow))/interval)+restLineAdvance;return restLines[index%restLines.Count];}
  void NextRestLine(){if(engine.State!=Phase.Break)return;restLineAdvance++;RefreshDisplay();}
  bool encouraging;
  string EncouragementContext(string trigger,double? sessionSeconds=null){string day=DateTime.Now.ToString("yyyy-MM-dd");return "触发状态："+(trigger=="break"?"刚进入休息或正在等待休息确认，请支持离开座位；不要写剩余时间或声称已经开始休息，不催促继续工作":trigger=="timer-end"?"本次计时已结束":trigger=="task-complete"?"刚完成任务":"手动请求鼓励")+"；当地时间："+DateTime.Now.ToString("HH:mm")+"；今日专注："+FocusEngine.Duration(data.Records.Where(r=>r.Day==day).Sum(r=>r.Seconds))+"；本次实际专注："+FocusEngine.Duration(sessionSeconds??engine.SessionSeconds)+"；今日完成任务数："+data.Projects.Count(p=>p.Completed&&p.UpdatedUtc.ToLocalTime().Date==DateTime.Today);}
  async void QueueEncouragement(string trigger,Notice target,double? sessionSeconds=null){if(target==null||target.IsDisposed||!target.Visible||!api.Enabled||!TaskSupport.EncouragementEnabled(data,trigger))return;using(var cancel=new CancellationTokenSource()){FormClosedEventHandler closed=(s,e)=>cancel.Cancel();target.FormClosed+=closed;try{string result=await Planner.Encourage(api,data.EncouragementPrompt,EncouragementContext(trigger,sessionSeconds),cancel.Token,data.EncouragementPersona);if(!IsDisposed&&!closing&&!target.IsDisposed&&!cancel.IsCancellationRequested)target.AddEncouragement(result);}catch(OperationCanceledException){}catch(Exception){if(!IsDisposed&&!closing)status.Text="AI 鼓励暂未生成；提醒与计时不受影响，请检查 API 配置。";}finally{target.FormClosed-=closed;}}}
  async Task Encourage(){if(encouraging)return;encouraging=true;status.Text="正在生成今日鼓励…";try{string result=await Planner.Encourage(api,data.EncouragementPrompt,EncouragementContext("manual"),CancellationToken.None,data.EncouragementPersona);if(!IsDisposed&&!closing){status.Text="今日鼓励已生成";if(notice==null||notice.IsDisposed)ShowNotice("给今天的你",result,"encouragement",Pair("收下这句鼓励",null));else notice.AddEncouragement(result);}}catch(Exception){if(!IsDisposed)status.Text="鼓励暂未生成，请检查 API 配置、网络和额度；计时不受影响。";}finally{encouraging=false;}}
  void BuildSettings(){
    var page=Page("设置与休息活动");page.AutoScroll=true;var root=UI.Table(1,34,48,50,34,50,50,40,46,52,-100,45);root.MinimumSize=new Size(800,600);page.Controls.Add(root);
    root.Controls.Add(UI.Label("计时与反馈",12,true),0,0);
    var mins=new NumericUpDown{Minimum=1,Maximum=240,Value=data.FocusMinutes,Width=70,Margin=new Padding(6,8,8,4)};var text=UI.Label("番茄钟专注分钟",10,true);text.Dock=DockStyle.None;text.Size=new Size(140,38);var sound=new CheckBox{Text="提示音",Checked=data.Sound,AutoSize=true,Margin=new Padding(24,10,8,4)};var quiet=new CheckBox{Text="低刺激显示",Checked=data.LowStimulus,AutoSize=true,Margin=new Padding(12,10,4,4)};quiet.CheckedChanged+=(s,e)=>{data.LowStimulus=quiet.Checked;Save();RefreshDisplay();};var rewards=new CheckBox{Text="显示轻量奖励",Checked=data.Rewards,AutoSize=true,Margin=new Padding(20,10,8,4)};
    root.Controls.Add(UI.Flow(text,mins,sound,rewards,quiet,UI.Button("测试提醒",()=>ShowNotice("提醒测试","这是程序自己的置顶弹窗，不依赖浏览器通知权限。\n正式计时到点时，也会显示这样的提醒。","test",Pair("知道了",null)))),0,1);
    mins.ValueChanged+=(s,e)=>{data.FocusMinutes=(int)mins.Value;Save();RefreshDisplay();};sound.CheckedChanged+=(s,e)=>{data.Sound=sound.Checked;Save();};rewards.CheckedChanged+=(s,e)=>{data.Rewards=rewards.Checked;Save();RefreshDisplay();};
    var soundPreset=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=110,Font=UI.Font(9),Margin=new Padding(4,7,4,4)};soundPreset.Items.AddRange(new object[]{"短双音","柔和单音","上扬三音"});soundPreset.SelectedItem=String.IsNullOrWhiteSpace(data.SoundPreset)?"短双音":data.SoundPreset;if(soundPreset.SelectedIndex<0)soundPreset.SelectedIndex=0;var soundPath=UI.TextBox();soundPath.ReadOnly=true;soundPath.Width=200;soundPath.Text=data.SoundPath??"";root.Controls.Add(UI.Flow(UI.Label("提示音效",9),soundPreset,soundPath,UI.Button("导入 MP3/WAV",()=>{using(var f=new OpenFileDialog{Filter="音频文件|*.mp3;*.wav|MP3 音频|*.mp3|WAV 音频|*.wav",Title="选择提示音效"})if(f.ShowDialog(this)==DialogResult.OK){data.SoundPath=f.FileName;soundPath.Text=f.FileName;Save();}}),UI.Button("使用内置",()=>{data.SoundPath="";soundPath.Text="";Save();}),UI.Button("试听",()=>PlaySound(true))),0,2);soundPreset.SelectedIndexChanged+=(s,e)=>{data.SoundPreset=Convert.ToString(soundPreset.SelectedItem);data.SoundPath="";soundPath.Text="";Save();};
    var moreHeading=UI.Label("更多设置 · 需要时再打开",11,true);moreHeading.ForeColor=UI.Muted;root.Controls.Add(moreHeading,0,3);
    var systemRows=UI.Table(1,46,46);systemRows.Controls.Add(UI.Flow(UI.Button("配置 AI API",()=>{using(var d=new ApiDialog(api,store.DirectoryPath))d.ShowDialog(this);}),UI.Button("数据管理",()=>ShowDataManagement()),UI.Button("同步",()=>{using(var d=new SyncDialog(sync,store.DirectoryPath))d.ShowDialog(this);})),0,0);root.RowStyles[4].Height=92;root.Controls.Add(systemRows,0,4);
    var legacy=UI.Flow(UI.Button("导出全部数据",()=>Backup()),UI.Button("导入并合并",()=>Restore()),UI.Button("数据文件夹",()=>OpenFolder()),UI.Button("运行日志",()=>{using(var d=new RuntimeLogDialog(data,()=>{Save();}))d.ShowDialog(this);}),UI.Button("同步设置",()=>{using(var d=new SyncDialog(sync,store.DirectoryPath))d.ShowDialog(this);}),UI.Button("立即同步",async()=>await SyncNow(false)),UI.Button("收藏的宝藏",()=>ShowFavorites()));legacy.Visible=false;root.Controls.Add(legacy,0,3);
    root.Controls.Add(UI.Flow(UI.Button("项目与程序设置",()=>{using(var d=new ProjectDefaultsDialog(data)){if(d.ShowDialog(this)==DialogResult.OK){Save();status.Text=data.CloseToTray?"关闭主窗口时将收进托盘。":"关闭主窗口时将退出软件。";}}}),UI.Button("接续卡 AI",()=>{using(var d=new SupportSettingsDialog(data)){if(d.ShowDialog(this)==DialogResult.OK)Save();}}),UI.Button("AI 鼓励",()=>{using(var d=new EncouragementDialog(data)){if(d.ShowDialog(this)==DialogResult.OK)Save();}}),UI.Button("休息个性化",()=>{using(var dialog=new MiniSettingsDialog(data)){if(dialog.ShowDialog(this)==DialogResult.OK){restLineKey="";Save();RefreshDisplay();}}}),UI.Button("个性化探索",()=>ShowDistractionSettings()),UI.Button("审视自我",()=>ShowDistractionLog())),0,5);
    root.Controls.Add(UI.Label("休息活动",13,true),0,6);var use=new CheckBox{Text="随机使用内置活动（走动、接水、远眺等）",Checked=data.UseBuiltins,Dock=DockStyle.Fill};use.CheckedChanged+=(s,e)=>{data.UseBuiltins=use.Checked;Save();};root.Controls.Add(use,0,7);
    root.Controls.Add(UI.Flow(UI.Button("查看内置活动",()=>{using(var d=new BuiltInActivitiesDialog(builtins))d.ShowDialog(this);}),UI.Button("＋ 自定义活动",()=>AddIdea()),UI.Button("移除选中活动",()=>{if(ideas.SelectedIndex<0)return;var item=visibleIdeas[ideas.SelectedIndex];item.Deleted=true;item.UpdatedUtc=DateTime.UtcNow;RefreshIdeas();Save();}),UI.Button("换个休息建议",()=>{PickActivity();RefreshDisplay();})),0,8);
    ideas=new CheckedListBox{Dock=DockStyle.Fill,Font=UI.Font(13),MinimumSize=new Size(0,155),CheckOnClick=true,BorderStyle=BorderStyle.None,IntegralHeight=false};ideas.ItemCheck+=(s,e)=>{if(updating)return;var item=visibleIdeas[e.Index];item.Enabled=e.NewValue==CheckState.Checked;item.UpdatedUtc=DateTime.UtcNow;BeginInvoke(new Action(()=>Save()));};root.Controls.Add(ideas,0,9);
    syncStatus=UI.Label("",8.5f);syncStatus.Visible=false;root.Controls.Add(syncStatus,0,10);RefreshIdeas();
  }
  void AddIdea(){using(var f=new Form()){UI.FormStyle(f,"添加休息活动",490,290);f.Padding=new Padding(18);var root=UI.Table(1,28,38,28,90,50);var title=UI.TextBox();title.MaxLength=80;var desc=UI.TextBox(true);desc.MaxLength=500;root.Controls.Add(UI.Label("活动名称"),0,0);root.Controls.Add(title,0,1);root.Controls.Add(UI.Label("怎么做（5 分钟内）"),0,2);root.Controls.Add(desc,0,3);root.Controls.Add(UI.Flow(UI.Button("添加",()=>{if(String.IsNullOrWhiteSpace(title.Text))return;data.Ideas.Add(new BreakIdea{Name=title.Text.Trim(),Detail=desc.Text.Trim()});Save();RefreshIdeas();f.Close();},true)),0,4);f.Controls.Add(root);f.ShowDialog(this);}}
  void RefreshIdeas(){if(ideas==null)return;updating=true;ideas.Items.Clear();visibleIdeas=data.Ideas.Where(i=>!i.Deleted).ToList();foreach(var i in visibleIdeas)ideas.Items.Add(i,i.Enabled);updating=false;}
  void PickActivity(){var pool=(data.UseBuiltins?builtins:new List<BreakIdea>()).Concat(data.Ideas.Where(i=>i.Enabled&&!i.Deleted)).ToList();if(pool.Count==0)pool.Add(new BreakIdea{Name="起身走动 5 分钟",Detail="活动库为空，先离开座位，按舒服的节奏走一走。"});var different=pool.Where(i=>activity==null||i.Name!=activity.Name).ToList();if(different.Count>0)pool=different;activity=pool[random.Next(pool.Count)];}
  void Backup(){if(!Save())return;using(var d=new SaveFileDialog{Filter="本地备份|*.xml",FileName="专注小站备份-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".xml"}){if(d.ShowDialog(this)!=DialogResult.OK)return;try{if(Path.GetFullPath(d.FileName).Equals(Path.GetFullPath(store.FilePath),StringComparison.OrdinalIgnoreCase))return;File.Copy(store.FilePath,d.FileName,true);status.Text="数据备份已导出（不含 API 密钥）。";}catch(Exception){MessageBox.Show(this,"备份失败，请换一个可写位置。");}}}
  void Restore(){if(engine.State!=Phase.Idle||syncing){MessageBox.Show(this,"请先结束当前计时或等待同步完成，再导入数据。");return;}using(var d=new OpenFileDialog{Filter="本地备份|*.xml"}){if(d.ShowDialog(this)!=DialogResult.OK)return;try{var incoming=Store.Read(d.FileName);if(!Save())return;PreMergeBackup();ApplyMerged(DataMerge.Merge(data,incoming));MessageBox.Show(this,"导入完成，重复记录已去重。导入前的数据也已备份。","历史记录已合并");}catch(Exception){MessageBox.Show(this,"无法导入：文件格式无效或数据目录不可写。原文件保留在本机。");}}}
  void PreMergeBackup(){if(File.Exists(store.FilePath))File.Copy(store.FilePath,Path.Combine(store.DirectoryPath,"合并前-"+DateTime.Now.ToString("yyyyMMdd-HHmmss-fff")+".xml"),false);}
  void ApplyMerged(AppData merged){string selected=Selected()==null?null:Selected().Id;store.Save(merged);data=merged;engine=new FocusEngine(data);RefreshProjects(selected);RefreshIdeas();RefreshHistory();RefreshDisplay();Save();}
  async Task SyncNow(bool automatic){
   if(syncing)return;nextSync=DateTime.UtcNow.AddMinutes(5);if(engine.State!=Phase.Idle){if(!automatic)MessageBox.Show(this,"请先结束当前计时，再同步。自动同步会在空闲时进行。");return;}if(String.IsNullOrWhiteSpace(sync.Url)){if(!automatic)MessageBox.Show(this,"请先打开“同步设置”，填写 WebDAV 地址和账号。");return;}if(!Save())return;
   syncing=true;syncStatus.Text="正在同步：先下载并合并，再安全上传……";syncCancel=new CancellationTokenSource();
   try{var merged=await WebDavSync.Run(sync,()=>Store.Decode(Store.Encode(data)),syncCancel.Token);if(IsDisposed||closing)return;PreMergeBackup();ApplyMerged(DataMerge.Merge(data,merged));syncStatus.Text="同步完成 "+DateTime.Now.ToString("HH:mm:ss")+" · 重复记录已去重，断网仍可使用。";}
   catch(OperationCanceledException){if(!IsDisposed)syncStatus.Text="同步取消或超时，本地记录保留。";}
   catch(Exception ex){if(!IsDisposed)syncStatus.Text=ex is InvalidOperationException?ex.Message:"同步失败，请检查网络、凭据和远端数据格式；本地数据保留。";}
   finally{syncing=false;if(syncCancel!=null){syncCancel.Dispose();syncCancel=null;}}
  }
  bool Save(){try{store.Save(data);savedAt=DateTime.UtcNow;saveError=false;status.Text="本地已保存 "+DateTime.Now.ToString("HH:mm:ss")+" · 最小化进托盘；关闭窗口退出";status.ForeColor=UI.Muted;return true;}catch(Exception){savedAt=DateTime.UtcNow;status.Text="保存失败：数据目录不可写或磁盘空间不足。请勿关闭程序。";status.ForeColor=Color.Firebrick;if(!saveError){saveError=true;ShowNotice("数据暂时无法保存","请检查数据目录和磁盘空间。当前计时仍在内存中，请暂时不要关闭程序。","save-error",Pair("知道了",null));}return false;}}
  void OpenFolder(){try{Directory.CreateDirectory(store.DirectoryPath);Process.Start(new ProcessStartInfo("explorer.exe","\""+store.DirectoryPath+"\""){UseShellExecute=true});}catch(Exception){MessageBox.Show(this,store.DirectoryPath,"数据目录");}}
  void BuildTray(){tray=new NotifyIcon{Icon=Icon,Text=Brand.AppName+" · 种下一点进展",Visible=true};var menu=new ContextMenuStrip();menu.Items.Add("打开专注小站",null,(s,e)=>ShowMain());menu.Items.Add("迷你计时条",null,(s,e)=>ShowMini());menu.Items.Add("暂停 / 继续",null,(s,e)=>PauseResume());menu.Items.Add("结束本次计时",null,(s,e)=>EndFocus("手动结束"));menu.Items.Add("完成当前任务",null,(s,e)=>CompleteTask());menu.Items.Add("退出程序",null,(s,e)=>{exitRequested=true;Close();});tray.ContextMenuStrip=menu;tray.DoubleClick+=(s,e)=>ShowMain();}
  void FinishMiniStep(){var p=DisplayProject();if(p==null)return;var stage=p.Stages.FirstOrDefault(x=>!x.Done);if(stage==null)return;if(engine.IsChallenge&&engine.Current==p){double saved=engine.PlannedStageRemaining(stage);engine.Pause(DateTime.UtcNow);stage.Done=true;p.SmallStep="";p.UpdatedUtc=DateTime.UtcNow;Save();RefreshSubtasks();RefreshDisplay();ChallengeEarly(stage,saved);return;}HandleEvent(engine.Tick(DateTime.UtcNow));undoProject=p;undoStage=stage;undoSmall=p.SmallStep;p.SmallStep="";stage.Done=true;if(engine.Current==p)engine.RefreshStageDeadline();p.UpdatedUtc=DateTime.UtcNow;Save();RefreshSubtasks();RefreshDisplay();} void ShowMini(){if(mini==null||mini.IsDisposed)mini=new MiniTimer(()=>{if(engine.State==Phase.Idle||engine.State==Phase.Ready)StartSelected();else if(engine.State==Phase.Break)EarlyFocus();else PauseResume();},()=>ShowMain(),()=>EndFocus("手动结束"),()=>CompleteTask(),()=>BeginBreak(),()=>FinishMiniStep(),()=>ShowDistraction(),()=>WithdrawLastStage(),()=>NextRestLine());if(mini.WindowState==FormWindowState.Minimized)mini.WindowState=FormWindowState.Normal;mini.Show();var miniArea=Screen.FromControl(mini).WorkingArea;mini.Location=new Point(Math.Max(miniArea.Left,Math.Min(mini.Left,miniArea.Right-mini.Width)),Math.Max(miniArea.Top,Math.Min(mini.Top,miniArea.Bottom-mini.Height)));mini.Activate();RefreshDisplay();Hide();}
  public void ShowMain(){Show();WindowState=FormWindowState.Normal;Activate();if(mini!=null&&!mini.IsDisposed)mini.Show();}
  void PowerChanged(object sender,PowerModeChangedEventArgs e){if(e.Mode==PowerModes.Suspend&&IsHandleCreated&&!IsDisposed){try{Invoke(new Action(()=>{if(engine.State==Phase.Focus){engine.Pause(DateTime.UtcNow);Save();RefreshDisplay();}}));}catch(InvalidOperationException){}}}
  void SessionChanged(object sender,SessionSwitchEventArgs e){if(e.Reason==SessionSwitchReason.SessionLock&&IsHandleCreated&&!IsDisposed){try{BeginInvoke(new Action(()=>{if(engine.State==Phase.Focus){engine.Pause(DateTime.UtcNow);Save();RefreshDisplay();}}));}catch(InvalidOperationException){}}}
  void OnClosing(object sender,FormClosingEventArgs e){if(closing)return;if(e.CloseReason==CloseReason.UserClosing&&data.CloseToTray&&!exitRequested){e.Cancel=true;Hide();status.Text="已收进托盘；计时和提醒继续运行。";return;}if(distractionCancel!=null)distractionCancel.Cancel();if(engine.State!=Phase.Idle)TaskSupport.Remember(engine.Current);bool focused=engine.State==Phase.Focus||engine.State==Phase.Paused;if(engine.State!=Phase.Idle)engine.Stop(DateTime.UtcNow,"退出程序");if(!Save()){e.Cancel=true;return;}closing=true;if(breakCancel!=null)breakCancel.Cancel();timer.Stop();CloseNotice();if(mini!=null&&!mini.IsDisposed)mini.Close();if(syncCancel!=null)syncCancel.Cancel();if(focused&&e.CloseReason==CloseReason.UserClosing){using(var n=new Notice("专注结束，记录已保存",(engine.Current==null?"":engine.Current.Name)+"\n本轮 "+FocusEngine.Duration(engine.RunSeconds)+"\n\n程序退出后不再计时。",Pair("退出程序",null)))n.ShowDialog();}SystemEvents.PowerModeChanged-=PowerChanged;SystemEvents.SessionSwitch-=SessionChanged;tray.Visible=false;tray.Dispose();timer.Dispose();}
  [DllImport("user32.dll",CharSet=CharSet.Auto)]static extern bool DestroyIcon(IntPtr handle);
  static Icon SeedIcon(){using(var image=new Bitmap(32,32))using(var g=Graphics.FromImage(image)){g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;g.Clear(Color.Transparent);using(var stem=new Pen(Color.FromArgb(53,89,65),3)){g.DrawCurve(stem,new[]{new Point(16,28),new Point(15,21),new Point(17,14)});}using(var leaf=new SolidBrush(Color.FromArgb(91,132,73))){g.FillEllipse(leaf,new Rectangle(7,10,11,8));g.FillEllipse(leaf,new Rectangle(16,6,10,9));}using(var seed=new SolidBrush(Color.FromArgb(174,122,62)))g.FillEllipse(seed,new Rectangle(12,20,8,9));IntPtr h=image.GetHicon();try{using(var icon=Icon.FromHandle(h))return (Icon)icon.Clone();}finally{DestroyIcon(h);}}}
 }
}





















