using System;
using System.Drawing;using System.Collections.Generic;using System.Linq;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
namespace LittleFocus {
 public class MiniActionButton:Button {
  public string Kind="play";
  protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;float s=Math.Min(Width,Height)/28f;var old=g.Save();g.TranslateTransform((Width-28*s)/2,(Height-28*s)/2);g.ScaleTransform(s,s);Color color=ForeColor;using(var pen=new Pen(color,1.8f))using(var brush=new SolidBrush(color)){if(Kind=="pause"){g.FillRectangle(brush,8,7,4,14);g.FillRectangle(brush,16,7,4,14);}else if(Kind=="play")g.FillPolygon(brush,new[]{new PointF(9,6),new PointF(22,14),new PointF(9,22)});else if(Kind=="rest"){g.DrawRectangle(pen,5,10,14,11);g.DrawArc(pen,16,11,8,8,-90,180);g.DrawLine(pen,8,4,8,7);g.DrawLine(pen,14,4,14,7);}else if(Kind=="undo"){g.DrawArc(pen,7,7,14,14,205,235);g.FillPolygon(brush,new[]{new PointF(5,10),new PointF(12,9),new PointF(8,15)});}else if(Kind=="bulb"){g.DrawEllipse(pen,8,5,12,13);g.DrawLine(pen,11,20,17,20);g.DrawLine(pen,11,23,17,23);g.DrawLine(pen,14,1,14,4);g.DrawLine(pen,4,8,7,9);g.DrawLine(pen,21,9,24,8);}else if(Kind=="lock"||Kind=="unlock"){g.DrawRectangle(pen,7,12,14,11);g.DrawArc(pen,9,4,10,13,Kind=="lock"?180:210,Kind=="lock"?180:130);g.DrawLine(pen,14,16,14,20);}else if(Kind=="close"){g.DrawLine(pen,8,8,20,20);g.DrawLine(pen,20,8,8,20);}else{g.DrawRectangle(pen,6,7,16,14);g.DrawLine(pen,6,11,22,11);}}g.Restore(old);}
 }
 public class RestTicker:Label {
  public bool Scrolling;public float Offset;
  protected override void OnPaint(PaintEventArgs e){if(!Scrolling){base.OnPaint(e);return;}int width=TextRenderer.MeasureText(Text,Font,new Size(Int32.MaxValue,Height),TextFormatFlags.SingleLine|TextFormatFlags.NoPadding).Width;if(width<=Width){base.OnPaint(e);return;}int x=-(int)(Offset%(width+35));TextRenderer.DrawText(e.Graphics,Text,Font,new Rectangle(x,0,width+10,Height),ForeColor,TextFormatFlags.SingleLine|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding|TextFormatFlags.NoPrefix);TextRenderer.DrawText(e.Graphics,Text,Font,new Rectangle(x+width+35,0,width+10,Height),ForeColor,TextFormatFlags.SingleLine|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding|TextFormatFlags.NoPrefix);}
 }
 public class MiniTimer:Form {
  Label task,countdown,phase;RestTicker elapsed;int dimPercent=25;string restText="( ˘ω˘ )";List<Stage> pathStages=new List<Stage>();MiniActionButton toggle,rest,open,distract,withdraw,lockButton,closeButton;CheckBox stageCheck;bool locked,hasStage,canWithdrawState;double baseOpacity=1,targetOpacity=1;bool clickThrough;readonly Timer hoverTimer=new Timer{Interval=150},fadeTimer=new Timer{Interval=30};
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern int GetWindowLong(IntPtr hWnd,int nIndex);
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern int SetWindowLong(IntPtr hWnd,int nIndex,int value);
 const int GWL_EXSTYLE=-20,WS_EX_TRANSPARENT=0x20;Action distractAction,nextRestAction;ContextMenuStrip actionsMenu;ToolTip tips=new ToolTip();bool dragging;Point pointer,origin;Phase current;Panel motion=new Panel();bool animate=true,lowStimulus;double motionPhase;readonly Timer animation=new Timer{Interval=50};
  public MiniTimer(Action toggleAction,Action openMain,Action end,Action complete,Action beginRest=null,Action finishStage=null,Action distractCallback=null,Action withdrawStage=null,Action nextRest=null){
   UI.FormStyle(this,Brand.AppName+" · 迷你计时条",460,110);MinimumSize=new Size(460,110);FormBorderStyle=FormBorderStyle.None;TopMost=true;ShowInTaskbar=false;StartPosition=FormStartPosition.Manual;Padding=new Padding(8,18,8,8);BackColor=UI.Soft;DoubleBuffered=true;nextRestAction=nextRest;
   motion.Dock=DockStyle.Fill;motion.Paint+=(s,e)=>{var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;if(pathStages.Count>0&&current!=Phase.Break){int left=12,right=Math.Max(left+1,motion.Width-12),ground=motion.Height-3;using(var trunk=new Pen(Color.FromArgb(105,115,80),2)){g.DrawLine(trunk,motion.Width/2,ground,motion.Width/2,3);}using(var branch=new Pen(Color.FromArgb(133,145,102),1)){g.DrawLine(branch,motion.Width/2,ground/2,left,ground/2);g.DrawLine(branch,motion.Width/2,ground/2,right,ground/2);}for(int i=0;i<pathStages.Count;i++){int x=pathStages.Count==1?motion.Width/2:left+(right-left)*i/Math.Max(1,pathStages.Count-1);int y=3+(i%2)*5;using(var b=new SolidBrush(pathStages[i].Done?UI.Green:(i==pathStages.FindIndex(q=>!q.Done)?Color.FromArgb(232,169,67):Color.White)))using(var p=new Pen(UI.Green,1)){g.FillEllipse(b,x-4,y-4,8,8);g.DrawEllipse(p,x-4,y-4,8,8);}}}else{using(var brush=new SolidBrush(current==Phase.Break?UI.Purple:UI.Green)){double x=(Math.Sin(motionPhase)+1)/2;int width=Math.Max(20,motion.Width/6);g.FillRectangle(brush,(int)(x*(motion.Width-width)),motion.Height-2,width,2);}}};;animation.Tick+=(s,e)=>{if(Visible){if(!lowStimulus){motionPhase+=current==Phase.Break?0.023:0.035;motion.Invalidate();}if(current==Phase.Break||hasStage){elapsed.Offset+=0.45f;elapsed.Invalidate();}}};
   var root=UI.Table(8,-100,16);root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,150));for(int i=0;i<6;i++)root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,30));
   var names=UI.Table(1,24,-100);task=UI.Label("未选择任务",9,true);phase=UI.Label("准备开始",8);task.Margin=phase.Margin=new Padding(2,0,2,0);phase.ForeColor=UI.Muted;names.Controls.Add(task,0,0);names.Controls.Add(phase,0,1);root.Controls.Add(names,0,0);
   var clocks=UI.Table(1,30,-100);clocks.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));countdown=UI.Label("25:00",17,true);countdown.Name="MiniCountdown";countdown.Margin=new Padding(0);countdown.TextAlign=ContentAlignment.MiddleCenter;elapsed=new RestTicker{Text="本次 00:00:00",Font=UI.Font(8.5f),Dock=DockStyle.Fill,ForeColor=UI.Ink,Cursor=Cursors.Hand};elapsed.Name="MiniSessionTime";elapsed.Margin=new Padding(2,0,2,0);elapsed.TextAlign=ContentAlignment.MiddleCenter;elapsed.Click+=(s,e)=>{if(current==Phase.Break&&nextRestAction!=null)nextRestAction();};tips.SetToolTip(elapsed,"休息时点击换一句");clocks.Controls.Add(countdown,0,0);stageCheck=new CheckBox{Name="MiniStageDone",Dock=DockStyle.Left,Width=18,Visible=false,AutoCheck=false};stageCheck.Click+=(s,e)=>{if(!locked&&finishStage!=null)finishStage();};var line=new Panel{Dock=DockStyle.Fill};line.Controls.Add(elapsed);line.Controls.Add(stageCheck);clocks.Controls.Add(line,0,1);root.Controls.Add(clocks,1,0);
   elapsed.MouseEnter+=(s,e)=>{if(current==Phase.Break)tips.SetToolTip(elapsed,null);};toggle=IconButton("MiniToggle","pause","暂停 / 继续",toggleAction);rest=IconButton("MiniRest","rest","直接开始休息",()=>{if(beginRest!=null)beginRest();});open=IconButton("MiniExpand","expand","展开主窗口",openMain);distractAction=distractCallback;distract=IconButton("MiniDistraction","bulb","分心一下",()=>{if(!locked&&distractAction!=null)distractAction();});distract.Visible=false;withdraw=IconButton("MiniWithdraw","undo","撤回最近完成的子任务",()=>{if(!locked&&withdrawStage!=null)withdrawStage();});withdraw.Visible=false;root.Controls.Add(withdraw,2,0);root.Controls.Add(toggle,3,0);root.Controls.Add(rest,4,0);root.Controls.Add(open,5,0);root.Controls.Add(distract,6,0);lockButton=IconButton("MiniLock","unlock","锁定操作 / 再点解锁",()=>{locked=!locked;dragging=false;ApplyLock();});root.Controls.Add(lockButton,7,0);closeButton=IconButton("MiniClose","close","隐藏迷你计时条（托盘点一下可再打开）",()=>Hide());closeButton.ForeColor=UI.Muted;closeButton.Dock=DockStyle.None;closeButton.Size=new Size(22,14);closeButton.Margin=new Padding(0);closeButton.Anchor=AnchorStyles.Top|AnchorStyles.Right;closeButton.Size=new Size(24,16);Controls.Add(root);Controls.Add(closeButton);closeButton.BringToFront();root.Controls.Add(motion,0,1);root.SetColumnSpan(motion,8);SizeChanged+=(s,e)=>{closeButton.Location=new Point(Width-closeButton.Width-14,2);};
   foreach(Control c in new Control[]{this,root,names,clocks,task,phase,countdown,elapsed}){c.MouseDown+=DragStart;c.MouseMove+=DragMove;c.MouseUp+=DragEnd;}
   var menu=new ContextMenuStrip();actionsMenu=menu;menu.Opening+=(s,e)=>e.Cancel=locked;var opacity=new ToolStripMenuItem("透明度");foreach(int percent in new[]{100,90,80,70,60}){int value=percent;var item=new ToolStripMenuItem(percent+"%"){Checked=percent==100};item.Click+=(s,e)=>{baseOpacity=value/100.0;targetOpacity=baseOpacity;fadeTimer.Enabled=false;Opacity=baseOpacity;foreach(ToolStripMenuItem other in opacity.DropDownItems)other.Checked=other==item;};opacity.DropDownItems.Add(item);}menu.Items.Add(opacity);var effect=new ToolStripMenuItem("缓慢流动效果"){Checked=true,CheckOnClick=true};effect.CheckedChanged+=(s,e)=>{animate=effect.Checked;ConfigureAnimation();ApplyLock();};menu.Items.Add(effect);var pin=menu.Items.Add("取消置顶");pin.Click+=(s,e)=>{TopMost=!TopMost;pin.Text=TopMost?"取消置顶":"保持置顶";};menu.Items.Add("结束本次计时",null,(s,e)=>end());menu.Items.Add("完成当前任务",null,(s,e)=>complete());menu.Items.Add("展开主窗口",null,(s,e)=>openMain());menu.Items.Add("隐藏计时条",null,(s,e)=>Hide());foreach(Control c in new Control[]{this,root,names,clocks,task,phase,countdown,elapsed})c.ContextMenuStrip=menu;hoverTimer.Tick+=(s,e)=>{if(Visible)CheckHover();};fadeTimer.Tick+=(s,e)=>FadeTick();
   SizeChanged+=(s,e)=>ArrangeAccent();Shown+=(s,e)=>{ArrangeAccent();closeButton.Location=new Point(Width-closeButton.Width-14,2);var area=Screen.FromControl(this).WorkingArea;Location=new Point(area.Right-Width-20,area.Bottom-Height-20);};
  }
  MiniActionButton IconButton(string name,string kind,string hint,Action action){var b=new MiniActionButton{Name=name,Kind=kind,AccessibleName=hint,Dock=DockStyle.Fill,FlatStyle=FlatStyle.Flat,ForeColor=UI.Green,BackColor=UI.Soft,Margin=new Padding(1,4,1,4),Padding=new Padding(0),Text=""};b.FlatAppearance.BorderSize=0;b.Click+=(s,e)=>action();tips.SetToolTip(b,hint);return b;}
   public void UpdateState(string name,string value,string status,Phase state,double sessionSeconds=0,bool canBreak=true,Stage stage=null,string countdownHint=null,bool canDistraction=false,bool canWithdraw=false){current=state;Color theme=state==Phase.Break?Color.FromArgb(238,231,246):state==Phase.Paused?Color.FromArgb(241,235,223):UI.Soft;BackColor=theme;foreach(Control c in Controls)Theme(c,theme);task.Text=name;countdown.Text=value;hasStage=stage!=null&&state!=Phase.Break&&state!=Phase.Ready;canWithdrawState=canWithdraw;elapsed.Scrolling=state==Phase.Break||hasStage;string line=state==Phase.Break?restText:hasStage?stage.Title:"本次 "+FocusEngine.Duration(sessionSeconds);if(elapsed.Text!=line){elapsed.Text=line;elapsed.Offset=0;}elapsed.AutoEllipsis=false;stageCheck.Visible=hasStage;distract.Visible=canDistraction&&(state==Phase.Focus||state==Phase.Paused);withdraw.Visible=canWithdraw&&state!=Phase.Break&&state!=Phase.Idle;tips.SetToolTip(countdown,countdownHint??("本次 "+FocusEngine.Duration(sessionSeconds)+"（不含暂停和休息）"));tips.SetToolTip(elapsed,hasStage?(String.IsNullOrWhiteSpace(stage.Action)?stage.Title:stage.Action):state==Phase.Break?restText:"本次实际专注时长");countdown.ForeColor=state==Phase.Break?UI.Purple:UI.Green;phase.Text=state==Phase.Focus?(status.Contains("已到")?"等待休息确认":status.Contains("极限")?"挑战中":"专注中"):state==Phase.Paused?"已暂停":state==Phase.Break?"休息中":state==Phase.Ready?"休息结束":"准备开始";toggle.Kind=state==Phase.Focus?"pause":"play";string action=state==Phase.Focus?"暂停计时":state==Phase.Break?"提前专注":"继续 / 开始计时";toggle.AccessibleName=action;tips.SetToolTip(toggle,action);toggle.Enabled=name!="未选择任务";toggle.Invalidate();rest.Visible=canBreak&&(state==Phase.Focus||state==Phase.Paused);rest.Enabled=canBreak&&(state==Phase.Focus||state==Phase.Paused);tips.SetToolTip(task,name+"\n拖动移动；右键调透明度");ConfigureAnimation();ApplyLock();}
  public void SetPreferences(int dim,string text){dimPercent=Math.Max(0,Math.Min(100,dim));restText=String.IsNullOrWhiteSpace(text)?"( ˘ω˘ )":text;} public void SetStages(IEnumerable<Stage> value){pathStages=value==null?new List<Stage>():value.ToList();motion.Invalidate();ConfigureAnimation();} Color Fade(Color color){double a=locked?dimPercent/100.0:1;return Color.FromArgb((int)(color.R*a+BackColor.R*(1-a)),(int)(color.G*a+BackColor.G*(1-a)),(int)(color.B*a+BackColor.B*(1-a)));} void ApplyLock(){closeButton.Visible=!locked;if(!locked){hoverTimer.Enabled=false;if(clickThrough){SetClickThrough(false);clickThrough=false;}FadeTo(baseOpacity);}else{FadeTo(1);hoverTimer.Enabled=true;}toggle.Enabled=!locked&&task.Text!="未选择任务";rest.Enabled=!locked&&rest.Visible;open.Enabled=!locked;distract.Enabled=!locked&&distract.Visible;withdraw.Enabled=!locked&&withdraw.Visible;stageCheck.Enabled=!locked&&hasStage;lockButton.Kind=locked?"lock":"unlock";lockButton.Invalidate();tips.Active=!locked;task.AutoEllipsis=!locked;task.Font=UI.Font(locked?10:9,true);countdown.Font=UI.Font(locked?20:17,true);elapsed.Font=UI.Font(locked?10.5f:8.5f,locked);task.ForeColor=Fade(UI.Ink);phase.ForeColor=Fade(UI.Muted);toggle.ForeColor=rest.ForeColor=open.ForeColor=distract.ForeColor=withdraw.ForeColor=Fade(UI.Green);elapsed.ForeColor=hasStage||current==Phase.Break?UI.Ink:Fade(UI.Ink);stageCheck.Visible=hasStage&&!locked;motion.Visible=!lowStimulus;toggle.Invalidate();rest.Invalidate();open.Invalidate();distract.Invalidate();withdraw.Invalidate();elapsed.Invalidate();tips.SetToolTip(lockButton,locked?"已锁定，点击解锁":"锁定：禁用操作与拖动");} void Theme(Control c,Color color){c.BackColor=color;foreach(Control child in c.Controls)Theme(child,color);}
  void ConfigureAnimation(){bool motionRunning=animate&&!lowStimulus&&(current==Phase.Focus||current==Phase.Break)&&pathStages.Count==0;bool tickerRunning=current==Phase.Break&&elapsed.Scrolling;animation.Enabled=motionRunning||tickerRunning;motion.Visible=!lowStimulus;if(!motionRunning)motion.Invalidate();}
  void SetClickThrough(bool on){int ex=GetWindowLong(Handle,GWL_EXSTYLE);SetWindowLong(Handle,GWL_EXSTYLE,on?ex|WS_EX_TRANSPARENT:ex&~WS_EX_TRANSPARENT);}
  void CheckHover(){CheckHover(Cursor.Position);}
  public void CheckHover(Point screenPos){if(!locked)return;var p=PointToClient(screenPos);bool inside=ClientRectangle.Contains(p);bool overLock=lockButton.Bounds.Contains(p);if(inside&&!overLock){if(!clickThrough){SetClickThrough(true);clickThrough=true;}FadeTo(0.1);}else if(clickThrough){SetClickThrough(false);clickThrough=false;FadeTo(baseOpacity);}}
  void FadeTo(double target){targetOpacity=target;if(Math.Abs((double)Opacity-target)<0.01)return;fadeTimer.Enabled=false;fadeTimer.Enabled=true;}
  void FadeTick(){double current=(double)Opacity;double next=current+(targetOpacity-current)*0.28;if(Math.Abs(next-targetOpacity)<0.02){next=targetOpacity;fadeTimer.Enabled=false;}Opacity=next;}
  public void SetLowStimulus(bool value){lowStimulus=value;ConfigureAnimation();ApplyLock();}
  void ArrangeAccent(){int r=14;using(var path=new GraphicsPath()){path.AddArc(0,0,r,r,180,90);path.AddArc(Width-r,0,r,r,270,90);path.AddArc(Width-r,Height-r,r,r,0,90);path.AddArc(0,Height-r,r,r,90,90);path.CloseFigure();var old=Region;Region=new Region(path);if(old!=null)old.Dispose();}}
  void DragStart(object sender,MouseEventArgs e){if(locked||e.Button!=MouseButtons.Left)return;dragging=true;pointer=Cursor.Position;origin=Location;((Control)sender).Capture=true;}
  void DragMove(object sender,MouseEventArgs e){if(dragging){Point p=Cursor.Position;Location=new Point(origin.X+p.X-pointer.X,origin.Y+p.Y-pointer.Y);}}
  void DragEnd(object sender,MouseEventArgs e){if(!dragging)return;dragging=false;((Control)sender).Capture=false;var area=Screen.FromControl(this).WorkingArea;Location=new Point(Math.Max(area.Left,Math.Min(Left,area.Right-Width)),Math.Max(area.Top,Math.Min(Top,area.Bottom-Height)));}
  protected override void Dispose(bool disposing){if(disposing){animation.Dispose();hoverTimer.Dispose();fadeTimer.Dispose();tips.Dispose();}base.Dispose(disposing);}
 }
}









