using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
namespace LittleFocus {
 public static class Tests {
  static int checks;
  static void Check(bool condition,string message){checks++;if(!condition)throw new Exception(message);}
  static void Equal(double a,double b,string message){Check(Math.Abs(a-b)<0.00001,message+" ("+a+" vs "+b+")");}
  static void Throws(Action action,string message){bool threw=false;try{action();}catch(Exception){threw=true;}Check(threw,message);}
  static DateTime Advance(FocusEngine e,DateTime t,int seconds){for(int i=0;i<seconds;i++){t=t.AddSeconds(1);e.Tick(t);}return t;}
  static void RuntimeLogChecks(){
   var t=DateTime.UtcNow;
   var d=new AppData{FocusMinutes=1};var p=new Project{Name="写稿"};d.Projects.Add(p);var e=new FocusEngine(d);
   Check(d.RuntimeEvents!=null,"runtime log initialised");
   e.Start(p,t);
   Check(d.RuntimeEvents.Count==1,"start writes one event");
   Check(d.RuntimeEvents[0].Name=="start"&&d.RuntimeEvents[0].ProjectId==p.Id,"start event carries project");
   t=t.AddSeconds(30);e.Pause(t);t=t.AddSeconds(5);e.Resume(t);t=t.AddSeconds(30);e.Stop(t,"结束");
   Check(d.RuntimeEvents.Count==4,"pause resume stop each write one event");
   Check(d.RuntimeEvents[1].Name=="pause"&&d.RuntimeEvents[2].Name=="resume"&&d.RuntimeEvents[3].Name=="stop","events stay in order");
   var segs=RuntimeLog.Segments(d);
   Check(segs.Count==1,"one focus segment");
   Equal(segs[0].Seconds,60,"segment duration excludes paused time");
   Check(segs[0].ProjectName=="写稿","segment resolves project name");
   var sum=RuntimeLog.Summary(d);
   Check(sum.Starts==1&&sum.Pauses==1&&sum.Resumes==1,"summary counts today's events");
   Check(sum.SegmentCount==1&&sum.Headline.Contains("今天启动了 1 次"),"summary headline reflects the day");
   var csv=RuntimeLog.Csv(d);
   Check(csv.StartsWith("时间,事件,任务,状态,专注时长,说明"),"csv header");
   Check(csv.Split('\n').Length>=5,"csv has one line per event plus header");
   Check(csv.Contains("开始计时")&&csv.Contains("结束计时"),"csv uses readable event names");
   Check(RuntimeLog.NameText("start")=="开始计时","known event names are translated");
   Check(RuntimeLog.NameText("nope")=="nope","unknown event names pass through instead of becoming 其他");
   Check(RuntimeLog.NameText("")=="其他"&&RuntimeLog.NameText(null)=="其他","blank event names fall back");
   Check(RuntimeLog.ProjectName(d,p.Id)=="写稿","known project name");
   Check(RuntimeLog.ProjectName(d,"missing")=="（已删除的任务）","missing project falls back");
   Check(RuntimeLog.ProjectName(d,"")=="","blank project id stays blank");
   RuntimeLog.Clear(d);
   Check(d.RuntimeEvents.Count==0&&RuntimeLog.Segments(d).Count==0,"clear empties log and segments");
   var big=new AppData();big.Projects.Add(new Project{Name="压力测试"});var bigEngine=new FocusEngine(big);
   for(int i=0;i<1100;i++){bigEngine.Start(big.Projects[0],t);bigEngine.Stop(t,"结束");}
   Check(big.RuntimeEvents.Count==RuntimeLog.Keep,"log is capped at Keep");
   Check(big.RuntimeEvents.Count==2000,"log keeps the newest 2000 events");
   Check(RuntimeLog.Ordered(big).Count==2000,"ordered view returns every kept event");
  }
  public static int Main(string[] args){try{SupportChecks();RuntimeLogChecks();Run(args.Length>0?args[0]:Path.Combine(Environment.CurrentDirectory,"work","tests"));Console.WriteLine("PASS: "+checks+" assertions. No live API credentials used.");return 0;}catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}
  static void Run(string dir){
   var sd=new AppData{FocusMinutes=1};var sp=new Project{Name="分段",Stages=Planner.Writing()};sd.Projects.Add(sp);var se=new FocusEngine(sd);var st=new DateTime(2026,9,1,12,0,0,DateTimeKind.Utc);se.Start(sp,st);se.Tick(st.AddSeconds(5));sp.Stages[0].Done=true;se.RefreshStageDeadline();Check(se.Tick(st.AddSeconds(20))=="due","next subtask uses its own deadline");Equal(sd.Records.Where(x=>x.StageId==sp.Stages[0].Id).Sum(x=>x.Seconds),5,"early finished subtask duration");Equal(sd.Records.Where(x=>x.StageId==sp.Stages[1].Id).Sum(x=>x.Seconds),6,"second subtask duration capped at allocation");se.Stop(st.AddSeconds(20),"结束");var copied=Store.Decode(Store.Encode(sd));Check(copied.Records[0].StageId==sp.Stages[0].Id,"subtask log roundtrip");sp.Deleted=true;sp.UpdatedUtc=DateTime.UtcNow.AddSeconds(1);var merge=DataMerge.Merge(copied,sd);Check(merge.Projects[0].Deleted&&merge.Records.Count==0,"deletion sync purges historical records");
   var fast=new ApiConfig{Endpoint="https://api.deepseek.com/chat/completions",Model="deepseek-v4-flash"};Check(Planner.RequestJson(fast,Planner.Payload(sp,fast)).Contains("\"thinking\":{\"type\":\"disabled\"}"),"official DeepSeek thinking disabled");fast.EconomyMode=false;Check(!Planner.RequestJson(fast,Planner.Payload(sp,fast)).Contains("thinking"),"thinking opt-out preserved");fast.EconomyMode=true;fast.Endpoint="https://example.com/chat/completions";Check(!Planner.RequestJson(fast,Planner.Payload(sp,fast)).Contains("thinking"),"no foreign provider thinking parameter");Check(Planner.SupportPolicy.Length<500,"compact skill rules budget");
   var p=new Project{Name="写稿",NextStep="给用户写一篇说明",AiEnabled=true};Check(!new Project().AiEnabled,"legacy AI flag defaults off");var d=new AppData{FocusMinutes=1};d.Projects.Add(p);var e=new FocusEngine(d);DateTime t=new DateTime(2026,8,31,12,0,0,DateTimeKind.Utc);e.Start(p,t);t=Advance(e,t,59);Check(e.State==Phase.Focus,"before deadline focus");t=t.AddSeconds(1);Check(e.Tick(t)=="due","due reminder");Check(e.State==Phase.Paused,"deadline pauses until confirmed");t=Advance(e,t,42);Equal(e.RunSeconds,60,"waiting excluded");Equal(d.Records.Sum(r=>r.Seconds),60,"waiting not logged");e.Snooze();e.Resume(t);t=Advance(e,t,299);Check(!e.ReminderSent,"snooze waits");t=t.AddSeconds(1);Check(e.Tick(t)=="due","snooze reminder");Check(e.BeginBreak(t),"manual break");Check(e.State==Phase.Break,"break state");Equal(e.RunSeconds,360,"full focus before break");Check(d.Records.Sum(r=>r.Tomatoes)==1,"award once");t=Advance(e,t,299);Check(e.State==Phase.Break,"full 5 minute break");t=t.AddSeconds(1);Check(e.Tick(t)=="break-end","break-end reminder");Check(e.State==Phase.Ready,"await manual resume");t=Advance(e,t,60);Equal(d.Records.Sum(r=>r.Seconds),360,"rest/ready excluded");e.Start(p,t);t=Advance(e,t,20);e.Pause(t);t=Advance(e,t,500);Equal(e.RunSeconds,20,"pause excluded");e.Resume(t);t=Advance(e,t,15);e.Stop(t,"手动结束");Equal(e.RunSeconds,35,"stop retains partial");Check(e.State==Phase.Idle,"stop idle");
   e.Start(p,t);t=Advance(e,t,10);t=t.AddHours(8);Check(e.Tick(t)=="interrupted","suspension detected");Equal(e.RunSeconds,10,"sleep not counted");Check(e.State==Phase.Paused,"sleep pauses");
   var midnight=DateTime.SpecifyKind(new DateTime(2026,9,1,0,0,0),DateTimeKind.Local).ToUniversalTime();d=new AppData();e=new FocusEngine(d);e.Start(p,midnight.AddSeconds(-30));e.Tick(midnight.AddSeconds(30));Check(d.Records.Count==2,"split midnight");Equal(d.Records[0].Seconds,30,"day one");Equal(d.Records[1].Seconds,30,"day two");Check(d.Records[0].Day=="2026-08-31"&&d.Records[1].Day=="2026-09-01","local day keys");
   d=new AppData();e=new FocusEngine(d);t=DateTime.UtcNow.AddTicks(123);e.Start(p,t);for(int i=0;i<100;i++){t=t.AddTicks(5123456);e.Tick(t);}Check(d.Records.Count==1,"continuous submillisecond spans merge");
   p.Challenge=true;p.ChallengeMinutes=2;p.Stages=new List<Stage>{new Stage{Remaining=100,Title="开始"},new Stage{Remaining=90,Title="方向"},new Stage{Remaining=70,Title="推进"},new Stage{Remaining=10,Title="收尾"}};d=new AppData();e=new FocusEngine(d);e.Start(p,t);t=Advance(e,t,11);t=t.AddSeconds(1);Check(e.Tick(t)=="stage","first allocation boundary");Check(e.Reached[0].Title=="开始","first stage reaches its own end");p.Stages[0].Done=true;Check(e.BeginBreak(t),"challenge permits a manual break");Check(e.EndBreakEarly(t),"challenge resumes after break");t=Advance(e,t,23);t=t.AddSeconds(1);Check(e.Tick(t)=="stage","second allocation boundary");p.Stages[1].Done=true;e.Resume(t);t=t.AddSeconds(84);Check(e.Tick(t)=="challenge-end","challenge deadline event");Check(e.State==Phase.Paused,"challenge deadline pauses");e.FinishChallenge("测试结束");Equal(e.RunSeconds,120,"challenge excludes late callback overshoot");Equal(d.Records.Sum(r=>r.Seconds),120,"exact challenge record");Check(e.State==Phase.Idle,"challenge ends");Check(d.Records.Sum(r=>r.Tomatoes)==1,"challenge star");e.Tick(t.AddMinutes(1));Equal(e.RunSeconds,120,"ended no extra time");
   var overtimeProject=new Project{Name="不限加时",Challenge=true,ChallengeMinutes=1,Stages=new List<Stage>{new Stage{Remaining=100,Title="未完成"}}};var overtimeEngine=new FocusEngine(new AppData());overtimeEngine.Start(overtimeProject,DateTime.UtcNow);Check(overtimeEngine.AddChallengeTime(1)&&overtimeEngine.AddChallengeTime(1)&&overtimeEngine.AddChallengeTime(1),"unfinished challenge stage allows repeated overtime");var screenshotData=new AppData();var screenshotProject=new Project{Name="游戏测评框架",Challenge=true,ChallengeMinutes=120,Stages=new List<Stage>{new Stage{Remaining=100,Title="写2000字"}}};screenshotData.Projects.Add(screenshotProject);var screenshotEngine=new FocusEngine(screenshotData);var screenshotNow=DateTime.UtcNow;screenshotEngine.Start(screenshotProject,screenshotNow);Check(screenshotEngine.AddChallengeTime(30),"screenshot scenario accepts 30-minute overtime");Equal(screenshotEngine.StageRemaining(),1800,"30-minute overtime remains 30 minutes");
   var continuedProject=new Project{Name="继续挑战",Challenge=true,ChallengeMinutes=10,Stages=new List<Stage>{new Stage{Id="done",Remaining=100,Title="已完成",Done=true},new Stage{Id="current",Remaining=60,Title="继续这里"},new Stage{Id="later",Remaining=20,Title="之后"}}};var continuedData=new AppData{FocusMinutes=1};continuedData.Records.Add(new TimeRecord{ProjectId=continuedProject.Id,StageId="current",Seconds=30});var continuedEngine=new FocusEngine(continuedData);var continuedAt=DateTime.UtcNow;continuedEngine.Start(continuedProject,continuedAt);Check(continuedEngine.CurrentStage().Id=="current","challenge starts at first unfinished stage by id");Equal(continuedEngine.StageRemaining(),210,"historical stage time reduces current allocation");Equal(continuedEngine.ChallengeTotalRemaining(),330,"completed share and historical time reduce total remaining");continuedAt=Advance(continuedEngine,continuedAt,60);Check(continuedEngine.State==Phase.Paused,"global pomodoro interval pauses challenge");continuedEngine.SkipChallengeBreak(continuedAt);Check(continuedEngine.State==Phase.Focus,"challenge may continue without taking break");
   var shiftedProject=new Project{Name="顺延节点",Challenge=true,ChallengeMinutes=2,Stages=new List<Stage>{new Stage{Remaining=100,Title="第一段"},new Stage{Remaining=50,Title="第二段"},new Stage{Remaining=25,Title="收尾"}}};var shiftedEngine=new FocusEngine(new AppData());var shiftedAt=DateTime.UtcNow;shiftedEngine.Start(shiftedProject,shiftedAt);shiftedAt=Advance(shiftedEngine,shiftedAt,60);Check(shiftedEngine.State==Phase.Paused,"first planned boundary pauses");Check(shiftedEngine.AddChallengeTime(1),"first stage can enter overtime");shiftedEngine.Resume(shiftedAt);shiftedAt=Advance(shiftedEngine,shiftedAt,30);shiftedProject.Stages[0].Done=true;shiftedEngine.CompleteOvertimeStage();shiftedEngine.Resume(shiftedAt);shiftedAt=Advance(shiftedEngine,shiftedAt,29);Check(shiftedEngine.State==Phase.Focus,"used overtime shifts later stage boundary");shiftedAt=Advance(shiftedEngine,shiftedAt,1);Check(shiftedEngine.State==Phase.Paused&&shiftedEngine.Reached.Any(x=>x.Title=="第二段"),"later stage keeps original proportional duration after shift");Equal(shiftedEngine.ChallengeTotalRemaining(),30,"challenge end shifts by used overtime");
   Check(Planner.Validate(Planner.Writing())==null,"writing template valid");Check(Planner.Writing().Count==5,"writing five phases");Check(Planner.Validate(new List<Stage>{new Stage{Remaining=100,Title="a"},new Stage{Remaining=100,Title="b"}})!=null,"duplicate milestones rejected");var durationProject=new Project{PomodoroMinutes=0,Stages=new List<Stage>{new Stage{Remaining=100,Title="第一步"},new Stage{Remaining=60,Title="第二步"},new Stage{Remaining=20,Title="第三步"}}};Equal(TaskSupport.StageSeconds(durationProject,durationProject.Stages[0],new AppData{FocusMinutes=50}),1200,"stage duration inherits global pomodoro minutes");durationProject.Challenge=true;durationProject.ChallengeMinutes=100;Equal(TaskSupport.StageSeconds(durationProject,durationProject.Stages[1],new AppData()),2400,"stage duration follows challenge total and percentages");
   durationProject.Stages[1].AllocatedSeconds=900;Equal(TaskSupport.StageSeconds(durationProject,durationProject.Stages[1],new AppData()),900,"exact edited stage duration is preserved");Check(new AppData().DistractionTopic==""&&!new AppData().DistractionUseProjectName,"personalization defaults blank and project association off");Check(Planner.RequestJson(new ApiConfig{Model="test"},Planner.FreshPayload(new ApiConfig{Model="test"},"",300,"读一本书")).Contains("围绕当前项目名称"),"blank personalization falls back to project name");var fresh=Planner.ParseFresh("说明文字\n{\"kind\":\"personalized\",\"title\":\"标题\",\"body\":\"正文\",\"sourceUrl\":\"\"}\n结束",300);Check(fresh.Title=="标题"&&fresh.Body=="正文","fresh parser extracts JSON from surrounding text");bool friendlyFresh=false;try{Planner.ParseFresh("{\"title\":\"未终止",300);}catch(InvalidDataException ex){friendlyFresh=ex.Message.Contains("格式不完整")&&!ex.Message.Contains("未终止的字符串");}Check(friendlyFresh,"malformed fresh response uses a friendly fixed error");
   var planJson="{\"stages\":[{\"remaining\":100,\"title\":\"准备\",\"action\":\"第一步\"},{\"remaining\":70,\"title\":\"执行\",\"action\":\"第二步\"}]}";
   Check(Planner.Parse("```json\n"+planJson+"\n```").Count==2,"fenced JSON parser");Throws(()=>Planner.Parse(planJson.Replace(":70",":70.5")),"fraction rejected");Throws(()=>Planner.Parse("{}"),"bad schema rejected");Throws(()=>Planner.Endpoint("http://example.com/api"),"remote HTTP rejected");Throws(()=>Planner.Endpoint("https://key:secret@example.com/api"),"URL user info rejected");Throws(()=>Planner.Endpoint("https://example.com/api?key=secret"),"query rejected");Check(Planner.Endpoint("http://127.0.0.1:1234/v1/chat/completions").IsLoopback,"local HTTP allowed");
   Directory.CreateDirectory(dir);var store=new Store(Path.Combine(dir,"data-"+Guid.NewGuid().ToString("N")));d.Projects.Add(p);p.AiEnabled=false;store.Save(d);var loaded=store.Load();Check(!loaded.Projects[0].AiEnabled,"AI opt-out saved");Check(loaded.Projects[0].Stages.Count==4,"subtasks persisted");Equal(loaded.Records.Sum(r=>r.Seconds),120,"records round trip");store.Save(d);File.WriteAllText(store.FilePath,"damaged");loaded=store.Load();Check(loaded.Projects.Count==1&&!String.IsNullOrEmpty(store.Warning),"backup recovered");Check(Directory.GetFiles(store.DirectoryPath,"*.damaged-*").Length==1,"damaged preserved");
   var api=new ApiConfig{Model="test-model"};api.SetKey("not-a-real-key-test-only");Check(api.ProtectedKey!="not-a-real-key-test-only","secret encrypted");Check(api.GetKey()=="not-a-real-key-test-only","secret decrypts");api.Save(store.DirectoryPath);Check(!File.ReadAllText(Path.Combine(store.DirectoryPath,"api.xml")).Contains("not-a-real-key-test-only"),"no plaintext secret on disk");Check(!File.ReadAllText(store.FilePath+".bak").Contains("ProtectedKey"),"backup excludes credentials");
   ApiRoundTrip(p,planJson).GetAwaiter().GetResult();
   var remote=Store.Decode(Store.Encode(d));remote.Projects[0].Name="远端改名";remote.Projects[0].UpdatedUtc=DateTime.UtcNow.AddSeconds(1);var merged=DataMerge.Merge(d,remote);Check(merged.Projects[0].Name=="远端改名","newest project wins");Equal(merged.Records.Sum(r=>r.Seconds),120,"merge deduplicates time");merged=DataMerge.Merge(merged,remote);Check(merged.Records.Count==d.Records.Count,"repeated import idempotent");var idea=new BreakIdea{Name="测试活动"};d.Ideas.Add(idea);remote=Store.Decode(Store.Encode(d));remote.Ideas[0].Deleted=true;remote.Ideas[0].UpdatedUtc=DateTime.UtcNow.AddSeconds(1);merged=DataMerge.Merge(d,remote);Check(merged.Ideas[0].Deleted,"removed activities do not resurrect");
   SyncRoundTrip(d).GetAwaiter().GetResult();
   var completeData=new AppData();var completeProject=new Project{Name="待完成任务",Enabled=false};completeData.Projects.Add(completeProject);var completeEngine=new FocusEngine(completeData);var started=DateTime.UtcNow;completeEngine.Start(completeProject,started);completeEngine.Tick(started.AddSeconds(27));completeEngine.Complete(completeProject,started.AddSeconds(30));Check(completeProject.Completed,"complete marks task");Check(completeEngine.State==Phase.Idle,"complete stops timer");Equal(completeData.Records.Sum(r=>r.Seconds),30,"complete saves all focus time");Check(completeData.Records.All(r=>r.Outcome=="任务完成"),"complete record outcome");completeEngine.Complete(completeProject,started.AddSeconds(80));Equal(completeData.Records.Sum(r=>r.Seconds),30,"repeat complete adds no time");
  }
  static void SupportChecks(){
   Check(Planner.SupportPolicy.Length<3500,"runtime policy avoids sending two full skills");Check(typeof(Planner).Assembly.GetManifestResourceNames().Contains("LittleFocus.PrimaryAdhdPolicy"),"primary skill source bundled");Check(new JavaScriptSerializer().Serialize(Planner.Payload(new Project{Name="任务"},new ApiConfig{Model="mock"})).Contains("i-have-adhd"),"task decomposition uses shared skills");var legacy=new AppData{AutoResumeSuggestions=true,EncouragementPersona="温和、克制的陪伴者；具体认可投入，不催促、不夸大。",EncouragementPrompt="用温和、具体的中文鼓励我，认可已经投入的时间，不催促、不比较。最多三句话。"};var upgraded=Store.Decode(Store.Encode(legacy));Check(!upgraded.AutoResumeSuggestions&&upgraded.AiPreferencesRevision==1,"upgrade turns off existing auto resume");Check(upgraded.EncouragementPersona==AiDefaults.Persona&&upgraded.EncouragementPrompt==AiDefaults.Prompt,"old stock prompts upgraded");upgraded.AutoResumeSuggestions=true;upgraded.EncouragementPersona="我的自定义人格";var reopened=Store.Decode(Store.Encode(upgraded));Check(reopened.AutoResumeSuggestions&&reopened.EncouragementPersona=="我的自定义人格","later explicit opt-in and custom persona preserved");
   Check(Planner.SupportPolicy.Contains("i-have-adhd")&&Planner.SupportPolicy.Contains("adhd-friendly-skill"),"primary and secondary runtime rules embedded");string wholeTaskPayload=new JavaScriptSerializer().Serialize(Planner.Payload(new Project{Name="读一本书"},new ApiConfig{Model="mock"}));Check(wholeTaskPayload.Contains("整件事")&&wholeTaskPayload.Contains("读完整本书")&&wholeTaskPayload.Contains("不能把任务范围偷换"),"task decomposition preserves the whole-task boundary");var prefs=new AppData{AutoEncouragement=true,EncourageOnBreak=true,EncourageOnTimerEnd=false,EncourageOnTaskComplete=true,SupportHabits="先写草稿",EncouragementPersona="安静的伙伴"};Check(TaskSupport.EncouragementEnabled(prefs,"break")&&!TaskSupport.EncouragementEnabled(prefs,"timer-end")&&TaskSupport.EncouragementEnabled(prefs,"task-complete"),"independent encouragement event switches");prefs.AutoEncouragement=false;Check(!TaskSupport.EncouragementEnabled(prefs,"break"),"master encouragement switch");var prefsCopy=Store.Decode(Store.Encode(prefs));Check(prefsCopy.EncouragementPersona==prefs.EncouragementPersona&&prefsCopy.SupportHabits==prefs.SupportHabits&&!prefsCopy.EncourageOnTimerEnd,"persona habits and triggers persist");Check(Planner.ParseResume("{\"resumeNote\":\"建议：打开草稿\",\"nextStep\":\"写一句话\",\"doneWhen\":\"保存初稿\"}")[1]=="写一句话","resume response parser");bool rejected=false;try{Planner.ParseResume("{\"nextStep\":\"\"}");}catch(Exception){rejected=true;}Check(rejected,"invalid resume response rejected");
   var p=new Project{Name="文章",Stages=Planner.Writing(),DoneWhen="保存一篇可读的初稿",ResumeNote="正文第二段，文件在桌面"};Check(TaskSupport.Next(p)==p.Stages[0].Action,"next unfinished stage visible");p.SmallStep="只打开文档";Check(TaskSupport.Next(p)=="只打开文档","smaller step takes priority");TaskSupport.Remember(p);Check(p.LastCheckpoint.Contains("只打开文档"),"checkpoint preserves restart action");var data=new AppData{LowStimulus=true,LastProjectId=p.Id};data.Projects.Add(p);var loaded=Store.Decode(Store.Encode(data));Check(loaded.LowStimulus&&loaded.LastProjectId==p.Id,"support preferences survive restart");Check(loaded.Projects[0].ResumeNote==p.ResumeNote&&loaded.Projects[0].DoneWhen==p.DoneWhen&&loaded.Projects[0].SmallStep==p.SmallStep,"resume card round trip");var merged=DataMerge.Merge(loaded,new AppData());Check(merged.Projects[0].LastCheckpoint==p.LastCheckpoint,"merge preserves checkpoint");p.SmallStep="";p.Stages[0].Done=true;Check(TaskSupport.Next(p)==p.Stages[1].Action,"next stage advances");p.Completed=true;Check(TaskSupport.Next(p).Contains("已经完成"),"completed task does not pressure restart");var old=Store.Encode(new AppData());old=old.Replace("<LowStimulus>false</LowStimulus>","").Replace("<LastProjectId />","");Check(!Store.Decode(old).LowStimulus,"missing new settings keep defaults");
  }
  static async Task ApiRoundTrip(Project p,string planJson){
   var probe=new TcpListener(IPAddress.Loopback,0);probe.Start();int port=((IPEndPoint)probe.LocalEndpoint).Port;probe.Stop();
   using(var server=new HttpListener()){string prefix="http://127.0.0.1:"+port+"/";server.Prefixes.Add(prefix);server.Start();
    var request=server.GetContextAsync();var config=new ApiConfig{Endpoint=prefix+"v1/chat/completions",Model="test-model"};
    using(var timeout=new CancellationTokenSource(10000)){
     var result=Planner.Generate(p,config,timeout.Token);var arrived=await Task.WhenAny(request,Task.Delay(10000));if(arrived!=request)throw new Exception("Mock API did not receive request");var context=await request;string body;using(var reader=new StreamReader(context.Request.InputStream))body=await reader.ReadToEndAsync();var json=new JavaScriptSerializer();var payload=json.DeserializeObject(body) as Dictionary<string,object>;Check((string)payload["model"]=="test-model","API model transmitted");Check(!payload.ContainsKey("Records")&&!body.Contains("ProtectedKey"),"no history/credentials in payload");var response=json.Serialize(new{choices=new[]{new{message=new{content=planJson}}}});byte[] bytes=Encoding.UTF8.GetBytes(response);context.Response.StatusCode=200;context.Response.ContentType="application/json";context.Response.ContentLength64=bytes.Length;await context.Response.OutputStream.WriteAsync(bytes,0,bytes.Length);context.Response.Close();Check((await result).Count==2,"compatible API round trip");
    }
    Check((await Planner.Generate(p,config,CancellationToken.None)).Count==2,"identical breakdown reuses cache without server response");config.Model="test-denied";var denied=server.GetContextAsync();using(var timeout=new CancellationTokenSource(10000)){var result=Planner.Generate(p,config,timeout.Token);var context=await denied;context.Response.StatusCode=401;context.Response.Close();bool failed=false;try{await result;}catch(InvalidOperationException ex){failed=ex.Message.Contains("401");}Check(failed,"API errors understandable");Check(p.Name=="写稿"&&p.Stages.Count==4,"API failure preserves original task");}
    var encouragement=server.GetContextAsync();using(var timeout=new CancellationTokenSource(10000)){var result=Planner.Encourage(config,"温和具体","今日专注 00:20:00",timeout.Token,"安静的伙伴");var context=await encouragement;string body;using(var reader=new StreamReader(context.Request.InputStream))body=await reader.ReadToEndAsync();Check(body.Contains("温和具体")&&body.Contains("00:20:00")&&body.Contains("安静的伙伴"),"encouragement includes personality preferences and metrics");Check(!body.Contains("ProtectedKey")&&!body.Contains("Records"),"encouragement excludes private history");byte[] bytes=Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(new{choices=new[]{new{message=new{content="这二十分钟已经算数。"}}}}));context.Response.ContentLength64=bytes.Length;await context.Response.OutputStream.WriteAsync(bytes,0,bytes.Length);context.Response.Close();Check(await result=="这二十分钟已经算数。","encouragement compatible API response");}
    var resume=server.GetContextAsync();using(var timeout=new CancellationTokenSource(10000)){var history=new AppData{SupportHabits="先写草稿"};history.Records.Add(new TimeRecord{ProjectName="不应上传的其他任务",RunId="private-run",StartUtc=DateTime.UtcNow,Seconds=120});var result=Planner.ResumeSuggestions(p,history,config,timeout.Token);var context=await resume;string body;using(var reader=new StreamReader(context.Request.InputStream))body=await reader.ReadToEndAsync();Check(body.Contains("i-have-adhd")&&body.Contains("先写草稿")&&body.Contains("recent30Days"),"resume API receives skill habits and aggregates");Check(!body.Contains("不应上传的其他任务")&&!body.Contains("private-run"),"resume excludes raw history and unrelated projects");byte[] bytes=Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(new{choices=new[]{new{message=new{content="{\"resumeNote\":\"建议：看看草稿末尾\",\"nextStep\":\"写一句承接的话\",\"doneWhen\":\"保存一个段落\"}"}}}}));context.Response.ContentLength64=bytes.Length;await context.Response.OutputStream.WriteAsync(bytes,0,bytes.Length);context.Response.Close();Check((await result)[2]=="保存一个段落","resume compatible API round trip");}
   }
  }
  static async Task SyncRoundTrip(AppData d){
   var probe=new TcpListener(IPAddress.Loopback,0);probe.Start();int port=((IPEndPoint)probe.LocalEndpoint).Port;probe.Stop();
   using(var server=new HttpListener()){string prefix="http://127.0.0.1:"+port+"/";server.Prefixes.Add(prefix);server.Start();
    var config=new SyncConfig{Url=prefix+"focus-data.xml"};using(var timeout=new CancellationTokenSource(10000)){
     var request=server.GetContextAsync();var run=WebDavSync.Run(config,()=>d,timeout.Token);var get=await request;Check(get.Request.HttpMethod=="GET","sync downloads first");get.Response.StatusCode=404;get.Response.Close();var put=await server.GetContextAsync();Check(put.Request.Headers["If-None-Match"]=="*","new cloud file conditional creation");string body;using(var reader=new StreamReader(put.Request.InputStream))body=await reader.ReadToEndAsync();Check(!body.Contains("ProtectedPassword")&&!body.Contains("ProtectedKey"),"cloud excludes credentials");var parsed=Store.Decode(body);Equal(parsed.Records.Sum(r=>r.Seconds),120,"sync body readable");put.Response.StatusCode=201;put.Response.Close();Equal((await run).Records.Sum(r=>r.Seconds),120,"sync creation success");
    }
    using(var timeout=new CancellationTokenSource(10000)){
     var request=server.GetContextAsync();var run=WebDavSync.Run(config,()=>d,timeout.Token);var get=await request;get.Response.StatusCode=200;get.Response.Headers["ETag"]="\"v1\"";byte[] bytes=Encoding.UTF8.GetBytes(Store.Encode(d).Replace("utf-16","utf-8"));get.Response.ContentLength64=bytes.Length;await get.Response.OutputStream.WriteAsync(bytes,0,bytes.Length);get.Response.Close();var put=await server.GetContextAsync();Check(put.Request.Headers["If-Match"]=="\"v1\"","cloud update guarded by ETag");put.Response.StatusCode=412;put.Response.Close();var again=await server.GetContextAsync();Check(again.Request.HttpMethod=="GET","conflict triggers re-download");again.Response.StatusCode=200;again.Response.Headers["ETag"]="\"v2\"";again.Response.ContentLength64=bytes.Length;await again.Response.OutputStream.WriteAsync(bytes,0,bytes.Length);again.Response.Close();var retry=await server.GetContextAsync();Check(retry.Request.Headers["If-Match"]=="\"v2\"","retry uses latest version");retry.Response.StatusCode=204;retry.Response.Close();Check((await run).Records.Count==d.Records.Count,"conflict recovery no duplicate records");
    }
   }
  }
 }
}
