using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
namespace LittleFocus {
 public static class UiTests {
  static IEnumerable<Control> All(Control c){yield return c;foreach(Control child in c.Controls)foreach(var x in All(child))yield return x;}
  static void Layout(Control c){c.PerformLayout();foreach(Control child in c.Controls)Layout(child);}
  static void Check(bool ok,string text){if(!ok)throw new Exception(text);}
  static object Field(object o,string n){return o.GetType().GetField(n,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(o);}
  static void Call(object o,string n){o.GetType().GetMethod(n,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(o,null);}
  static void WaitFor(Func<bool> condition){DateTime end=DateTime.UtcNow.AddSeconds(8);while(!condition()){if(DateTime.UtcNow>end)throw new Exception("Timed out waiting for local API/UI");Application.DoEvents();System.Threading.Thread.Sleep(15);}}
  static void PumpBriefly(){DateTime end=DateTime.UtcNow.AddMilliseconds(350);while(DateTime.UtcNow<end){Application.DoEvents();System.Threading.Thread.Sleep(10);}}
  static void Respond(System.Threading.Tasks.Task<System.Net.HttpListenerContext> request,Notice notice,string expected,string reply){notice.Opacity=0;WaitFor(()=>request.IsCompleted);var ctx=request.Result;string body;using(var reader=new StreamReader(ctx.Request.InputStream))body=reader.ReadToEnd();Check(body.Contains(expected),"correct encouragement trigger: "+expected);byte[] bytes=System.Text.Encoding.UTF8.GetBytes(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(new{choices=new[]{new{message=new{content=reply}}}}));ctx.Response.ContentLength64=bytes.Length;ctx.Response.OutputStream.Write(bytes,0,bytes.Length);ctx.Response.Close();WaitFor(()=>notice.Detail.Text.Contains(reply));}
  static void Render(Form form,string file){form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-30000,-30000);form.ShowInTaskbar=false;form.Opacity=0;form.Show();Application.DoEvents();Layout(form);using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save(file);}Console.WriteLine(Path.GetFileName(file)+" DPI="+form.CurrentAutoScaleDimensions+" size="+form.Size);foreach(var label in All(form).OfType<Label>().Where(l=>l.Visible&&l.Font.Size>=14)){using(var g=label.CreateGraphics())Check(label.Height>=label.Font.GetHeight(g),"Clipped large label: "+label.Text+" height="+label.Height+" needed="+label.Font.GetHeight(g)+" font="+label.Font.Size);}foreach(var b in All(form).OfType<Button>().Where(b=>b.Visible&&b.Parent is FlowLayoutPanel))Check(b.Bottom<=b.Parent.ClientSize.Height&&b.Right<=b.Parent.ClientSize.Width,"Clipped flow button: "+b.Text);form.Hide();}
  [STAThread]public static int Main(string[] args){try{Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);string dir=args[0];Directory.CreateDirectory(dir);
   var fixtureStore=new Store(Path.Combine(dir,"fixture-"+Guid.NewGuid().ToString("N")));var fixture=new AppData();fixture.Projects.Add(new Project{Name="写稿",Stages=Planner.Writing()});fixture.Projects.Add(new Project{Name="已完成的阅读",Completed=true});fixtureStore.Save(fixture);
   using(var form=new MainForm(fixtureStore)){Layout(form);var tabs=All(form).OfType<TabControl>().Single();Check(tabs.TabPages.Count==3,"three main surfaces");foreach(TabPage page in tabs.TabPages){page.Bounds=tabs.DisplayRectangle;Layout(page);}Check(All(form).OfType<Button>().Any(b=>b.Text=="配置 AI API"),"API settings available");Check(All(form).OfType<Button>().Any(b=>b.Text=="立即同步"),"sync available");Check(All(form).OfType<Button>().Any(b=>b.Text=="导入并合并"),"import available");Check(All(form).OfType<Button>().Any(b=>b.Text=="导出全部数据"),"export available");Check(All(form).Single(c=>c.Name=="ProjectList").GetType()==typeof(TaskListBox),"task list has no checkboxes");Check(All(form).OfType<Button>().Any(b=>b.Text=="完成任务"),"complete button");Render(form,Path.Combine(dir,"main-v16.png"));var clock=All(form).OfType<Label>().Single(l=>l.Name=="MainCountdown");using(var g=clock.CreateGraphics())Check(clock.ClientSize.Height>=clock.Font.GetHeight(g),"countdown height must fit actual DPI font");var completed=All(form).OfType<RadioButton>().Single(c=>c.Text=="已完成");completed.Checked=true;Check(All(form).OfType<ListBox>().Single(l=>l.Name=="ProjectList").Items.Count==1,"completed view separate");Render(form,Path.Combine(dir,"completed-v16.png"));}
   using(var form=new ProjectDialog(new Project(),new ApiConfig(),dir)){Layout(form);Check(!All(form).OfType<CheckBox>().Any(c=>c.Text=="AI 拆解子任务"),"no automatic AI checkbox");Check(All(form).OfType<DataGridView>().Single().ContextMenuStrip.Items.Count==2,"reordering actions");Check(All(form).OfType<Button>().Any(b=>b.Text=="保存任务"),"offline save available");Render(form,Path.Combine(dir,"project-v16.png"));}
   var detailData=new AppData();var detailWriting=new Project{Name="写稿",NextStep="完成文章"};var detailReading=new Project{Name="阅读",NextStep="读完一章"};detailData.Projects.Add(detailWriting);detailData.Projects.Add(detailReading);detailData.Records.Add(new TimeRecord{ProjectId=detailWriting.Id,ProjectName=detailWriting.Name,Day=DateTime.Today.ToString("yyyy-MM-dd"),StartUtc=DateTime.UtcNow.AddMinutes(-5),EndUtc=DateTime.UtcNow,Seconds=300,Outcome="手动结束",StageName="写开头"});using(var form=new ProjectDetailsDialog(detailData,detailWriting.Id)){form.Opacity=0;form.ShowInTaskbar=false;form.Show();Application.DoEvents();var search=(TextBox)Field(form,"search");var choices=(ComboBox)Field(form,"project");Check(choices.Items.Count==2,"empty project search lists all projects");search.Text="阅读";Application.DoEvents();Check(choices.Items.Count==1&&Convert.ToString(choices.Items[0])=="阅读","project search filters choices while typing");search.Text="";Application.DoEvents();Check(choices.Items.Count==2,"clearing project search restores all projects");Render(form,Path.Combine(dir,"project-details-v16.png"));}
   using(var form=new ApiDialog(new ApiConfig(),dir)){Layout(form);Check(All(form).OfType<TextBox>().Count()==3,"endpoint model key inputs");Check(All(form).OfType<TextBox>().Count(t=>t.UseSystemPasswordChar)==1,"key masked");Render(form,Path.Combine(dir,"api-v16.png"));}
   using(var form=new SyncDialog(new SyncConfig(),dir)){Layout(form);Check(All(form).OfType<TextBox>().Count()==3,"sync url user password");Check(All(form).OfType<TextBox>().Count(t=>t.UseSystemPasswordChar)==1,"sync password masked");Render(form,Path.Combine(dir,"sync-v16.png"));}
   using(var form=new Notice("专注结束，时间已保存","写作\r\n本轮专注：00:00:27\r\n\r\n已经投入的时间都算数。准备好时，再开始下一步。",new KeyValuePair<string,Action>("知道了",null))){Layout(form);Check(form.TopMost,"reminders topmost");Render(form,Path.Combine(dir,"notice-v16.png"));Check(form.Detail.ScrollBars==ScrollBars.Vertical,"long reminder text scrolls");}
   using(var form=new MiniTimer(()=>{},()=>{},()=>{},()=>{})){form.UpdateState("写稿","24:51","番茄钟 · 专注进行中",Phase.Focus);Render(form,Path.Combine(dir,"mini-v16.png"));Check(form.TopMost,"mini topmost");Check(All(form).OfType<Label>().Single(l=>l.Name=="MiniCountdown").Text=="24:51","mini displays shared value");}
   using(var form=new MainForm(fixtureStore)){form.Opacity=0;form.ShowInTaskbar=false;form.Show();Check(((Button)Field(form,"start")).Visible&&!((Button)Field(form,"pause")).Visible&&!((Button)Field(form,"stop")).Visible,"idle actions");Call(form,"StartSelected");Check(!((Button)Field(form,"start")).Visible&&((Button)Field(form,"pause")).Visible,"focus actions");Render(form,Path.Combine(dir,"focus-v16.png"));Call(form,"BeginBreak");var popup=(Notice)Field(form,"notice");popup.Opacity=0;string before=popup.Detail.Text;DateTime until=DateTime.UtcNow.AddSeconds(1.2);while(DateTime.UtcNow<until){Application.DoEvents();System.Threading.Thread.Sleep(20);}Check(popup.Detail.Text==before,"rest popup stays static so scrolling is preserved");form.Show();Check(!((Button)Field(form,"pause")).Visible&&((Button)Field(form,"rest")).Text=="提前专注","break actions");Render(form,Path.Combine(dir,"break-v16.png"));Call(form,"EarlyFocus");Check(((FocusEngine)Field(form,"engine")).State==Phase.Focus,"early focus works");var tabs=All(form).OfType<TabControl>().Single();tabs.SelectedIndex=1;Render(form,Path.Combine(dir,"history-v16.png"));var grid=(DataGridView)Field(form,"records");Check(!grid.Columns["start"].Visible,"brief history default");((RadioButton)Field(form,"briefHistory")).Checked=false;Check(grid.Columns["start"].Visible,"detail history toggle");tabs.SelectedIndex=2;Render(form,Path.Combine(dir,"settings-v16.png"));Call(form,"CloseNotice");}
   using(var fresh=new FreshContentDialog(new FreshContent{Title="中文内容",Body="第一句。第二句。第三句。第四句。"},"",x=>{})){fresh.Opacity=0;fresh.Show();Application.DoEvents();var body=All(fresh).OfType<TextBox>().Single();Check(body.SelectionLength==0&&body.Text.Contains("\r\n\r\n"),"fresh content opens unselected and formatted into paragraphs");}
   using(var favorites=new FavoritesDialog(new[]{new FreshContent{Title="宝藏",Body="内容",Favorite=true}},()=>{})){Check(All(favorites).OfType<Button>().Any(b=>b.Text=="清空宝藏"),"favorites provide a clear action");}
   var reviewData=new AppData();reviewData.ChallengeAdjustments.Add(new ChallengeAdjustment{ProjectName="项目",StageName="步骤",Reason="理由"});using(var review=new SelfReviewDialog(reviewData,new ApiConfig(),()=>{})){Check(All(review).OfType<Button>().Any(b=>b.Text=="清空记录"),"self review provides a clear action");Check(All(review).OfType<Button>().Any(b=>b.Text=="查看原始记录"),"raw review records move to a child entry");Check(All(review).OfType<TextBox>().Any(b=>b.ReadOnly),"saved analysis has a scrollable reading area");}
   using(var form=new EncouragementDialog(new AppData())){Render(form,Path.Combine(dir,"encouragement-v16.png"));}
   using(var form=new MiniTimer(()=>{},()=>{},()=>{},()=>{})){form.UpdateState("休息一下","04:23","休息",Phase.Break);Render(form,Path.Combine(dir,"mini-break-v16.png"));Check(form.ContextMenuStrip.Items[0].Text=="透明度","mini opacity control");}
   var local=new AppData();var project=new Project{Name="统计测试"};var engine=new FocusEngine(local);var now=DateTime.UtcNow;engine.Start(project,now);engine.Tick(now.AddSeconds(10));engine.BeginBreak(now.AddSeconds(10));Check(engine.EndBreakEarly(now.AddSeconds(20)),"early break end accepted");engine.Tick(now.AddSeconds(30));engine.Stop(now.AddSeconds(30),"手动结束");Check(local.Records.Select(r=>r.SessionId).Distinct().Count()==1,"one timing session spans breaks");Check(local.Records.Sum(r=>r.Seconds)==20,"break excluded from session average");engine.Start(project,now.AddSeconds(40));engine.Tick(now.AddSeconds(50));engine.Stop(now.AddSeconds(50),"结束");Check(local.Records.Select(r=>r.SessionId).Distinct().Count()==2,"new start after end creates session");
   using(var form=new MainForm(fixtureStore)){form.Opacity=0;form.ShowInTaskbar=false;form.Show();var p=((AppData)Field(form,"data")).Projects.First(x=>!x.Completed);Check(((CheckedListBox)Field(form,"subtasks")).Visible,"full plan expanded by default");string first=TaskSupport.Next(p);Call(form,"FinishStep");Check(p.Stages[0].Done&&TaskSupport.Next(p)!=first,"step completion advances current action");Call(form,"UndoStep");Check(!p.Stages[0].Done&&TaskSupport.Next(p)==first,"step undo restores action");p.SmallStep="只打开文档";Call(form,"FinishStep");Check(p.SmallStep==""&&!p.Stages[0].Done,"starter step does not complete entire stage");Call(form,"UndoStep");Check(p.SmallStep=="只打开文档","starter undo restores small action");p.ResumeNote="正文第二段";p.DoneWhen="保存初稿";Call(form,"StartSelected");Call(form,"PauseResume");Check(p.LastCheckpoint.Contains("只打开文档"),"pause remembers current action");Render(form,Path.Combine(dir,"recovery-v16.png"));Call(form,"CloseNotice");}
   using(var form=new ResumeDialog(new Project{Name="写稿",ResumeNote="正文第二段",SmallStep="打开草稿，写一句承接上一段的话。",DoneWhen="保存一份可读的初稿"})){Render(form,Path.Combine(dir,"resume-card-v16.png"));}
   using(var form=new StuckDialog(new Project{Name="写稿"})){Render(form,Path.Combine(dir,"stuck-v16.png"));}
   using(var form=new MiniTimer(()=>{},()=>{},()=>{},()=>{})){form.UpdateState("写稿","24:51","专注中",Phase.Focus);form.SetLowStimulus(true);Check(!((Timer)Field(form,"animation")).Enabled,"low stimulation stops mini animation");form.SetLowStimulus(false);Check(((Timer)Field(form,"animation")).Enabled,"animation can be restored");}
   var draftProject=new Project{Name="保留接续卡",SmallStep="打开文件",ResumeNote="桌面",DoneWhen="保存",LastCheckpoint="第一段"};using(var dialog=new ProjectDialog(draftProject,new ApiConfig(),dir)){var draft=(Project)dialog.GetType().GetMethod("Draft",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(dialog,null);Check(draft.SmallStep==draftProject.SmallStep&&draft.ResumeNote==draftProject.ResumeNote&&draft.DoneWhen==draftProject.DoneWhen,"editing preserves resume metadata");}
   using(var dialog=new ProjectDialog(new Project(),new ApiConfig(),dir,new AppData{DefaultAllowDistraction=true})){var draft=(Project)dialog.GetType().GetMethod("Draft",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(dialog,null);Check(draft.AllowDistraction,"new projects inherit the default distraction permission");}
   using(var form=new ResumeDialog(new Project{Name="写稿"})){Check(form.TryApplySuggestions(new[]{"建议：看草稿末尾","写一句话","保存一段"},0),"AI suggestions populate editable fields");var field=All(form).OfType<TextBox>().Single(x=>x.Name=="ResumeStep");field.Text="我自己的下一步";Check(!form.TryApplySuggestions(new[]{"覆盖","覆盖","覆盖"},0)&&field.Text=="我自己的下一步","late AI result preserves user edits");Render(form,Path.Combine(dir,"resume-ai-v16.png"));}
   using(var form=new SupportSettingsDialog(new AppData())){Render(form,Path.Combine(dir,"habits-v16.png"));}
   int restClicks=0,distractionClicks=0;using(var form=new MiniTimer(()=>{},()=>{},()=>{},()=>{},()=>restClicks++,null,()=>distractionClicks++)){form.Opacity=0;form.ShowInTaskbar=false;form.Show();form.UpdateState("写作","24:50","专注中",Phase.Focus,70);Check(All(form).OfType<Label>().Single(l=>l.Name=="MiniSessionTime").Text=="本次 00:01:10","mini displays actual session duration");var b=(Button)All(form).Single(x=>x.Name=="MiniRest");Check(b.Visible&&b.Enabled,"direct rest available during focus");b.PerformClick();Check(restClicks==1,"rest icon calls shared rest action");form.UpdateState("写作","24:50","暂停",Phase.Paused,70,false,null,null,true);var distraction=(Button)All(form).Single(x=>x.Name=="MiniDistraction");Check(distraction.Visible&&distraction.Enabled,"distraction icon available when enabled");distraction.PerformClick();Check(distractionClicks==1,"distraction icon calls shared action");form.UpdateState("写作","24:50","暂停",Phase.Paused,70);form.SetLowStimulus(false);Check(!((Timer)Field(form,"animation")).Enabled,"paused animation remains stopped after refresh");double position=(double)Field(form,"motionPhase");Application.DoEvents();Check((double)Field(form,"motionPhase")==position,"paused motion phase unchanged");Check(All(form).OfType<Button>().Count()==6&&!All(form).OfType<Button>().Any(x=>x.Text=="×"),"six icon buttons including distraction, withdraw and lock without close");Render(form,Path.Combine(dir,"mini-paused-v16.png"));form.Show();var lockIcon=(Button)All(form).Single(x=>x.Name=="MiniLock");lockIcon.PerformClick();Check(!b.Enabled,"locked rest disabled");lockIcon.PerformClick();form.UpdateState("写作","24:50","暂停",Phase.Paused,70,true,new Stage{Title="写开头"});Check(All(form).Single(x=>x.Name=="MiniSessionTime").Text=="写开头","mini shows next stage title");Check(All(form).Single(x=>x.Name=="MiniStageDone").Visible,"stage checkbox visible");form.UpdateState("挑战","90:00","挑战",Phase.Focus,30,false);Check(!b.Enabled,"challenge cannot silently enter pomodoro break");}
   var probe=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);probe.Start();int port=((System.Net.IPEndPoint)probe.LocalEndpoint).Port;probe.Stop();using(var server=new System.Net.HttpListener()){string address="http://127.0.0.1:"+port+"/";server.Prefixes.Add(address);server.Start();var mockStore=new Store(Path.Combine(dir,"events-"+Guid.NewGuid().ToString("N")));var mockData=new AppData{AutoEncouragement=true,Sound=false};mockData.Projects.Add(new Project{Name="事件测试"});mockStore.Save(mockData);using(var form=new MainForm(mockStore)){form.GetType().GetField("api",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(form,new ApiConfig{Endpoint=address,Model="mock"});form.Opacity=0;form.ShowInTaskbar=false;form.Show();var request=server.GetContextAsync();Call(form,"StartSelected");Call(form,"BeginBreak");var popup=(Notice)Field(form,"notice");Respond(request,popup,"刚进入休息","休息鼓励");Check(!popup.Detail.Text.Contains("休息剩余")&&popup.Detail.Text.Contains("项目："),"rest text static with project name");request=server.GetContextAsync();form.GetType().GetMethod("EndFocus",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(form,new object[]{"手动结束"});Respond(request,(Notice)Field(form,"notice"),"本次计时已结束","结束鼓励");request=server.GetContextAsync();Call(form,"CompleteTask");Respond(request,(Notice)Field(form,"notice"),"刚完成任务","完成鼓励");Call(form,"CloseNotice");}}
   Check(engine.SessionSeconds==10,"session duration resets on a new timing session");
   var manualProbe=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);manualProbe.Start();int manualPort=((System.Net.IPEndPoint)manualProbe.LocalEndpoint).Port;manualProbe.Stop();using(var server=new System.Net.HttpListener()){string url="http://127.0.0.1:"+manualPort+"/";server.Prefixes.Add(url);server.Start();var config=new ApiConfig{Endpoint=url,Model="mock"};var pending=server.GetContextAsync();var original=new Project{Name="保存不联网",AiEnabled=true,Stages=Planner.Writing()};using(var form=new ProjectDialog(original,config,dir)){form.Opacity=0;form.Show();((TextBox)Field(form,"name")).Text="改名后保存";((NumericUpDown)Field(form,"minutes")).Value=10;Call(form,"SaveTask");PumpBriefly();Check(form.Result!=null&&form.Result.Stages.Count==5&&form.Result.Name=="改名后保存","save preserves plan after edits");Check(!pending.IsCompleted,"task save sends zero API requests despite legacy AI flag");}
    var migrated=Store.Decode(Store.Encode(new AppData{AutoResumeSuggestions=true}));using(var form=new ResumeDialog(new Project{Name="空白接续卡"},config,migrated)){form.Opacity=0;form.Show();PumpBriefly();Check(!pending.IsCompleted,"opening resume card after upgrade sends zero requests");form.Close();}
    Project generatedProject;using(var form=new ProjectDialog(new Project{Name="显式生成"},config,dir)){form.Opacity=0;form.Show();((Button)Field(form,"generate")).PerformClick();WaitFor(()=>pending.IsCompleted);var ctx=pending.Result;using(var reader=new StreamReader(ctx.Request.InputStream)){string body=reader.ReadToEnd();Check(body.Contains("i-have-adhd"),"explicit button sends primary skill policy");}string plan="{\"stages\":[{\"remaining\":100,\"title\":\"打开文档\",\"action\":\"打开草稿\"},{\"remaining\":50,\"title\":\"保存\",\"action\":\"保存一段\"}]}";byte[] bytes=System.Text.Encoding.UTF8.GetBytes(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(new{choices=new[]{new{message=new{content=plan}}}}));ctx.Response.ContentLength64=bytes.Length;ctx.Response.OutputStream.Write(bytes,0,bytes.Length);ctx.Response.Close();WaitFor(()=>!(bool)Field(form,"busy"));pending=server.GetContextAsync();Call(form,"SaveTask");PumpBriefly();Check(!pending.IsCompleted&&form.Result.Stages[0].Title=="打开文档","saving generated plan does not regenerate");generatedProject=form.Result;}
    using(var form=new ProjectDialog(generatedProject,config,dir)){Call(form,"SaveTask");PumpBriefly();Check(!pending.IsCompleted&&form.Result!=null,"repeated save sends zero requests");}
   }
   V16Checks(dir);
   Console.WriteLine("PASS: save/open zero-network regression, explicit AI button, policy priority, trigger events, editable AI drafts, mini controls, deletion, subtask tracking and shared break request. No live API credentials used.");return 0;
  }catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}
  static void V16Checks(string dir){
   var store=new Store(Path.Combine(dir,"v16-"+Guid.NewGuid().ToString("N")));var data=new AppData{Sound=false,FocusMinutes=1,AutoEncouragement=true};var project=new Project{Name="早点睡觉",Stages=Planner.Writing()};data.Projects.Add(project);store.Save(data);
   var socket=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);socket.Start();int port=((System.Net.IPEndPoint)socket.LocalEndpoint).Port;socket.Stop();using(var server=new System.Net.HttpListener()){string address="http://127.0.0.1:"+port+"/";server.Prefixes.Add(address);server.Start();using(var form=new MainForm(store)){
    form.GetType().GetField("api",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(form,new ApiConfig{Endpoint=address,Model="mock"});form.Opacity=0;form.Show();Render(form,Path.Combine(dir,"five-stages-v16.png"));var list=(CheckedListBox)Field(form,"subtasks");Check(list.Items.Count>=5,"five full stage rows reserved");Check(list.ClientSize.Height/Math.Max(1,list.ItemHeight)>=5,"five stage rows visible without scrolling");Check(!All(form).OfType<Button>().Any(b=>(b.Text??"").Contains("撤回")),"main panel has no duplicate undo button");var projectList=(ListBox)Field(form,"projects");Check(Convert.ToString(projectList.Items[0]).StartsWith("▸ "),"projects with subtasks have a visible marker");project.LastCheckpoint="上次停在：整段动作与完成标准";Check(TaskSupport.Checkpoint(project)=="上次停在："+project.Stages[0].Title,"checkpoint shows only the subtask name");form.Show();Call(form,"StartSelected");Call(form,"ShowMini");var mini=(MiniTimer)Field(form,"mini");var box=(CheckBox)All(mini).Single(c=>c.Name=="MiniStageDone");var finish=typeof(CheckBox).GetMethod("OnClick",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);finish.Invoke(box,new object[]{EventArgs.Empty});var engine=(FocusEngine)Field(form,"engine");Check(engine.Current.Stages[0].Done&&!engine.Current.Stages[1].Done,"mini checkbox advances one step");Check(All(mini).Single(c=>c.Name=="MiniSessionTime").Text==engine.Current.Stages[1].Title,"next stage refreshes in mini");var undoIcon=(Button)All(mini).Single(c=>c.Name=="MiniWithdraw");var toggleIcon=(Button)All(mini).Single(c=>c.Name=="MiniToggle");Check(undoIcon.Left<toggleIcon.Left,"mini undo sits beside the current subtask before timer controls");var lockIcon=(Button)All(mini).Single(c=>c.Name=="MiniLock");lockIcon.PerformClick();finish.Invoke(box,new object[]{EventArgs.Empty});Check(!engine.Current.Stages[1].Done,"locked checkbox cannot complete stage");lockIcon.PerformClick();Render(mini,Path.Combine(dir,"mini-stage-v16.png"));
    var request=server.GetContextAsync();engine.LastUtc=DateTime.UtcNow.AddSeconds(-61);var evt=engine.Tick(DateTime.UtcNow);Console.WriteLine("due probe: "+evt+" "+engine.State+" seconds="+engine.RunSeconds+" goal="+engine.GoalMinutes+" auto="+engine.Data.AutoEncouragement);form.GetType().GetMethod("HandleEvent",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(form,new object[]{evt});var due=(Notice)Field(form,"notice");WaitFor(()=>request.IsCompleted);Call(form,"BeginBreak");var rest=(Notice)Field(form,"notice");Respond(request,rest,"等待休息确认","共用的休息鼓励");var noSecond=server.GetContextAsync();Call(form,"ShowRest");PumpBriefly();Check(!noSecond.IsCompleted,"rest re-open makes no second API request");Check(((Notice)Field(form,"notice")).Detail.Text.Contains("共用的休息鼓励"),"rest reuses same AI text");Call(form,"CloseNotice");var hidden=new Notice("隐藏","不展示");form.GetType().GetMethod("QueueBreakEncouragement",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(form,new object[]{hidden});PumpBriefly();Check(!noSecond.IsCompleted,"hidden target causes no request");hidden.Dispose();
    engine.Stop(DateTime.UtcNow,"测试结束");Call(form,"DeleteSelected");Check(engine.Current.Deleted,"active-list deletion tombstone");Check(store.Load().Records.Count==0,"delete purges logs");mini.Close();
   }}
   var completeStore=new Store(Path.Combine(dir,"delete-completed-"+Guid.NewGuid().ToString("N")));var doneData=new AppData{Sound=false};doneData.Projects.Add(new Project{Name="已完成",Completed=true});completeStore.Save(doneData);using(var form=new MainForm(completeStore)){form.Opacity=0;form.Show();((RadioButton)Field(form,"completedView")).Checked=true;Call(form,"DeleteSelected");Check(completeStore.Load().Projects[0].Deleted,"completed task deletion supported");}
  }
 }
}
